# Part 1: Data Assessment

## Objective

Examine existing arXiv research papers in the Artificial Intelligence category, identify the available file types and metadata,
assess the quality of the data, and determine what information is usable for the RAG pipeline.

In [1]:
# setup, imports

import io
import time
import requests
import feedparser
from pathlib import Path
import pandas as pd
from pypdf import PdfReader

cwd = Path.cwd()
project_root = cwd.parent if cwd.name == "notebooks" else cwd

In [2]:
# define arxiv fetch + extraction functions

ARXIV_API_URL = "http://export.arxiv.org/api/query"

def sanitize_text(text):
    return text.encode("utf-8", errors="ignore").decode("utf-8") if isinstance(text, str) else text

def fetch_arxiv_metadata(query, total_results, batch_size=100):
    papers = []
    for start in range(0, total_results, batch_size):
        params = {
            "search_query": query,
            "start": start,
            "max_results": min(batch_size, total_results - start),
            "sortBy": "submittedDate",
            "sortOrder": "descending",
        }
        response = requests.get(ARXIV_API_URL, params=params, timeout=30)
        response.raise_for_status()
        feed = feedparser.parse(response.text)

        for entry in feed.entries:
            arxiv_id = entry.id.split("/abs/")[-1]
            pdf_url = next(
                (link.href for link in entry.links if link.get("title") == "pdf"), None
            )
            papers.append({
                "arxiv_id": arxiv_id,
                "title": entry.title.replace("\n", " ").strip(),
                "author": "; ".join(a.name for a in entry.authors),
                "published": entry.published,
                "pdf_url": pdf_url,
            })

        print(f"fetched metadata for {len(papers)}/{total_results} papers")
        time.sleep(3)
    return papers


def extract_pdf_pages_from_url(paper):
    response = requests.get(paper["pdf_url"], timeout=30)
    response.raise_for_status()
    reader = PdfReader(io.BytesIO(response.content))

    records = []
    for page_number, page in enumerate(reader.pages, start=1):
        raw_text = sanitize_text(page.extract_text() or "")
        records.append({
            "arxiv_id": paper["arxiv_id"],
            "title": sanitize_text(paper["title"]),
            "author": sanitize_text(paper["author"]),
            "published": paper["published"],
            "page_number": page_number,
            "num_pages": len(reader.pages),
            "raw_text": raw_text,
        })
    return records

In [6]:
# fetch metadata and extract pages

# skip this cell if you're about to run the ArxivIngestionPipeline class (in Part 2) below instead, since running both fetches everything twice

paper_metadata = fetch_arxiv_metadata("cat:cs.AI", total_results=500) # importing 500 papers for now for testing the api, but when we scale to ingesting updated+new papers every day, we'd have to export to a .py script and run a scheduled workflow for daily imports
metadata_df = pd.DataFrame(paper_metadata)

all_pages = []
for i, paper in enumerate(paper_metadata, start=1):
    if paper["pdf_url"] is None:
        continue
    try:
        all_pages.extend(extract_pdf_pages_from_url(paper))
    except Exception as e:
        print(f"failed to extract {paper['arxiv_id']}: {e}")
    if i % 25 == 0:
        print(f"processed {i}/{len(paper_metadata)} papers")
    time.sleep(3) # arxiv rate limit policy asks for no more than 1 request every 3 seconds

pages_df = pd.DataFrame(all_pages)
print(f"extracted {len(pages_df)} pages from {pages_df['arxiv_id'].nunique()} papers")

fetched metadata for 100/500 papers
fetched metadata for 200/500 papers
fetched metadata for 300/500 papers
fetched metadata for 400/500 papers
fetched metadata for 500/500 papers
processed 25/500 papers
processed 50/500 papers

Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.

processed 75/500 papers
processed 100/500 papers

Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.

processed 125/500 papers

Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
Impossible to decode XFormObject /Im13: Reached maximum number of tokens per stream.

processed 150/500 papers
processed 175/500 papers

Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.

processed 200/500 papers
processed 225/500 papers

Skipping broken line b'14fa   14ff   10300': Odd-length string
Skipping broken line b'1500   1518   10306': Odd-length string
Skipping broken line b'1519   151c   10320': Odd-length string
Skipping broken line b'151d   1573   1d300': Odd-length string
Skipping broken line b'1574   1575   1d538': Odd-length string
Skipping broken line b'1576   1579   1d53b': Odd-length string
Skipping broken line b'157a   157e   1d540': Odd-length string
Skipping broken line b'1580   1586   1d54a': Odd-length string
Skipping broken line b'1587   15a0   1d552': Odd-length string
Skipping broken line b'15a1   15d4   1d5a0': Odd-length string
Skipping broken line b'15d5   15e8   1d7d8': Odd-length string
Skipping broken line b'15e9   15ec   1ee00': Odd-length string
Skipping broken line b'15ed   15ff   1ee05': Odd-length string
Skipping broken line b'1600   1607   1ee18': Odd-length string
Skipping broken line b'1608   1609   1ee21': Odd-length string
Skipping broken line b'160c   1615   1ee29': Odd-length string
Skipping broken line b'1616   1619   1ee34': Odd-length string
Skipping broken line b'161c   161d   1ee61': Odd-length string
Skipping broken line b'161f   1622   1ee67': Odd-length string
Skipping broken line b'1623   1629   1ee6c': Odd-length string
Skipping broken line b'162a   162d   1ee74': Odd-length string
Skipping broken line b'162e   1631   1ee79': Odd-length string
Skipping broken line b'1633   1696   1f030': Odd-length string
Skipping broken line b'1697   16a5   1f0a0': Odd-length string
Skipping broken line b'16a6   16b3   1f0b1': Odd-length string
Skipping broken line b'16b4   16c2   1f0c1': Odd-length string
Skipping broken line b'16c3   16d1   1f0d1': Odd-length string
Skipping broken line b'16d2   16d3   1f42d': Odd-length string
Skipping broken line b'16d6   16f9   1f600': Odd-length string
Skipping broken line b'16fa   16ff   1f625': Odd-length string
Skipping broken line b'1701   1714   1f62d': Odd-length string
Got invalid hex string: Odd-length string (b'1d546')
Got invalid hex string: Odd-length string (b'1ee24')
Got invalid hex string: Odd-length string (b'1ee27')
Got invalid hex string: Odd-length string (b'1ee39')
Got invalid hex string: Odd-length string (b'1ee3b')
Got invalid hex string: Odd-length string (b'1ee64')
Got invalid hex string: Odd-length string (b'1ee7e')
Got invalid hex string: Odd-length string (b'1f431')
Got invalid hex string: Odd-length string (b'1f435')
Got invalid hex string: Odd-length string (b'1f62b')
Skipping broken line b'14fa   14ff   10300': Odd-length string
Skipping broken line b'1500   1518   10306': Odd-length string
Skipping broken line b'1519   151c   10320': Odd-length string
Skipping broken line b'151d   1573   1d300': Odd-length string
Skipping broken line b'1574   1575   1d538': Odd-length string
Skipping broken line b'1576   1579   1d53b': Odd-length string
Skipping broken line b'157a   157e   1d540': Odd-length string
Skipping broken line b'1580   1586   1d54a': Odd-length string
Skipping broken line b'1587   15a0   1d552': Odd-length string
Skipping broken line b'15a1   15d4   1d5a0': Odd-length string
Skipping broken line b'15d5   15e8   1d7d8': Odd-length string
Skipping broken line b'15e9   15ec   1ee00': Odd-length string
Skipping broken line b'15ed   15ff   1ee05': Odd-length string
Skipping broken line b'1600   1607   1ee18': Odd-length string
Skipping broken line b'1608   1609   1ee21': Odd-length string
Skipping broken line b'160c   1615   1ee29': Odd-length string
Skipping broken line b'1616   1619   1ee34': Odd-length string
Skipping broken line b'161c   161d   1ee61': Odd-length string
Skipping broken line b'161f   1622   1ee67': Odd-length string
Skipping broken line b'1623   1629   1ee6c': Odd-length string
Skipping broken line b'162a   162d   1ee74': Odd-length string
Skipping broken line b'162e   1631   1ee79': Odd-length string
Skipping broken line b'1633   1696   1f030': Odd-length string
Skipping broken line b'1697   16a5   1f0a0': Odd-length string
Skipping broken line b'16a6   16b3   1f0b1': Odd-length string
Skipping broken line b'16b4   16c2   1f0c1': Odd-length string
Skipping broken line b'16c3   16d1   1f0d1': Odd-length string
Skipping broken line b'16d2   16d3   1f42d': Odd-length string
Skipping broken line b'16d6   16f9   1f600': Odd-length string
Skipping broken line b'16fa   16ff   1f625': Odd-length string
Skipping broken line b'1701   1714   1f62d': Odd-length string
Got invalid hex string: Odd-length string (b'1d546')
Got invalid hex string: Odd-length string (b'1ee24')
Got invalid hex string: Odd-length string (b'1ee27')
Got invalid hex string: Odd-length string (b'1ee39')
Got invalid hex string: Odd-length string (b'1ee3b')
Got invalid hex string: Odd-length string (b'1ee64')
Got invalid hex string: Odd-length string (b'1ee7e')
Got invalid hex string: Odd-length string (b'1f431')
Got invalid hex string: Odd-length string (b'1f435')
Got invalid hex string: Odd-length string (b'1f62b')

processed 250/500 papers
processed 275/500 papers

Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.

processed 300/500 papers

Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.

processed 325/500 papers

Impossible to decode XFormObject /Im10: Reached maximum number of tokens per stream.

processed 350/500 papers
processed 375/500 papers
processed 400/500 papers
processed 425/500 papers

Skipping broken line b'14fd   14ff   10300': Odd-length string
Skipping broken line b'1500   151b   10303': Odd-length string
Skipping broken line b'151c   151f   10320': Odd-length string
Skipping broken line b'1520   1576   1d300': Odd-length string
Skipping broken line b'1577   1578   1d538': Odd-length string
Skipping broken line b'1579   157c   1d53b': Odd-length string
Skipping broken line b'157d   1581   1d540': Odd-length string
Skipping broken line b'1583   1589   1d54a': Odd-length string
Skipping broken line b'158a   15a3   1d552': Odd-length string
Skipping broken line b'15a4   15d7   1d5a0': Odd-length string
Skipping broken line b'15d8   15eb   1d7d8': Odd-length string
Skipping broken line b'15ec   15ef   1ee00': Odd-length string
Skipping broken line b'15f0   15ff   1ee05': Odd-length string
Skipping broken line b'1600   160a   1ee15': Odd-length string
Skipping broken line b'160b   160c   1ee21': Odd-length string
Skipping broken line b'160f   1618   1ee29': Odd-length string
Skipping broken line b'1619   161c   1ee34': Odd-length string
Skipping broken line b'161f   1620   1ee61': Odd-length string
Skipping broken line b'1622   1625   1ee67': Odd-length string
Skipping broken line b'1626   162c   1ee6c': Odd-length string
Skipping broken line b'162d   1630   1ee74': Odd-length string
Skipping broken line b'1631   1634   1ee79': Odd-length string
Skipping broken line b'1636   1699   1f030': Odd-length string
Skipping broken line b'169a   16a8   1f0a0': Odd-length string
Skipping broken line b'16a9   16b6   1f0b1': Odd-length string
Skipping broken line b'16b7   16c5   1f0c1': Odd-length string
Skipping broken line b'16c6   16d4   1f0d1': Odd-length string
Skipping broken line b'16d5   16dc   1f311': Odd-length string
Skipping broken line b'16dd   16de   1f42d': Odd-length string
Skipping broken line b'16e1   16ff   1f600': Odd-length string
Skipping broken line b'1700   1704   1f61f': Odd-length string
Skipping broken line b'1705   170b   1f625': Odd-length string
Skipping broken line b'170c   171f   1f62d': Odd-length string
Got invalid hex string: Odd-length string (b'1d546')
Got invalid hex string: Odd-length string (b'1ee24')
Got invalid hex string: Odd-length string (b'1ee27')
Got invalid hex string: Odd-length string (b'1ee39')
Got invalid hex string: Odd-length string (b'1ee3b')
Got invalid hex string: Odd-length string (b'1ee64')
Got invalid hex string: Odd-length string (b'1ee7e')
Got invalid hex string: Odd-length string (b'1f431')
Got invalid hex string: Odd-length string (b'1f435')
Got invalid hex string: Odd-length string (b'1f643')

processed 450/500 papers

could not convert string to float: b'0.000000000000-5684342' : FloatObject (b'0.000000000000-5684342') invalid; use 0.0 instead
could not convert string to float: b'0.000000000000-5684342' : FloatObject (b'0.000000000000-5684342') invalid; use 0.0 instead
could not convert string to float: b'0.000000000000-5684342' : FloatObject (b'0.000000000000-5684342') invalid; use 0.0 instead
Skipping broken line b'14f6   14ff   10300': Odd-length string
Skipping broken line b'1500   1514   1030a': Odd-length string
Skipping broken line b'1515   1518   10320': Odd-length string
Skipping broken line b'1519   156f   1d300': Odd-length string
Skipping broken line b'1570   1571   1d538': Odd-length string
Skipping broken line b'1572   1575   1d53b': Odd-length string
Skipping broken line b'1576   157a   1d540': Odd-length string
Skipping broken line b'157c   1582   1d54a': Odd-length string
Skipping broken line b'1583   159c   1d552': Odd-length string
Skipping broken line b'159d   15d0   1d5d4': Odd-length string
Skipping broken line b'15d1   15ff   1d756': Odd-length string
Skipping broken line b'1600   160a   1d785': Odd-length string
Skipping broken line b'160b   1614   1d7d8': Odd-length string
Skipping broken line b'1615   161e   1d7ec': Odd-length string
Skipping broken line b'161f   1682   1f030': Odd-length string
Skipping broken line b'1683   1691   1f0a0': Odd-length string
Skipping broken line b'1692   169f   1f0b1': Odd-length string
Skipping broken line b'16a0   16ae   1f0c1': Odd-length string
Skipping broken line b'16af   16bd   1f0d1': Odd-length string
Skipping broken line b'16be   16bf   1f42d': Odd-length string
Skipping broken line b'16c2   16e5   1f600': Odd-length string
Skipping broken line b'16e6   16ec   1f625': Odd-length string
Skipping broken line b'16ed   16ff   1f62d': Odd-length string
Got invalid hex string: Odd-length string (b'1d546')
Got invalid hex string: Odd-length string (b'1f431')
Got invalid hex string: Odd-length string (b'1f435')
Got invalid hex string: Odd-length string (b'1f640')
Skipping broken line b'14fa   14ff   10300': Odd-length string
Skipping broken line b'1500   1518   10306': Odd-length string
Skipping broken line b'1519   151c   10320': Odd-length string
Skipping broken line b'151d   1573   1d300': Odd-length string
Skipping broken line b'1574   1575   1d538': Odd-length string
Skipping broken line b'1576   1579   1d53b': Odd-length string
Skipping broken line b'157a   157e   1d540': Odd-length string
Skipping broken line b'1580   1586   1d54a': Odd-length string
Skipping broken line b'1587   15a0   1d552': Odd-length string
Skipping broken line b'15a1   15d4   1d5a0': Odd-length string
Skipping broken line b'15d5   15e8   1d7d8': Odd-length string
Skipping broken line b'15e9   15ec   1ee00': Odd-length string
Skipping broken line b'15ed   15ff   1ee05': Odd-length string
Skipping broken line b'1600   1607   1ee18': Odd-length string
Skipping broken line b'1608   1609   1ee21': Odd-length string
Skipping broken line b'160c   1615   1ee29': Odd-length string
Skipping broken line b'1616   1619   1ee34': Odd-length string
Skipping broken line b'161c   161d   1ee61': Odd-length string
Skipping broken line b'161f   1622   1ee67': Odd-length string
Skipping broken line b'1623   1629   1ee6c': Odd-length string
Skipping broken line b'162a   162d   1ee74': Odd-length string
Skipping broken line b'162e   1631   1ee79': Odd-length string
Skipping broken line b'1633   1696   1f030': Odd-length string
Skipping broken line b'1697   16a5   1f0a0': Odd-length string
Skipping broken line b'16a6   16b3   1f0b1': Odd-length string
Skipping broken line b'16b4   16c2   1f0c1': Odd-length string
Skipping broken line b'16c3   16d1   1f0d1': Odd-length string
Skipping broken line b'16d2   16d3   1f42d': Odd-length string
Skipping broken line b'16d6   16f9   1f600': Odd-length string
Skipping broken line b'16fa   16ff   1f625': Odd-length string
Skipping broken line b'1701   1714   1f62d': Odd-length string
Got invalid hex string: Odd-length string (b'1d546')
Got invalid hex string: Odd-length string (b'1ee24')
Got invalid hex string: Odd-length string (b'1ee27')
Got invalid hex string: Odd-length string (b'1ee39')
Got invalid hex string: Odd-length string (b'1ee3b')
Got invalid hex string: Odd-length string (b'1ee64')
Got invalid hex string: Odd-length string (b'1ee7e')
Got invalid hex string: Odd-length string (b'1f431')
Got invalid hex string: Odd-length string (b'1f435')
Got invalid hex string: Odd-length string (b'1f62b')

processed 475/500 papers

Skipping broken line b'11cd   11d2   10780': Odd-length string
Skipping broken line b'11d3   11fc   10787': Odd-length string
Skipping broken line b'11fd   11ff   107b2': Odd-length string
Skipping broken line b'1200   1205   107b5': Odd-length string
Skipping broken line b'1206   1224   1df00': Odd-length string
Skipping broken line b'1225   122a   1df25': Odd-length string
Skipping broken line b'0d04   0d09   10780': Odd-length string
Skipping broken line b'0d0a   0d33   10787': Odd-length string
Skipping broken line b'0d34   0d3c   107b2': Odd-length string
Skipping broken line b'0d3d   0d5b   1df00': Odd-length string
Skipping broken line b'0d5c   0d61   1df25': Odd-length string
Skipping broken line b'11cd   11d2   10780': Odd-length string
Skipping broken line b'11d3   11fc   10787': Odd-length string
Skipping broken line b'11fd   11ff   107b2': Odd-length string
Skipping broken line b'1200   1205   107b5': Odd-length string
Skipping broken line b'1206   1224   1df00': Odd-length string
Skipping broken line b'1225   122a   1df25': Odd-length string
Skipping broken line b'11cd   11d2   10780': Odd-length string
Skipping broken line b'11d3   11fc   10787': Odd-length string
Skipping broken line b'11fd   11ff   107b2': Odd-length string
Skipping broken line b'1200   1205   107b5': Odd-length string
Skipping broken line b'1206   1224   1df00': Odd-length string
Skipping broken line b'1225   122a   1df25': Odd-length string
Skipping broken line b'0d04   0d09   10780': Odd-length string
Skipping broken line b'0d0a   0d33   10787': Odd-length string
Skipping broken line b'0d34   0d3c   107b2': Odd-length string
Skipping broken line b'0d3d   0d5b   1df00': Odd-length string
Skipping broken line b'0d5c   0d61   1df25': Odd-length string
Skipping broken line b'11cd   11d2   10780': Odd-length string
Skipping broken line b'11d3   11fc   10787': Odd-length string
Skipping broken line b'11fd   11ff   107b2': Odd-length string
Skipping broken line b'1200   1205   107b5': Odd-length string
Skipping broken line b'1206   1224   1df00': Odd-length string
Skipping broken line b'1225   122a   1df25': Odd-length string
Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
Skipping broken line b'11cd   11d2   10780': Odd-length string
Skipping broken line b'11d3   11fc   10787': Odd-length string
Skipping broken line b'11fd   11ff   107b2': Odd-length string
Skipping broken line b'1200   1205   107b5': Odd-length string
Skipping broken line b'1206   1224   1df00': Odd-length string
Skipping broken line b'1225   122a   1df25': Odd-length string
Skipping broken line b'11cd   11d2   10780': Odd-length string
Skipping broken line b'11d3   11fc   10787': Odd-length string
Skipping broken line b'11fd   11ff   107b2': Odd-length string
Skipping broken line b'1200   1205   107b5': Odd-length string
Skipping broken line b'1206   1224   1df00': Odd-length string
Skipping broken line b'1225   122a   1df25': Odd-length string
Skipping broken line b'0d04   0d09   10780': Odd-length string
Skipping broken line b'0d0a   0d33   10787': Odd-length string
Skipping broken line b'0d34   0d3c   107b2': Odd-length string
Skipping broken line b'0d3d   0d5b   1df00': Odd-length string
Skipping broken line b'0d5c   0d61   1df25': Odd-length string
Skipping broken line b'0d04   0d09   10780': Odd-length string
Skipping broken line b'0d0a   0d33   10787': Odd-length string
Skipping broken line b'0d34   0d3c   107b2': Odd-length string
Skipping broken line b'0d3d   0d5b   1df00': Odd-length string
Skipping broken line b'0d5c   0d61   1df25': Odd-length string
Skipping broken line b'11cd   11d2   10780': Odd-length string
Skipping broken line b'11d3   11fc   10787': Odd-length string
Skipping broken line b'11fd   11ff   107b2': Odd-length string
Skipping broken line b'1200   1205   107b5': Odd-length string
Skipping broken line b'1206   1224   1df00': Odd-length string
Skipping broken line b'1225   122a   1df25': Odd-length string
Skipping broken line b'11cd   11d2   10780': Odd-length string
Skipping broken line b'11d3   11fc   10787': Odd-length string
Skipping broken line b'11fd   11ff   107b2': Odd-length string
Skipping broken line b'1200   1205   107b5': Odd-length string
Skipping broken line b'1206   1224   1df00': Odd-length string
Skipping broken line b'1225   122a   1df25': Odd-length string
Skipping broken line b'11cd   11d2   10780': Odd-length string
Skipping broken line b'11d3   11fc   10787': Odd-length string
Skipping broken line b'11fd   11ff   107b2': Odd-length string
Skipping broken line b'1200   1205   107b5': Odd-length string
Skipping broken line b'1206   1224   1df00': Odd-length string
Skipping broken line b'1225   122a   1df25': Odd-length string
Skipping broken line b'0d04   0d09   10780': Odd-length string
Skipping broken line b'0d0a   0d33   10787': Odd-length string
Skipping broken line b'0d34   0d3c   107b2': Odd-length string
Skipping broken line b'0d3d   0d5b   1df00': Odd-length string
Skipping broken line b'0d5c   0d61   1df25': Odd-length string
Skipping broken line b'11cd   11d2   10780': Odd-length string
Skipping broken line b'11d3   11fc   10787': Odd-length string
Skipping broken line b'11fd   11ff   107b2': Odd-length string
Skipping broken line b'1200   1205   107b5': Odd-length string
Skipping broken line b'1206   1224   1df00': Odd-length string
Skipping broken line b'1225   122a   1df25': Odd-length string
Ignoring wrong pointing object 1173 0 (offset 0)
Ignoring wrong pointing object 1174 0 (offset 0)
Ignoring wrong pointing object 1175 0 (offset 0)

processed 500/500 papers
extracted 12133 pages from 500 papers

In [7]:
# aggregate quality checks (depends on fetching cell above, also skip if running ArxivIngestionPipeline below)

paper_quality = pages_df.groupby("arxiv_id").agg(
    num_pages=("page_number", "max"),
    pages_with_text=("raw_text", lambda s: (s.str.strip() != "").sum()),
).reset_index()
paper_quality["readable"] = paper_quality["pages_with_text"] > 0

print("papers fetched:", pages_df["arxiv_id"].nunique())
print("unreadable papers:", (~paper_quality["readable"]).sum())
print("duplicate arxiv_ids:", metadata_df["arxiv_id"].duplicated().sum())
print("missing titles:", metadata_df["title"].isna().sum())
print("missing pdf links:", metadata_df["pdf_url"].isna().sum())

paper_quality[~paper_quality["readable"]]

papers fetched: 500
unreadable papers: 0
duplicate arxiv_ids: 0
missing titles: 0
missing pdf links: 0

Empty DataFrame
Columns: [arxiv_id, num_pages, pages_with_text, readable]
Index: []

In [8]:
# spot check extracted text

sample_papers = pages_df[pages_df["page_number"] == 1].head(5)

for _, row in sample_papers.iterrows():
    print("\nARXIV ID:", row["arxiv_id"])
    print("TITLE:", row["title"])
    print(row["raw_text"][:300])
    print("-" * 80)

ARXIV ID: 2610.35868v1
TITLE: Retriever-Free Retrieval: Navigating Documents with Decision Models
Retriever-Free Retrieval: Navigating Documents with Decision Models
Chao Wan * 1 Paul J¨unger * 1 Beixi Du 1 Bodong Liu 1 Navaneetha Krishnan 2 Kilian Q. Weinberger1 2
Abstract
While language models have become dramatically
more capable, retrieval still largely relies on lex-
ical matching or simila
--------------------------------------------------------------------------------

ARXIV ID: 2610.35865v1
TITLE: Center-of-Mass Interpretation of Evolution Strategies
Center-of-Mass Interpretation of Evolution Strategies
Akshat Gupta
UC Berkeley
akshat.gupta@berkeley.edu
Abstract
Evolution strategies (ES) update a model by
sampling a population of perturbed copies,
scoring each one, and moving in the reward-
weighted direction of the perturbations. This
update is
--------------------------------------------------------------------------------

ARXIV ID: 2610.35862v1
TITLE: Learning Force-Reactive Humanoid Loco-Manipulation
Learning Force-Reactive Humanoid Loco-Manipulation
Sihang Li 1,2,§, Xiaofeng Guo 1, Jinkun Cao 1, Charlie Cheng 1, Ruihan Yang 1,
Chen Feng 1,2,†, Guanya Shi 1,3,†, Haozhi Qi 1,4,†
1Amazon FAR (Frontier AI & Robotics) 2New York University 3Carnegie Mellon University 4University of Chicago
FLoRe
c) D
--------------------------------------------------------------------------------

ARXIV ID: 2610.35847v1
TITLE: Patient-specific rubric-based evaluation of large language models across longitudinal cancer care
Patient-specific rubric-based evaluation of large language
models across longitudinal cancer care
Wei-Wei Zhang1†, Pengkai Wang 2†, Yan Li 1†, Zhijie Sang 2, Guan-Qun Zhou 1,
Jun-Yan Li3, Shu-Han Zhou 1, Pei-Wen Liu 1, Ting-Xi Tang 5, Min Tang 2, Zhitian Hou 2,
Jianmin Wu2,4, Jian Guan 5*, Li Lin 1*
--------------------------------------------------------------------------------

ARXIV ID: 2610.35835v1
TITLE: I-HITL: Inalienable Human-in-the-Loop
I-HITL: Inalienable Human-in-the-Loop
Samuel Breckenridge ∗
Cornell Tech, IC3
Dani Vilardell∗
Cornell Tech, IC3
Wenhao Wang
Yale University, IC3
Fan Zhang
Yale University, IC3
Ari Juels
Cornell Tech, IC3
Abstract—Human oversight is a pillar of AI safety. It is often
exercised by ahuman in the loop(H
--------------------------------------------------------------------------------

## Data Quality Findings

- Imported 500 most recent arXiv research papers, all in PDF format.
- All 500 PDFs opened successfully and contained extractable text on every page.
- Titles and author information were available for all papers.
- No duplicate filenames or paper titles were found.
- No missing values were found in the fields collected during the assessment.

# Part 2: Data Prep

In [9]:
# extra imports, output dir

import re
import json
import unicodedata
from dataclasses import dataclass
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger("ingestion_pipeline")

processed_dir = project_root / "data_processed"
processed_dir.mkdir(exist_ok=True)

print("Processed output directory:", processed_dir)

Processed output directory: /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed

In [10]:
# clean text

def clean_text(text: str) -> str:
    """Clean raw PDF-extracted text based on artifacts identified in the Part 1 assessment."""
    if not text or not text.strip():
        return ""

    text = unicodedata.normalize("NFKC", text)
    text = re.sub(r"-\s*\n\s*", "", text)              # rejoin hyphenated line breaks
    text = re.sub(r"(\w)-\s+(\w)", r"\1-\2", text)      # rejoin hyphenated stray spacing
    text = re.sub(r"\s[\*†‡]\s", " ", text)             # strip isolated footnote markers
    text = re.sub(r"\n+", " ", text)                    # collapse newlines
    text = re.sub(r"[ \t]+", " ", text)                 # collapse repeated whitespace

    return text.strip()


pages_df["cleaned_text"] = pages_df["raw_text"].apply(clean_text)
pages_df["char_count"] = pages_df["cleaned_text"].str.len()
pages_df["word_count"] = pages_df["cleaned_text"].str.split().str.len()

print("BEFORE:\n", pages_df.loc[0, "raw_text"][:300])
print("\nAFTER:\n", pages_df.loc[0, "cleaned_text"][:300])

BEFORE:
 Retriever-Free Retrieval: Navigating Documents with Decision Models
Chao Wan * 1 Paul J¨unger * 1 Beixi Du 1 Bodong Liu 1 Navaneetha Krishnan 2 Kilian Q. Weinberger1 2
Abstract
While language models have become dramatically
more capable, retrieval still largely relies on lex-
ical matching or simila

AFTER:
 Retriever-Free Retrieval: Navigating Documents with Decision Models Chao Wan 1 Paul J ̈unger 1 Beixi Du 1 Bodong Liu 1 Navaneetha Krishnan 2 Kilian Q. Weinberger1 2 Abstract While language models have become dramatically more capable, retrieval still largely relies on lexical matching or similarity

In [6]:
def clean_text(text: str) -> str:
    """Clean raw PDF-extracted text based on artifacts identified in the Part 1 assessment."""
    if not text or not text.strip():
        return ""

    text = unicodedata.normalize("NFKC", text)
    text = re.sub(r"-\s*\n\s*", "", text)
    text = re.sub(r"(\w)-\s+(\w)", r"\1-\2", text)
    text = re.sub(r"\s[\*†‡]\s", " ", text)
    text = re.sub(r"\n+", " ", text)
    text = re.sub(r"[ \t]+", " ", text)

    return text.strip()

In [11]:
# chunk text

CHUNK_SIZE_WORDS = 250
CHUNK_OVERLAP_WORDS = 40

def chunk_text(text: str, chunk_size: int = CHUNK_SIZE_WORDS, overlap: int = CHUNK_OVERLAP_WORDS) -> list[str]:
    words = text.split()
    if not words:
        return []
    if len(words) <= chunk_size:
        return [text]

    chunks = []
    start = 0
    while start < len(words):
        end = start + chunk_size
        chunks.append(" ".join(words[start:end]))
        start += chunk_size - overlap
    return chunks


chunk_records = []
for _, row in pages_df.iterrows():
    page_chunks = chunk_text(row["cleaned_text"])
    for chunk_index, chunk in enumerate(page_chunks):
        chunk_records.append({
            "chunk_id": f"{row['arxiv_id']}_p{row['page_number']}_c{chunk_index}",
            "arxiv_id": row["arxiv_id"],
            "title": row["title"],
            "author": row["author"],
            "published": row["published"],
            "page_number": row["page_number"],
            "chunk_index": chunk_index,
            "text": chunk,
            "word_count": len(chunk.split())
        })

chunks_df = pd.DataFrame(chunk_records)
print(f"Produced {len(chunks_df)} chunks from {pages_df['arxiv_id'].nunique()} papers")
chunks_df[["chunk_id", "page_number", "word_count"]].head(10)

Produced 35356 chunks from 500 papers

             chunk_id  page_number  word_count
0  2610.35868v1_p1_c0            1         250
1  2610.35868v1_p1_c1            1         250
2  2610.35868v1_p1_c2            1         210
3  2610.35868v1_p2_c0            2         250
4  2610.35868v1_p2_c1            2         250
5  2610.35868v1_p2_c2            2         250
6  2610.35868v1_p2_c3            2         144
7  2610.35868v1_p3_c0            3         250
8  2610.35868v1_p3_c1            3         250
9  2610.35868v1_p3_c2            3         250

In [12]:
# validate

assert not chunks_df.empty, "No chunks were produced"
assert chunks_df["chunk_id"].is_unique, "Duplicate chunk IDs found"
assert (chunks_df["word_count"] > 0).all(), "Empty chunks found"
assert chunks_df["title"].notna().all(), "Chunks missing title metadata"
assert chunks_df["arxiv_id"].notna().all(), "Chunks missing arxiv_id"
assert (chunks_df["word_count"] <= CHUNK_SIZE_WORDS + 5).all(), "Chunk exceeds target size unexpectedly"

print("All validation checks passed.")
print("\nChunk word-count distribution:")
print(chunks_df["word_count"].describe())

All validation checks passed.

Chunk word-count distribution:
count    35356.000000
mean       201.123883
std         75.099395
min          1.000000
25%        160.000000
50%        250.000000
75%        250.000000
max        250.000000
Name: word_count, dtype: float64

In [13]:
#save

jsonl_path = processed_dir / "chunks.jsonl"
parquet_path = processed_dir / "chunks.parquet"

with open(jsonl_path, "w") as f:
    for record in chunks_df.to_dict(orient="records"):
        f.write(json.dumps(record) + "\n")

chunks_df.to_parquet(parquet_path, index=False)

logger.info(f"Saved {len(chunks_df)} chunks to {jsonl_path}")
logger.info(f"Saved {len(chunks_df)} chunks to {parquet_path}")

2026-10-27 01:14:17,167 | INFO | Saved 35356 chunks to /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chunks.jsonl
2026-10-27 01:14:17,168 | INFO | Saved 35356 chunks to /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chunks.parquet

In [20]:
# wrap as a repeatable pipeline 

@dataclass
class IngestionConfig:
    query: str
    total_results: int
    output_dir: Path
    chunk_size_words: int = CHUNK_SIZE_WORDS
    chunk_overlap_words: int = CHUNK_OVERLAP_WORDS


class ArxivIngestionPipeline:
    def __init__(self, config: IngestionConfig):
        self.config = config
        self.pages_df = None
        self.chunks_df = None

    def extract(self):
        metadata = fetch_arxiv_metadata(self.config.query, self.config.total_results)
        records = []
        for i, paper in enumerate(metadata, start=1):
            if paper["pdf_url"] is None:
                continue
            try:
                records.extend(extract_pdf_pages_from_url(paper))
            except Exception as e:
                logger.warning(f"Failed to extract {paper['arxiv_id']}: {e}")
            if i % 25 == 0:
                logger.info(f"Processed {i}/{len(metadata)} papers")
            time.sleep(3)
        self.pages_df = pd.DataFrame(records)
        return self

    def clean(self):
        self.pages_df["cleaned_text"] = self.pages_df["raw_text"].apply(clean_text)
        return self

    def chunk(self):
        records = []
        for _, row in self.pages_df.iterrows():
            page_chunks = chunk_text(
                row["cleaned_text"],
                chunk_size=self.config.chunk_size_words,
                overlap=self.config.chunk_overlap_words
            )
            for chunk_index, chunk in enumerate(page_chunks):
                records.append({
                    "chunk_id": f"{row['arxiv_id']}_p{row['page_number']}_c{chunk_index}",
                    "arxiv_id": row["arxiv_id"],
                    "title": row["title"],
                    "author": row["author"],
                    "published": row["published"],
                    "page_number": row["page_number"],
                    "chunk_index": chunk_index,
                    "text": chunk,
                    "word_count": len(chunk.split())
                })
        self.chunks_df = pd.DataFrame(records)
        return self

    def validate(self):
        assert not self.chunks_df.empty, "No chunks produced"
        assert self.chunks_df["chunk_id"].is_unique, "Duplicate chunk IDs"
        assert (self.chunks_df["word_count"] > 0).all(), "Empty chunks found"
        assert self.chunks_df["title"].notna().all(), "Missing title metadata"
        return self

    def load(self):
        self.config.output_dir.mkdir(exist_ok=True)
        jsonl_path = self.config.output_dir / "chunks.jsonl"
        with open(jsonl_path, "w") as f:
            for record in self.chunks_df.to_dict(orient="records"):
                f.write(json.dumps(record) + "\n")
        self.chunks_df.to_parquet(self.config.output_dir / "chunks.parquet", index=False)
        logger.info(f"Saved {len(self.chunks_df)} chunks to {self.config.output_dir}")
        return self

    def run(self):
        return self.extract().clean().chunk().validate().load()

In [43]:
# only run this if you haven't already run the manual walkthrough above in this session, since running both fetches everything twice

config = IngestionConfig(query="cat:cs.AI", total_results=500, output_dir=processed_dir)
pipeline = ArxivIngestionPipeline(config)
pipeline.run()
print(f"Pipeline complete: {len(pipeline.chunks_df)} chunks ready for embedding")

fetched metadata for 100/500 papers
fetched metadata for 200/500 papers
fetched metadata for 300/500 papers
fetched metadata for 400/500 papers
fetched metadata for 500/500 papers

2026-10-19 10:22:58,474 | WARNING | Ignoring wrong pointing object 6 0 (offset 0)
2026-10-19 10:22:58,475 | WARNING | Ignoring wrong pointing object 8 0 (offset 0)
2026-10-19 10:22:58,475 | WARNING | Ignoring wrong pointing object 10 0 (offset 0)
2026-10-19 10:22:58,476 | WARNING | Ignoring wrong pointing object 12 0 (offset 0)
2026-10-19 10:22:58,477 | WARNING | Ignoring wrong pointing object 14 0 (offset 0)
2026-10-19 10:22:58,477 | WARNING | Ignoring wrong pointing object 16 0 (offset 0)
2026-10-19 10:22:58,477 | WARNING | Ignoring wrong pointing object 18 0 (offset 0)
2026-10-19 10:22:58,478 | WARNING | Ignoring wrong pointing object 28 0 (offset 0)
2026-10-19 10:22:58,478 | WARNING | Ignoring wrong pointing object 30 0 (offset 0)
2026-10-19 10:22:58,478 | WARNING | Ignoring wrong pointing object 32 0 (offset 0)
2026-10-19 10:22:58,478 | WARNING | Ignoring wrong pointing object 34 0 (offset 0)
2026-10-19 10:22:58,478 | WARNING | Ignoring wrong pointing object 36 0 (offset 0)
2026-10-19 10:22:58,478 | WARNING | Ignoring wrong pointing object 41 0 (offset 0)
2026-10-19 10:22:58,479 | WARNING | Ignoring wrong pointing object 46 0 (offset 0)
2026-10-19 10:22:58,479 | WARNING | Ignoring wrong pointing object 79 0 (offset 0)
2026-10-19 10:24:03,483 | INFO | Processed 25/500 papers
2026-10-19 10:24:10,040 | WARNING | Skipping broken line b'0d0e   0d2e   1d434': Odd-length string
2026-10-19 10:24:10,040 | WARNING | Skipping broken line b'0d2f   0d40   1d456': Odd-length string
2026-10-19 10:24:10,040 | WARNING | Skipping broken line b'0d41   0d42   1d538': Odd-length string
2026-10-19 10:24:10,041 | WARNING | Skipping broken line b'0d43   0d46   1d53b': Odd-length string
2026-10-19 10:24:10,041 | WARNING | Skipping broken line b'0d47   0d4b   1d540': Odd-length string
2026-10-19 10:24:10,041 | WARNING | Skipping broken line b'0d4d   0d53   1d54a': Odd-length string
2026-10-19 10:24:10,041 | WARNING | Skipping broken line b'0d54   0d6d   1d552': Odd-length string
2026-10-19 10:24:10,041 | WARNING | Skipping broken line b'0d6e   0d6f   1d6a4': Odd-length string
2026-10-19 10:24:10,041 | WARNING | Skipping broken line b'0d70   0d79   1d7d8': Odd-length string
2026-10-19 10:24:10,041 | WARNING | Got invalid hex string: Odd-length string (b'1d546')
2026-10-19 10:24:45,232 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-19 10:24:46,015 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-19 10:24:46,529 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-19 10:24:47,044 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-19 10:24:47,514 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-19 10:24:48,031 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-19 10:25:16,489 | WARNING | Ignoring wrong pointing object 6 0 (offset 0)
2026-10-19 10:25:16,491 | WARNING | Ignoring wrong pointing object 8 0 (offset 0)
2026-10-19 10:25:16,493 | WARNING | Ignoring wrong pointing object 10 0 (offset 0)
2026-10-19 10:25:16,494 | WARNING | Ignoring wrong pointing object 12 0 (offset 0)
2026-10-19 10:25:16,494 | WARNING | Ignoring wrong pointing object 14 0 (offset 0)
2026-10-19 10:25:16,495 | WARNING | Ignoring wrong pointing object 27 0 (offset 0)
2026-10-19 10:25:16,496 | WARNING | Ignoring wrong pointing object 29 0 (offset 0)
2026-10-19 10:25:16,496 | WARNING | Ignoring wrong pointing object 31 0 (offset 0)
2026-10-19 10:25:16,497 | WARNING | Ignoring wrong pointing object 33 0 (offset 0)
2026-10-19 10:25:16,497 | WARNING | Ignoring wrong pointing object 35 0 (offset 0)
2026-10-19 10:25:16,498 | WARNING | Ignoring wrong pointing object 37 0 (offset 0)
2026-10-19 10:25:16,498 | WARNING | Ignoring wrong pointing object 39 0 (offset 0)
2026-10-19 10:25:16,499 | WARNING | Ignoring wrong pointing object 41 0 (offset 0)
2026-10-19 10:25:16,499 | WARNING | Ignoring wrong pointing object 43 0 (offset 0)
2026-10-19 10:25:16,501 | WARNING | Ignoring wrong pointing object 51 0 (offset 0)
2026-10-19 10:25:16,502 | WARNING | Ignoring wrong pointing object 59 0 (offset 0)
2026-10-19 10:25:16,502 | WARNING | Ignoring wrong pointing object 61 0 (offset 0)
2026-10-19 10:25:16,503 | WARNING | Ignoring wrong pointing object 63 0 (offset 0)
2026-10-19 10:25:16,503 | WARNING | Ignoring wrong pointing object 94 0 (offset 0)
2026-10-19 10:25:16,503 | WARNING | Ignoring wrong pointing object 96 0 (offset 0)
2026-10-19 10:25:39,954 | INFO | Processed 50/500 papers
2026-10-19 10:25:53,504 | WARNING | Ignoring wrong pointing object 6 0 (offset 0)
2026-10-19 10:25:53,505 | WARNING | Ignoring wrong pointing object 8 0 (offset 0)
2026-10-19 10:25:53,505 | WARNING | Ignoring wrong pointing object 10 0 (offset 0)
2026-10-19 10:25:53,505 | WARNING | Ignoring wrong pointing object 12 0 (offset 0)
2026-10-19 10:25:53,506 | WARNING | Ignoring wrong pointing object 14 0 (offset 0)
2026-10-19 10:25:53,506 | WARNING | Ignoring wrong pointing object 21 0 (offset 0)
2026-10-19 10:25:53,506 | WARNING | Ignoring wrong pointing object 23 0 (offset 0)
2026-10-19 10:25:53,506 | WARNING | Ignoring wrong pointing object 25 0 (offset 0)
2026-10-19 10:25:53,507 | WARNING | Ignoring wrong pointing object 27 0 (offset 0)
2026-10-19 10:25:53,507 | WARNING | Ignoring wrong pointing object 34 0 (offset 0)
2026-10-19 10:25:53,508 | WARNING | Ignoring wrong pointing object 39 0 (offset 0)
2026-10-19 10:25:53,508 | WARNING | Ignoring wrong pointing object 46 0 (offset 0)
2026-10-19 10:25:53,508 | WARNING | Ignoring wrong pointing object 164 0 (offset 0)
2026-10-19 10:25:53,509 | WARNING | Ignoring wrong pointing object 166 0 (offset 0)
2026-10-19 10:25:53,509 | WARNING | Ignoring wrong pointing object 168 0 (offset 0)
2026-10-19 10:25:53,509 | WARNING | Ignoring wrong pointing object 175 0 (offset 0)
2026-10-19 10:25:53,509 | WARNING | Ignoring wrong pointing object 177 0 (offset 0)
2026-10-19 10:25:53,510 | WARNING | Ignoring wrong pointing object 179 0 (offset 0)
2026-10-19 10:25:53,510 | WARNING | Ignoring wrong pointing object 184 0 (offset 0)
2026-10-19 10:25:53,510 | WARNING | Ignoring wrong pointing object 186 0 (offset 0)
2026-10-19 10:25:53,510 | WARNING | Ignoring wrong pointing object 188 0 (offset 0)
2026-10-19 10:25:53,511 | WARNING | Ignoring wrong pointing object 191 0 (offset 0)
2026-10-19 10:25:53,511 | WARNING | Ignoring wrong pointing object 199 0 (offset 0)
2026-10-19 10:25:53,511 | WARNING | Ignoring wrong pointing object 207 0 (offset 0)
2026-10-19 10:25:53,512 | WARNING | Ignoring wrong pointing object 292 0 (offset 0)
2026-10-19 10:25:53,512 | WARNING | Ignoring wrong pointing object 293 0 (offset 0)
2026-10-19 10:25:53,512 | WARNING | Ignoring wrong pointing object 294 0 (offset 0)
2026-10-19 10:25:53,512 | WARNING | Ignoring wrong pointing object 295 0 (offset 0)
2026-10-19 10:25:53,513 | WARNING | Ignoring wrong pointing object 296 0 (offset 0)
2026-10-19 10:25:53,513 | WARNING | Ignoring wrong pointing object 297 0 (offset 0)
2026-10-19 10:25:53,514 | WARNING | Ignoring wrong pointing object 298 0 (offset 0)
2026-10-19 10:25:53,514 | WARNING | Ignoring wrong pointing object 299 0 (offset 0)
2026-10-19 10:25:53,514 | WARNING | Ignoring wrong pointing object 300 0 (offset 0)
2026-10-19 10:25:53,515 | WARNING | Ignoring wrong pointing object 301 0 (offset 0)
2026-10-19 10:25:53,515 | WARNING | Ignoring wrong pointing object 302 0 (offset 0)
2026-10-19 10:25:53,515 | WARNING | Ignoring wrong pointing object 303 0 (offset 0)
2026-10-19 10:25:53,516 | WARNING | Ignoring wrong pointing object 304 0 (offset 0)
2026-10-19 10:25:53,516 | WARNING | Ignoring wrong pointing object 305 0 (offset 0)
2026-10-19 10:25:53,516 | WARNING | Ignoring wrong pointing object 306 0 (offset 0)
2026-10-19 10:25:53,516 | WARNING | Ignoring wrong pointing object 307 0 (offset 0)
2026-10-19 10:25:53,517 | WARNING | Ignoring wrong pointing object 308 0 (offset 0)
2026-10-19 10:25:53,517 | WARNING | Ignoring wrong pointing object 309 0 (offset 0)
2026-10-19 10:25:53,517 | WARNING | Ignoring wrong pointing object 310 0 (offset 0)
2026-10-19 10:25:53,518 | WARNING | Ignoring wrong pointing object 311 0 (offset 0)
2026-10-19 10:25:53,518 | WARNING | Ignoring wrong pointing object 312 0 (offset 0)
2026-10-19 10:25:53,518 | WARNING | Ignoring wrong pointing object 313 0 (offset 0)
2026-10-19 10:25:53,518 | WARNING | Ignoring wrong pointing object 314 0 (offset 0)
2026-10-19 10:25:53,519 | WARNING | Ignoring wrong pointing object 315 0 (offset 0)
2026-10-19 10:25:53,519 | WARNING | Ignoring wrong pointing object 316 0 (offset 0)
2026-10-19 10:25:53,519 | WARNING | Ignoring wrong pointing object 317 0 (offset 0)
2026-10-19 10:25:53,519 | WARNING | Ignoring wrong pointing object 318 0 (offset 0)
2026-10-19 10:25:53,519 | WARNING | Ignoring wrong pointing object 319 0 (offset 0)
2026-10-19 10:25:53,520 | WARNING | Ignoring wrong pointing object 320 0 (offset 0)
2026-10-19 10:25:53,520 | WARNING | Ignoring wrong pointing object 321 0 (offset 0)
2026-10-19 10:25:53,520 | WARNING | Ignoring wrong pointing object 322 0 (offset 0)
2026-10-19 10:25:53,520 | WARNING | Ignoring wrong pointing object 323 0 (offset 0)
2026-10-19 10:25:53,521 | WARNING | Ignoring wrong pointing object 324 0 (offset 0)
2026-10-19 10:25:53,521 | WARNING | Ignoring wrong pointing object 325 0 (offset 0)
2026-10-19 10:25:53,521 | WARNING | Ignoring wrong pointing object 326 0 (offset 0)
2026-10-19 10:25:53,521 | WARNING | Ignoring wrong pointing object 327 0 (offset 0)
2026-10-19 10:25:53,522 | WARNING | Ignoring wrong pointing object 328 0 (offset 0)
2026-10-19 10:25:53,522 | WARNING | Ignoring wrong pointing object 329 0 (offset 0)
2026-10-19 10:25:53,522 | WARNING | Ignoring wrong pointing object 330 0 (offset 0)
2026-10-19 10:25:53,522 | WARNING | Ignoring wrong pointing object 331 0 (offset 0)
2026-10-19 10:25:53,522 | WARNING | Ignoring wrong pointing object 332 0 (offset 0)
2026-10-19 10:25:53,522 | WARNING | Ignoring wrong pointing object 333 0 (offset 0)
2026-10-19 10:26:37,228 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,230 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,231 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,231 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,231 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,231 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:37,234 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,236 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,236 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,236 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,237 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,237 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:37,441 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,443 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,443 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,444 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,444 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,444 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:37,447 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,449 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,450 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,450 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,450 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,450 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:37,584 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,586 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,586 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,586 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,587 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,587 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:37,589 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,591 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,592 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,592 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,592 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,592 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:37,817 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,819 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,820 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,820 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,820 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,820 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:37,823 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,825 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,825 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,825 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,826 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,826 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:38,029 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:38,031 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:38,031 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:38,031 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:38,032 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:38,032 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:38,035 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:38,037 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:38,037 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:38,037 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:38,038 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:38,038 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:38,138 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:38,140 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:38,140 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:38,140 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:38,141 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:38,141 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:38,144 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:38,146 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:38,146 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:38,146 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:38,146 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:38,147 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:38,242 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:38,244 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:38,244 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:38,244 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:38,244 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:38,245 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:38,248 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:38,249 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:38,250 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:38,250 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:38,250 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:38,250 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:39,092 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:39,094 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:39,094 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:39,094 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:39,095 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:39,095 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:39,098 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:39,101 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:39,101 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:39,101 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:39,102 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:39,102 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:39,105 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:39,107 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:39,107 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:39,107 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:39,107 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:39,107 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:39,110 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:39,112 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:39,112 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:39,112 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')

Pipeline complete: 35449 chunks ready for embedding

## Summary

- Extracted per-page text and metadata for all 500 papers.
- Cleaned hyphenation breaks, stray footnote symbols, and irregular whitespace found during Part 1.
- Chunked text at the page level (250 words, 40-word overlap) so every chunk keeps an accurate page number for citations.
- Validated that every chunk has complete metadata, a unique ID, and non-empty text.
- Packaged the flow into `ArxivIngestionPipeline` for repeatable reruns.
- Output: `data_processed/chunks.jsonl` and `chunks.parquet`, ready for embedding.

# Part 3: RAG Model Build

In [14]:
# install dependencies
# llamaindex is the core framework that wraps the other components (embeddings, vector stores, LLMs) together
# chromadb is a vector database for the embeddings

%pip install llama-index-core llama-index-embeddings-huggingface llama-index-vector-stores-chroma llama-index-llms-groq chromadb

import os
import chromadb

from llama_index.core import VectorStoreIndex, StorageContext, Settings
from llama_index.core.schema import TextNode
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.core.postprocessor import SentenceTransformerRerank
from llama_index.retrievers.bm25 import BM25Retriever
from llama_index.core.retrievers import QueryFusionRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.llms.groq import Groq

Requirement already satisfied: llama-index-core in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (0.14.25)
Requirement already satisfied: llama-index-embeddings-huggingface in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (0.8.0)
Requirement already satisfied: llama-index-vector-stores-chroma in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (0.6.0)
Requirement already satisfied: llama-index-llms-groq in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (0.6.1)
Requirement already satisfied: chromadb in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (1.5.9)
Requirement already satisfied: aiohttp<4,>=3.8.6 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (3.14.5)
Requirement already satisfied: aiosqlite in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (0.22.1)
Requirement already satisfied: banks<3,>=2.3.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (2.5.1)
Requirement already satisfied: dataclasses-json in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (1.3.1)
Requirement already satisfied: dirtyjson<2,>=1.0.8 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (1.0.8)
Requirement already satisfied: filetype<2,>=1.2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (1.2.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (2026.9.0)
Requirement already satisfied: httpx in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (0.28.1)
Requirement already satisfied: llama-index-workflows<3,>=2.14.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (2.26.1)
Requirement already satisfied: nest-asyncio<2,>=1.5.8 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (3.6.1)
Requirement already satisfied: nltk>=3.9.3 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (3.10.4)
Requirement already satisfied: numpy in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (2.4.6)
Requirement already satisfied: pillow>=9.0.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (13.0.0)
Requirement already satisfied: platformdirs in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (4.13.5)
Requirement already satisfied: pydantic>=2.8.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (2.14.1)
Requirement already satisfied: pyyaml>=6.0.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (6.0.3)
Requirement already satisfied: requests>=2.31.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (2.34.2)
Requirement already satisfied: setuptools>=80.9.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (84.2.1)
Requirement already satisfied: sqlalchemy[asyncio]>=1.4.49 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (2.1.6)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (9.2.1)
Requirement already satisfied: tiktoken>=0.7.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (0.14.0)
Requirement already satisfied: tinytag>=2.2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (2.3.2)
Requirement already satisfied: tqdm<5,>=4.66.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (4.70.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (4.16.0)
Requirement already satisfied: typing-inspect>=0.8.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (0.9.0)
Requirement already satisfied: wrapt in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-core) (2.5.1)
Requirement already satisfied: huggingface-hub[inference]>=0.19.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-embeddings-huggingface) (1.33.0)
Requirement already satisfied: sentence-transformers>=2.6.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-embeddings-huggingface) (6.1.0)
Requirement already satisfied: llama-index-llms-openai-like<0.9,>=0.8.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from llama-index-llms-groq) (0.8.1)
Requirement already satisfied: build>=1.0.3 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (1.6.1)
Requirement already satisfied: pydantic-settings>=2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (2.16.1)
Requirement already satisfied: pybase64>=1.4.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (1.5.1)
Requirement already satisfied: uvicorn[standard]>=0.18.3 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (0.54.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (1.31.1)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (1.45.1)
Requirement already satisfied: tokenizers>=0.13.2 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (0.23.3)
Requirement already satisfied: pypika>=0.48.9 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (0.51.1)
Requirement already satisfied: overrides>=7.3.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (1.85.0)
Requirement already satisfied: bcrypt>=4.0.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (0.27.3)
Requirement already satisfied: kubernetes>=28.1.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (37.0.1)
Requirement already satisfied: mmh3>=4.0.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (5.3.1)
Requirement already satisfied: orjson>=3.9.12 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (3.13.0)
Requirement already satisfied: rich>=10.11.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (15.0.0)
Requirement already satisfied: jsonschema>=4.19.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from chromadb) (4.26.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (1.8.0)
Requirement already satisfied: multidict<8.0,>=4.5 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (7.2.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.25.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (1.25.1)
Requirement already satisfied: griffe in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from banks<3,>=2.3.0->llama-index-core) (2.4.1)
Requirement already satisfied: jinja2 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from banks<3,>=2.3.0->llama-index-core) (3.1.6)
Requirement already satisfied: packaging>=24.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from build>=1.0.3->chromadb) (26.3)
Requirement already satisfied: pyproject_hooks in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from build>=1.0.3->chromadb) (1.3.3)
Requirement already satisfied: anyio in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from httpx->llama-index-core) (4.15.1)
Requirement already satisfied: certifi in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from httpx->llama-index-core) (2026.10.23)
Requirement already satisfied: httpcore==1.* in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from httpx->llama-index-core) (1.0.9)
Requirement already satisfied: idna in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from httpx->llama-index-core) (3.20)
Requirement already satisfied: h11>=0.16 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from httpcore==1.*->httpx->llama-index-core) (0.16.0)
WARNING: huggingface-hub 1.33.0 does not provide the extra 'inference'
Requirement already satisfied: click<9.0.0,>=8.4.2 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.2.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.7.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from jsonschema>=4.19.0->chromadb) (2026.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (3.0.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (1.9.2)
Requirement already satisfied: requests-oauthlib in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3<3.0.0,>=2.8.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (2.8.0)
Requirement already satisfied: durationpy>=0.11 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (0.11)

/Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
W1027 01:16:02.818000 78275 torch/distributed/elastic/multiprocessing/redirects.py:35] NOTE: Redirects are currently not supported in MacOs.

In [15]:
# load chunks

chunks_df = pd.read_parquet(processed_dir / "chunks.parquet")
print(f"loaded {len(chunks_df)} chunks from {processed_dir / 'chunks.parquet'}")

loaded 35356 chunks from /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chunks.parquet

In [16]:
# convert raw chunks into llamaindex textnodes, i.e. units with text and metadata

nodes = []
for _, row in chunks_df.iterrows():
    node = TextNode(
        text=row["text"],
        metadata={
            "arxiv_id": row["arxiv_id"],
            "title": row["title"],
            "author": row["author"],
            "page_number": row["page_number"],
        }
    )
    nodes.append(node)

print(f"built {len(nodes)} nodes")

built 35356 nodes

In [17]:
# config embedding model

Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

2026-10-27 01:17:06,927 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-10-27 01:17:06,929 | WARNING | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-10-27 01:17:06,957 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fmodules.json=&etag=%22952a9b81c0bfd99800fabf352f69c7ccd46c5e43%22 "HTTP/1.1 200 OK"
2026-10-27 01:17:06,985 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:17:07,011 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fconfig_sentence_transformers.json=&etag=%22dcb0c0d97d09b930d13600b1a773ddb27e441aab%22 "HTTP/1.1 200 OK"
2026-10-27 01:17:07,013 | INFO | Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-10-27 01:17:07,046 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:17:07,064 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fconfig_sentence_transformers.json=&etag=%22dcb0c0d97d09b930d13600b1a773ddb27e441aab%22 "HTTP/1.1 200 OK"
2026-10-27 01:17:07,092 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:17:07,119 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2FREADME.md=&etag=%228b8567d75ffa619486d9590cb0eb76d66ad46c49%22 "HTTP/1.1 200 OK"
2026-10-27 01:17:07,145 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:17:07,171 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fmodules.json=&etag=%22952a9b81c0bfd99800fabf352f69c7ccd46c5e43%22 "HTTP/1.1 200 OK"
2026-10-27 01:17:07,199 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:17:07,225 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fsentence_bert_config.json=&etag=%22ea85692bff64b0d1917833c31ddbca8ab10f5455%22 "HTTP/1.1 200 OK"
2026-10-27 01:17:07,254 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-10-27 01:17:07,294 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-10-27 01:17:07,341 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7758.85it/s]
2026-10-27 01:17:07,535 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-10-27 01:17:07,568 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-10-27 01:17:07,599 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-10-27 01:17:07,651 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:17:07,675 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2F1_Pooling%2Fconfig.json=&etag=%221da070f0993788c8851a652170ff013aa54dd519%22 "HTTP/1.1 200 OK"
2026-10-27 01:17:07,704 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/2_Normalize/config.json "HTTP/1.1 404 Not Found"
2026-10-27 01:17:07,743 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-10-27 01:17:08,253 | INFO | Loaded 1 prompt with these keys: ['query']

In [18]:
# config llm used to generate responses

from dotenv import load_dotenv
load_dotenv()  # load groq api key from .env file

Settings.llm = Groq(model="openai/gpt-oss-120b") # use openai/gpt-oss-120b model instead if hit rate limit, but could have lower answer quality

In [24]:
# ADDED: explicitly reload the Groq API key from the project .env file
# to fix the 401 authentication error caused by a stale or missing key.

from dotenv import load_dotenv
import os
from llama_index.llms.groq import Groq

load_dotenv(project_root / ".env", override=True)

groq_api_key = os.getenv("GROQ_API_KEY")

print("Groq key loaded:", bool(groq_api_key))

Settings.llm = Groq(
    model="openai/gpt-oss-120b",
    api_key=groq_api_key
)

Groq key loaded: True

In [19]:
# set up chroma for vectore store and build index

chroma_client = chromadb.PersistentClient(path=str(processed_dir / "chroma_db"))
chroma_collection = chroma_client.get_or_create_collection(name="arxiv_papers")

vectore_store = ChromaVectorStore(chroma_collection=chroma_collection)
storage_context = StorageContext.from_defaults(vector_store=vectore_store)

index = VectorStoreIndex(nodes, storage_context=storage_context)

print("index built and persisted to", processed_dir / "chroma_db")

index built and persisted to /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chroma_db

In [20]:
# hybrid retrieval: bm25 (keyword) + vector (semantic), fused via reciprocal rank fusion

bm25_retriever = BM25Retriever.from_defaults(nodes=nodes, similarity_top_k=30)
vector_retriever = index.as_retriever(similarity_top_k=30)

fusion_retriever = QueryFusionRetriever(
    [vector_retriever, bm25_retriever],
    similarity_top_k=30,
    num_queries=1,
    mode="reciprocal_rerank",
)

2026-10-27 01:24:31,333 | DEBUG | Building index from IDs objects

In [25]:
# build query engine (embed question, retrieve top similar chunks, feed them into llm, and generate response)

reranker = SentenceTransformerRerank(model="cross-encoder/ms-marco-MiniLM-L-6-v2", top_n=5) # build cross-encoder reranker
query_engine = index.as_query_engine(
    similarity_top_k=20,
    node_postprocessors=[reranker]
)

2026-10-27 01:28:21,470 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:28:21,496 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/modules.json "HTTP/1.1 404 Not Found"
2026-10-27 01:28:21,499 | INFO | No modules.json found for cross-encoder/ms-marco-MiniLM-L-6-v2, initializing a new CrossEncoder model.
2026-10-27 01:28:21,526 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L-6-v2 "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:28:21,559 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2 "HTTP/1.1 200 OK"
2026-10-27 01:28:21,592 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L-6-v2 "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:28:21,627 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2 "HTTP/1.1 200 OK"
2026-10-27 01:28:21,667 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/main/adapter_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:28:21,698 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-10-27 01:28:21,722 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L-6-v2 "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:28:21,756 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2 "HTTP/1.1 200 OK"
2026-10-27 01:28:21,782 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L-6-v2 "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:28:21,816 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2 "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 105/105 [00:00<00:00, 6471.45it/s]
2026-10-27 01:28:21,939 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L-6-v2 "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:28:21,969 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2 "HTTP/1.1 200 OK"
2026-10-27 01:28:22,007 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L-6-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:28:22,043 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-10-27 01:28:22,070 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L-6-v2/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-10-27 01:28:22,109 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"

In [26]:
# ask question (hardcoded for now)

response = query_engine.query("What are the most relevant recent research papers on reducing hallucinations in retrieval-augmented generation? Summarize the main approaches and identify where the evidence is strongest.")

print("RESPONSE:\n", response)

print("\nSOURCES:")
for node in response.source_nodes:
    meta = node.metadata
    print(f"- {meta['title']} (page {meta['page_number']}, score={node.score:.3f})")

Batches: 100%|██████████| 1/1 [00:00<00:00, 20.53it/s]
2026-10-27 01:28:31,737 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

RESPONSE:
 **Key recent papers that directly address hallucination mitigation in retrieval‑augmented generation**

| Paper (year) | Core Idea | How the paper evaluates the claim |
|--------------|-----------|-----------------------------------|
| **Shuster et al., “Retrieval augmentation reduces hallucination in conversation” (2021)** | Adds a retrieved knowledge base to the language model at generation time, forcing the model to ground each utterance in external evidence. | Experiments on conversational datasets show a measurable drop in factual errors compared with a baseline that generates without retrieval. |
| **Asai et al., “Self‑RAG: learning to retrieve, generate, and critique through self‑reflection” (2024)** | Introduces a three‑stage loop: (1) retrieve relevant passages, (2) generate a response, (3) let the model critique its own output and request new evidence if needed. The critique step is trained with a Socratic‑style prompting that encourages the model to question its own statements. | Benchmarks on several open‑domain QA and summarisation tasks report higher factuality scores and lower hallucination rates than standard RAG pipelines, with ablations confirming the benefit of the self‑critique stage. |
| **Cruz Blandón et al., “MEMERAG: a multilingual end‑to‑end meta‑evaluation benchmark for retrieval‑augmented generation” (2025)** | Provides a large, multilingual benchmark specifically designed to measure how well RAG systems stay faithful to retrieved sources. While not a mitigation method itself, the benchmark supplies the strongest empirical evidence for any proposed reduction technique. | The benchmark includes automatic and human‑annotated factuality metrics across many languages; several recent RAG models are evaluated on it, establishing a clear performance hierarchy. |
| **Huang et al., “A survey on hallucination in large language models” (2025)** | Synthesises the field and highlights the most promising mitigation strategies, including retrieval augmentation, self‑verification, and reinforcement‑learning‑based reward shaping. | The survey aggregates results from dozens of papers, pointing out that the most consistently reproduced gains come from retrieval‑grounded generation combined with post‑hoc verification. |

**Main methodological trends**

1. **Grounding via retrieval** – By conditioning generation on passages fetched from an external corpus, the model is forced to copy or paraphrase verifiable facts. The 2021 study provides the earliest quantitative proof that this alone cuts hallucinations in dialogue.

2. **Self‑critique / iterative refinement** – The 2024 Self‑RAG framework adds a feedback loop where the model evaluates its own output, asks for additional evidence, and revises the response. This Socratic‑style guidance yields higher factuality than a single‑pass RAG system.

3. **Reward‑driven fine‑tuning** – Although not a detection paper, outcome‑based reinforcement‑learning approaches (e.g., RL with verifiable rewards) are mentioned as complementary ways to align the model toward factual generation. Their impact is usually demonstrated on case‑level hallucination benchmarks rather than span‑level, so the evidence is less granular.

4. **Comprehensive evaluation** – The MEMERAG benchmark supplies the most rigorous, multilingual testbed for measuring hallucination reduction, making it the reference point for comparing any new grounding or self‑verification technique.

**Where the evidence is strongest**

- **Empirical reductions in conversation**: The 2021 retrieval‑augmentation study reports statistically significant drops in hallucination rates on standard conversational corpora, establishing a clear causal link between retrieved context and factuality.

- **Iterative self‑reflection gains**: The 2024 Self‑RAG paper demonstrates consistent improvements across multiple downstream tasks (QA, summarisation, dialogue) and includes ablation studies that isolate the critique component as the primary driver of the gains.

- **Benchmark‑level validation**: MEMERAG (2025) offers the most extensive, multilingual evidence base. Models that incorporate both retrieval grounding and self‑critique consistently rank at the top of its leaderboard, suggesting that the combination of these approaches yields the most robust reduction in hallucinations.

In summary, the most compelling recent work points to a two‑pronged strategy: first, anchor generation in retrieved evidence; second, let the model actively verify and refine its output through a self‑critique loop. The strongest empirical support comes from the 2021 retrieval‑augmentation experiments, the 2024 Self‑RAG iterative framework, and the 2025 MEMERAG benchmark that validates these methods across languages and tasks.

SOURCES:
- SOPO: Socratic Guided Policy Optimization for Span-Level Hallucination Detection (page 1, score=1.180)
- SOPO: Socratic Guided Policy Optimization for Span-Level Hallucination Detection (page 1, score=1.180)
- Trust Mechanisms for Offline Generative AI at the Edge: A Connectivity-Regime Framework and an Empirical Study on a Raspberry Pi 5 (page 21, score=0.644)
- Trust Mechanisms for Offline Generative AI at the Edge: A Connectivity-Regime Framework and an Empirical Study on a Raspberry Pi 5 (page 21, score=0.644)
- Mycelium: A Meta-Study of Hallucination Detection Across Provenance, Typology, and Granularities (page 1, score=-0.136)

## Part 3B: End-to-End Retrieval + Summarization Workflow

This section tests the complete retrieval and summarization workflow across the expanded arXiv dataset. The workflow accepts a natural-language research question, retrieves and reranks relevant research chunks, generates a summarized response with the configured LLM, and returns source metadata for review.

In [27]:
#reusable end-to-end retrieval + summarization function
# Takes a research question, runs it through the existing RAG query engine,
# and returns both the generated answer and source metadata.

def run_research_query(question, top_k=5):
    """
    Run a research question through the complete RAG pipeline
    and return the generated response with retrieved source metadata.
    """

    response = query_engine.query(question)

    sources = []

    for node in response.source_nodes[:top_k]:
        sources.append({
            "title": node.metadata.get("title"),
            "arxiv_id": node.metadata.get("arxiv_id"),
            "page_number": node.metadata.get("page_number"),
            "score": node.score
        })

    return {
        "question": question,
        "answer": str(response),
        "sources": sources
    }

In [28]:
#  test the end-to-end workflow using research questions
# covering several AI topics in the expanded arXiv dataset.

test_questions = [
    "What recent methods are being used to reduce hallucinations in retrieval-augmented generation?",
    "What approaches are recent AI research papers using to improve AI agent reliability?",
    "What techniques are being explored to make large language models more efficient?",
    "What recent research focuses on improving the safety or trustworthiness of generative AI?",
    "How are researchers improving retrieval and reasoning in AI systems?"
]

In [30]:
# Run each research question through the complete workflow.

test_results = []

for question in test_questions:
    result = run_research_query(question)
    test_results.append(result)

    print("=" * 80)
    print("QUESTION:")
    print(result["question"])

    print("\nANSWER:")
    print(result["answer"])

    print("\nSOURCES:")
    for source in result["sources"]:
        print(
            f"- {source['title']} "
            f"(arXiv: {source['arxiv_id']}, "
            f"page {source['page_number']}, "
            f"score={source['score']:.3f})"
        )

    print()

Batches: 100%|██████████| 1/1 [00:00<00:00,  5.85it/s]
2026-10-27 01:30:35,231 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

================================================================================
QUESTION:
What recent methods are being used to reduce hallucinations in retrieval-augmented generation?

ANSWER:
Recent work has explored several complementary approaches to curb hallucinations when models rely on external knowledge:

* **Retrieval‑augmented generation itself** – By grounding the model’s output in retrieved passages, the likelihood of fabricating facts drops markedly. Empirical studies have shown that simply adding a retrieval step can substantially lower hallucination rates in conversational settings.

* **Self‑reflexive retrieval‑generation loops** – Techniques that let the model iteratively retrieve, generate, and then critique its own output (often called “self‑RAG” or self‑reflection) encourage the system to verify statements against the source material before finalizing them.

* **Outcome‑oriented reinforcement learning** – Reward‑driven fine‑tuning methods such as Reinforcement Learning with Verifiable Rewards (RLVR) shape the policy toward fact‑consistent behavior by assigning higher rewards to outputs that can be verified against the retrieved context.

* **Policy‑optimization for span‑level detection** – Approaches like Class‑Aware Policy Optimization (CAPO) and Socratic Guided Policy Optimization (SOPO) train the model to explicitly identify and avoid hallucinated spans, effectively steering generation away from ungrounded content.

* **Guided‑RL and iterative‑refinement paradigms** – These frameworks interleave reasoning steps with corrective feedback, helping the model to refine its answer and eliminate inconsistencies before it is emitted.

Together, these methods—grounding via retrieval, self‑critique loops, reward‑based RL, and fine‑grained policy optimization—represent the current frontier in reducing hallucinations in retrieval‑augmented generation systems.

SOURCES:
- SOPO: Socratic Guided Policy Optimization for Span-Level Hallucination Detection (arXiv: 2610.32212v1, page 1, score=3.379)
- SOPO: Socratic Guided Policy Optimization for Span-Level Hallucination Detection (arXiv: 2610.32212v1, page 1, score=3.379)
- Trust Mechanisms for Offline Generative AI at the Edge: A Connectivity-Regime Framework and an Empirical Study on a Raspberry Pi 5 (arXiv: 2610.33732v1, page 21, score=2.173)
- Trust Mechanisms for Offline Generative AI at the Edge: A Connectivity-Regime Framework and an Empirical Study on a Raspberry Pi 5 (arXiv: 2610.33732v1, page 21, score=2.173)
- Mycelium: A Meta-Study of Hallucination Detection Across Provenance, Typology, and Granularities (arXiv: 2610.33608v1, page 11, score=1.179)

Batches: 100%|██████████| 1/1 [00:00<00:00, 46.66it/s]
2026-10-27 01:30:37,163 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

================================================================================
QUESTION:
What approaches are recent AI research papers using to improve AI agent reliability?

ANSWER:
Recent work is tackling agent reliability by treating the surrounding “harness” – the software and procedural infrastructure that drives an LLM‑based agent – as a first‑class object of evaluation and improvement.  The main strategies include:

* **Component‑wise reliability modeling** – breaking harness reliability into a set of well‑defined dimensions (e.g., context handling, execution control, governance policies, lifecycle management, observability, tool integration, and verification) and measuring each one separately.

* **Mechanism‑oriented benchmark suites** – building large collections of expert‑level tasks that have executable or state‑based ground truth, allowing the same model‑task pair to be run across different harnesses while keeping each harness’s native interfaces intact.

* **Execution‑trace capture** – instrumenting agents with a trajectory‑tracing module that records every step of the run and converts it into a unified trace representation.  This preserves provenance while enabling cross‑harness comparison.

* **Multi‑source evidence aggregation** – gathering evidence from the agent’s internal context, the harness’s logs, and the external execution environment, then synthesizing it into criterion‑specific proof that a particular reliability component was satisfied or violated.

* **Two‑layer evaluation framework** – first assessing whether the agent achieved the task goal, then independently scoring the harness on its reliability criteria, so that successful task outcomes can be distinguished from underlying harness failures.

* **Failure attribution via explicit mechanism chains** – defining causal chains that link a failed reliability criterion to concrete harness or model actions, and then reviewing the collected evidence to separate mere candidates from validated failure propagation.

* **Cross‑harness adapters and native‑behavior preservation** – providing thin adapters that map a common task definition onto each harness’s native API, ensuring that comparisons reflect real‑world behavior rather than artificial homogenization.

* **Auditable, reproducible pipelines** – publishing the full set of tasks, configurations, execution traces, and verdicts so that other researchers can replicate the experiments, diagnose failures, and iterate on harness design.

Together, these approaches shift the focus from only measuring model capability to systematically measuring, diagnosing, and improving the reliability of the entire agent system.

SOURCES:
- Trial by Trace: Benchmarking AI Agent Harnesses for Reliability and Failure Attribution (arXiv: 2610.32285v1, page 1, score=0.684)
- Trial by Trace: Benchmarking AI Agent Harnesses for Reliability and Failure Attribution (arXiv: 2610.32285v1, page 1, score=0.684)
- Trial by Trace: Benchmarking AI Agent Harnesses for Reliability and Failure Attribution (arXiv: 2610.32285v1, page 2, score=0.107)
- Trial by Trace: Benchmarking AI Agent Harnesses for Reliability and Failure Attribution (arXiv: 2610.32285v1, page 2, score=0.107)
- Trial by Trace: Benchmarking AI Agent Harnesses for Reliability and Failure Attribution (arXiv: 2610.32285v1, page 2, score=-0.498)

Batches: 100%|██████████| 1/1 [00:00<00:00, 49.54it/s]
2026-10-27 01:30:37,448 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-27 01:30:37,450 | INFO | Retrying request to /chat/completions in 10.000000 seconds
2026-10-27 01:30:47,626 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-27 01:30:47,629 | INFO | Retrying request to /chat/completions in 2.000000 seconds
2026-10-27 01:30:51,572 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

================================================================================
QUESTION:
What techniques are being explored to make large language models more efficient?

ANSWER:
Researchers are pursuing a variety of compression and architectural tricks to reduce the compute, memory, and storage demands of large language models.  Common approaches include:

* **Pruning** – removing weights or entire structures, often with structured or one‑shot methods (e.g., SparseGPT, LLM‑Pruner, simple effective pruning pipelines).
* **Quantization** – lowering the numeric precision of parameters, using post‑training quantization, data‑free quantization‑aware training, or dense‑and‑sparse schemes such as SqueezeLLM.
* **Distillation** – training a smaller “student” model from a larger teacher, including on‑policy or step‑by‑step distillation that learns from self‑generated mistakes.
* **Parameter‑efficient fine‑tuning** – techniques like LoRA and its long‑context variant LongLoRA that adapt only a tiny subset of weights, saving memory during post‑training adaptation.
* **Efficient attention mechanisms** – redesigns such as attention sinks or streaming attention that cut the quadratic cost of standard self‑attention, enabling handling of very long sequences.
* **Long‑context architectures** – models like LongNet that scale transformers to billions of tokens, often paired with specialized fine‑tuning tricks.
* **Model editing and task arithmetic** – methods that modify weights directly to inject or remove knowledge without full retraining, reducing the need for additional compute.

Together, these strategies aim to keep model performance while dramatically lowering the resources required for training, inference, and adaptation.

SOURCES:
- Large Language Models: A Plain-Language Overview for Engineers (arXiv: 2610.34585v1, page 2, score=2.038)
- A Comprehensive Framework for All Stages of Large-Model Training: From Data and Tokenization, through Pretraining, to Post-Training Alignment (arXiv: 2610.33451v1, page 137, score=1.560)
- A Comprehensive Framework for All Stages of Large-Model Training: From Data and Tokenization, through Pretraining, to Post-Training Alignment (arXiv: 2610.33451v1, page 137, score=1.560)
- A Comprehensive Framework for All Stages of Large-Model Training: From Data and Tokenization, through Pretraining, to Post-Training Alignment (arXiv: 2610.33451v1, page 137, score=1.365)
- A Comprehensive Framework for All Stages of Large-Model Training: From Data and Tokenization, through Pretraining, to Post-Training Alignment (arXiv: 2610.33451v1, page 137, score=1.365)

Batches: 100%|██████████| 1/1 [00:00<00:00, 21.12it/s]
2026-10-27 01:30:52,349 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-27 01:30:52,349 | INFO | Retrying request to /chat/completions in 13.000000 seconds
2026-10-27 01:31:06,564 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

================================================================================
QUESTION:
What recent research focuses on improving the safety or trustworthiness of generative AI?

ANSWER:
Recent work has explored several approaches to make generative AI safer and more trustworthy. One line of research proposes a “connectivity‑regime” framework that defines trust mechanisms for offline generative models running on edge devices, and validates the approach with an empirical study on a Raspberry Pi 5. Another recent effort surveys the emerging field of trustworthy recursive self‑improvement for large models, mapping risks, safeguards, and evaluation methods across the improvement loop. In addition, a number of surveys have synthesized trustworthiness requirements from standards such as NIST and the EU’s AI guidelines, outlining dimensions like validity, reliability, robustness, truthfulness, safety, fairness, privacy, transparency, and accountability, and linking them to concrete assessment techniques for generative systems.

SOURCES:
- Trust Mechanisms for Offline Generative AI at the Edge: A Connectivity-Regime Framework and an Empirical Study on a Raspberry Pi 5 (arXiv: 2610.33732v1, page 3, score=1.117)
- Trust Mechanisms for Offline Generative AI at the Edge: A Connectivity-Regime Framework and an Empirical Study on a Raspberry Pi 5 (arXiv: 2610.33732v1, page 3, score=1.117)
- Trust Mechanisms for Offline Generative AI at the Edge: A Connectivity-Regime Framework and an Empirical Study on a Raspberry Pi 5 (arXiv: 2610.33732v1, page 11, score=0.982)
- Trustworthy Recursive Self-Improvement in the Era of Large Models: Foundation, Risks, Evaluation and Open Challenges (arXiv: 2610.35193v1, page 6, score=0.535)
- Trustworthy Recursive Self-Improvement in the Era of Large Models: Foundation, Risks, Evaluation and Open Challenges (arXiv: 2610.35193v1, page 13, score=0.449)

Batches: 100%|██████████| 1/1 [00:00<00:00, 17.23it/s]
2026-10-27 01:31:07,420 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-27 01:31:07,420 | INFO | Retrying request to /chat/completions in 20.000000 seconds
2026-10-27 01:31:29,852 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

================================================================================
QUESTION:
How are researchers improving retrieval and reasoning in AI systems?

ANSWER:
Researchers are enhancing AI systems’ ability to retrieve relevant information and reason over it through several complementary approaches:

1. **Retrieval‑augmented generation** – Models are equipped with external search modules that fetch evidence from large corpora before generating answers, allowing them to rely on up‑to‑date facts rather than only on stored parameters.

2. **Self‑assessment reinforcement learning (SARL)** – Agents are trained to monitor their own “search state,” detecting when the retrieved evidence is insufficient and issuing additional queries or corrections. A dual‑reward signal (assessment reward + assessment penalty) encourages thorough searching early on and reduces over‑reliance on post‑hoc self‑checks.

3. **Incentivized search via RL** – Frameworks such as R1‑searcher, R1searcher++, and RAG‑R1 reward LLMs for issuing effective queries, refining results, and integrating multiple parallel searches, thereby strengthening the link between searching and reasoning.

4. **Dynamic knowledge acquisition** – Techniques like multi‑hop and deep‑research benchmarks push models to chain together several retrieval steps, filling information gaps progressively.

5. **Adaptive context construction** – Training‑free semantic‑tree methods and context‑folding strategies reorganize retrieved passages into hierarchical or compressed representations, enabling efficient reasoning over long contexts without exceeding model limits.

6. **Scaling compute at inference** – Optimizing test‑time compute (e.g., allocating more resources to search or reasoning phases) can yield better performance than merely enlarging model parameters.

Together, these methods make AI systems more reliable, less prone to fabricating unsupported answers, and better suited for applications such as research assistance, education, healthcare information, and decision support.

SOURCES:
- Self-Assessment Reinforcement Learning for Search-State Awareness in Retrieval-Augmented Large Language Models (arXiv: 2610.30435v1, page 22, score=0.401)
- Self-Assessment Reinforcement Learning for Search-State Awareness in Retrieval-Augmented Large Language Models (arXiv: 2610.30435v1, page 11, score=0.171)
- Rethinking Retrieval in the Long-Context Era: Training-Free Semantic Trees for Adaptive Context Construction (arXiv: 2610.34146v1, page 10, score=-0.806)
- Self-Assessment Reinforcement Learning for Search-State Awareness in Retrieval-Augmented Large Language Models (arXiv: 2610.30435v1, page 2, score=-3.182)
- Self-Assessment Reinforcement Learning for Search-State Awareness in Retrieval-Augmented Large Language Models (arXiv: 2610.30435v1, page 4, score=-3.512)

In [31]:
# basic initial evaluation of the end-to-end workflow.
# This checks whether each query generated an answer and returned sources.

initial_evaluation = pd.DataFrame([
    {
        "question": result["question"],
        "answer_generated": bool(result["answer"].strip()),
        "sources_returned": len(result["sources"]),
        "top_source": result["sources"][0]["title"] if result["sources"] else None
    }
    for result in test_results
])

initial_evaluation

,question,answer_generated,sources_returned,top_source
0,What recent methods are being used to reduce h...,True,5,SOPO: Socratic Guided Policy Optimization for ...
1,What approaches are recent AI research papers ...,True,5,Trial by Trace: Benchmarking AI Agent Harnesse...
2,What techniques are being explored to make lar...,True,5,Large Language Models: A Plain-Language Overvi...
3,What recent research focuses on improving the ...,True,5,Trust Mechanisms for Offline Generative AI at ...
4,How are researchers improving retrieval and re...,True,5,Self-Assessment Reinforcement Learning for Sea...

In [32]:
# Manual review of retrieval relevance and summary usefulness.
# "Partial" is used where the retrieved evidence is related to the topic
# but not as directly relevant as the other test cases.

manual_review = pd.DataFrame([
    {
        "question": test_results[0]["question"],
        "retrieval_relevant": "Yes",
        "summary_useful": "Yes",
        "notes": "Retrieved papers were directly related to hallucination reduction and detection."
    },
    {
        "question": test_results[1]["question"],
        "retrieval_relevant": "Yes",
        "summary_useful": "Yes",
        "notes": "Retrieved research was aligned with AI agent reliability and governance."
    },
    {
        "question": test_results[2]["question"],
        "retrieval_relevant": "Yes",
        "summary_useful": "Yes",
        "notes": "Retrieved papers included relevant work on AI model efficiency and optimization."
    },
    {
        "question": test_results[3]["question"],
        "retrieval_relevant": "Yes",
        "summary_useful": "Yes",
        "notes": "Retrieved research focused on AI safety, trust, and governance."
    },
    {
        "question": test_results[4]["question"],
        "retrieval_relevant": "Partial",
        "summary_useful": "Yes",
        "notes": "The broader retrieval and reasoning question returned some useful sources, but several were less directly related."
    }
])

manual_review

,question,retrieval_relevant,summary_useful,notes
0,What recent methods are being used to reduce h...,Yes,Yes,Retrieved papers were directly related to hall...
1,What approaches are recent AI research papers ...,Yes,Yes,Retrieved research was aligned with AI agent r...
2,What techniques are being explored to make lar...,Yes,Yes,Retrieved papers included relevant work on AI ...
3,What recent research focuses on improving the ...,Yes,Yes,"Retrieved research focused on AI safety, trust..."
4,How are researchers improving retrieval and re...,Partial,Yes,The broader retrieval and reasoning question r...

### Initial Findings

The workflow was able to answer all five test questions and return five sources for each one. Most of the results matched the questions pretty well, especially for hallucinations, AI agent reliability, model efficiency, and AI safety.

The retrieval and reasoning question was a little weaker because some of the lower-ranked sources were not as closely related to the question. The answer was still useful, but this showed that broader questions may need some more retrieval tuning.

During testing, I also had to reload the Groq API key directly from the project .env file after running into an authentication error. After fixing that, the query workflow worked normally. I also ran into a few temporary Groq rate-limit errors while testing multiple questions in a row, but the requests automatically retried and eventually completed.

Overall, the workflow is working from retrieval through summarization and source reporting. The main things to improve are handling broader questions more precisely and dealing with API rate limits during larger batches of testing.

# Part 4 - Baseline RAG Evaluation

In [29]:
# test the end-to-end workflow using research questions
# covering several AI topics in the expanded arXiv dataset.

test_questions = [
    "What recent methods are being used to reduce hallucinations in retrieval-augmented generation?",
    "What approaches are recent AI research papers using to improve AI agent reliability?",
    "What techniques are being explored to make large language models more efficient?",
    "What recent research focuses on improving the safety or trustworthiness of generative AI?",
    "How are researchers improving retrieval and reasoning in AI systems?"
]

In [26]:
# Part 4: Baseline RAG Evaluation

import chromadb
import pandas as pd

from llama_index.core import VectorStoreIndex, StorageContext
from llama_index.vector_stores.chroma import ChromaVectorStore

In [27]:
# Create benchmark questions

benchmark_questions = [
    {
        "id": "Q1",
        "question": "What problem does Pandora's AI Model Routing Box aim to solve?",
        "expected_arxiv_id": "2608.20316v1"
    },
    {
        "id": "Q2",
        "question": "How does Pandora's AI Model Routing Box improve the efficiency of AI model selection?",
        "expected_arxiv_id": "2608.20316v1"
    },
    {
        "id": "Q3",
        "question": "What is AI4AI-Bench designed to evaluate?",
        "expected_arxiv_id": "2608.20318v1"
    },
    {
        "id": "Q4",
        "question": "How does AI4AI-Bench assess the performance of LLM agents in algorithmic design?",
        "expected_arxiv_id": "2608.20318v1"
    },
    {
        "id": "Q5",
        "question": "What information is used to induce task models from computer-use traces?",
        "expected_arxiv_id": "2608.20319v1"
    },
    {
        "id": "Q6",
        "question": "What is the purpose of the agentic approach for active data collection and travel behaviour modelling?",
        "expected_arxiv_id": "2608.20320v1"
    },
    {
        "id": "Q7",
        "question": "What problem does grounded checklist-aligned reward learning address in patient-oriented medical research?",
        "expected_arxiv_id": "2608.20331v1"
    },
    {
        "id": "Q8",
        "question": "How is reward learning used to improve patient-oriented medical outcomes?",
        "expected_arxiv_id": "2608.20331v1"
    }
]

benchmark_df = pd.DataFrame(benchmark_questions)

benchmark_df

   id                                           question expected_arxiv_id
0  Q1  What problem does Pandora's AI Model Routing B...      2608.20316v1
1  Q2  How does Pandora's AI Model Routing Box improv...      2608.20316v1
2  Q3          What is AI4AI-Bench designed to evaluate?      2608.20318v1
3  Q4  How does AI4AI-Bench assess the performance of...      2608.20318v1
4  Q5  What information is used to induce task models...      2608.20319v1
5  Q6  What is the purpose of the agentic approach fo...      2608.20320v1
6  Q7  What problem does grounded checklist-aligned r...      2608.20331v1
7  Q8  How is reward learning used to improve patient...      2608.20331v1

In [28]:
# Create Chroma vector store

chroma_client = chromadb.PersistentClient(
    path=str(processed_dir / "chroma_db")
)

chroma_collection = chroma_client.get_or_create_collection(
    name="baseline_rag"
)

vector_store = ChromaVectorStore(
    chroma_collection=chroma_collection
)

storage_context = StorageContext.from_defaults(
    vector_store=vector_store
)

In [29]:
# Create the baseline vector index

index = VectorStoreIndex(
    nodes,
    storage_context=storage_context,
    show_progress=True
)

retriever = index.as_retriever(
    similarity_top_k=5
)

Generating embeddings: 100%|██████████| 300/300 [00:45<00:00,  6.63it/s]

In [30]:
# Test baseline retrieval

test_question = benchmark_questions[0]["question"]

results = retriever.retrieve(test_question)

for rank, result in enumerate(results, start=1):
    print(f"Rank {rank}")
    print(f"arXiv ID: {result.node.metadata.get('arxiv_id')}")
    print(f"Title: {result.node.metadata.get('title')}")
    print(f"Page: {result.node.metadata.get('page_number')}")
    print()

Rank 1
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 26

Rank 2
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 26

Rank 3
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 26

Rank 4
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 18

Rank 5
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 18

In [31]:
# Evaluate baseline retrieval

retrieval_results = []

for item in benchmark_questions:

    results = retriever.retrieve(item["question"])

    retrieved_ids = [
        result.node.metadata.get("arxiv_id")
        for result in results
    ]

    expected_id = item["expected_arxiv_id"]

    retrieval_results.append({
        "id": item["id"],
        "question": item["question"],
        "expected_arxiv_id": expected_id,
        "retrieved_ids": retrieved_ids,
        "hit_at_1": expected_id in retrieved_ids[:1],
        "hit_at_3": expected_id in retrieved_ids[:3],
        "hit_at_5": expected_id in retrieved_ids[:5]
    })

evaluation_df = pd.DataFrame(retrieval_results)

evaluation_df

,id,question,expected_arxiv_id,retrieved_ids,hit_at_1,hit_at_3,hit_at_5
0,Q1,What problem does Pandora's AI Model Routing B...,2608.20316v1,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260...",True,True,True
1,Q2,How does Pandora's AI Model Routing Box improv...,2608.20316v1,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260...",True,True,True
2,Q3,What is AI4AI-Bench designed to evaluate?,2608.20318v1,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260...",True,True,True
3,Q4,How does AI4AI-Bench assess the performance of...,2608.20318v1,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260...",True,True,True
4,Q5,What information is used to induce task models...,2608.20319v1,"[2608.20319v1, 2608.20319v1, 2608.20319v1, 260...",True,True,True
5,Q6,What is the purpose of the agentic approach fo...,2608.20320v1,"[2608.20320v1, 2608.20320v1, 2608.20320v1, 260...",True,True,True
6,Q7,What problem does grounded checklist-aligned r...,2608.20331v1,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260...",True,True,True
7,Q8,How is reward learning used to improve patient...,2608.20331v1,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260...",True,True,True

In [32]:
# Calculate retrieval metrics

hit_at_1 = evaluation_df["hit_at_1"].mean()
hit_at_3 = evaluation_df["hit_at_3"].mean()
hit_at_5 = evaluation_df["hit_at_5"].mean()

print("Baseline Retrieval Performance")
print("-" * 40)
print(f"Hit@1: {hit_at_1:.2%}")
print(f"Hit@3: {hit_at_3:.2%}")
print(f"Hit@5: {hit_at_5:.2%}")

Baseline Retrieval Performance
----------------------------------------
Hit@1: 100.00%
Hit@3: 100.00%
Hit@5: 100.00%

In [33]:
# Save baseline retrieval results

evaluation_df.to_csv(
    processed_dir / "baseline_retrieval_evaluation.csv",
    index=False
)

Okay, so far 100% Hit for 1,3, and 5 indicates that it was able to retrieve a chunk from the expected paper. However, we do not know if the RAG system generates correct answers.

Will be using Groq generation and evalluate the answers below.

In [34]:
# Set up Groq

import os
from dotenv import load_dotenv

from llama_index.core import Settings
from llama_index.llms.groq import Groq

load_dotenv()

groq_api_key = os.getenv("GROQ_API_KEY")

llm = Groq(
    model="openai/gpt-oss-20b",
    api_key=groq_api_key
)

Settings.llm = llm

In [35]:
# Test Groq with one question

question = benchmark_questions[0]["question"]

results = retriever.retrieve(question)

context = "\n\n".join([
    f"""
Source:
Title: {result.node.metadata.get('title')}
arXiv ID: {result.node.metadata.get('arxiv_id')}
Page: {result.node.metadata.get('page_number')}

Text:
{result.node.text}
"""
    for result in results
])

prompt = f"""
You are a research intelligence assistant.

Answer the question using only the research context provided below.

Question:
{question}

Research context:
{context}

Instructions:
- Give a concise and factual answer.
- Do not use information outside the provided context.
- If the context does not contain enough information, say so.
- At the end of your answer, provide the source arXiv ID.
"""

response = llm.complete(prompt)

print(response.text)

2026-10-06 15:35:47,022 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Pandora’s AI Model Routing Box is designed to address the problem of efficiently allocating AI models to incoming tasks while taking into account the cost of estimating each model’s value. It seeks to minimize regret and inspection cost by routing queries to the most appropriate model under a budget‑constrained value‑estimation setting.

Source: arXiv 2608.20316v1

In [36]:
# Generate a RAG answer

def generate_rag_answer(question):

    results = retriever.retrieve(question)

    context = "\n\n".join([
        f"""
Source:
Title: {result.node.metadata.get('title')}
arXiv ID: {result.node.metadata.get('arxiv_id')}
Page: {result.node.metadata.get('page_number')}

Text:
{result.node.text}
"""
        for result in results
    ])

    prompt = f"""
You are a research intelligence assistant.

Answer the question using only the research context provided below.

Question:
{question}

Research context:
{context}

Instructions:
- Give a concise and factual answer.
- Do not use information outside the provided context.
- If the context does not contain enough information, say so.
- At the end of your answer, provide the source arXiv ID.
"""

    response = llm.complete(prompt)

    return response.text, results

In [37]:
# Generate answers for all benchmark questions

rag_results = []

for item in benchmark_questions:

    answer, results = generate_rag_answer(
        item["question"]
    )

    retrieved_ids = [
        result.node.metadata.get("arxiv_id")
        for result in results
    ]

    rag_results.append({
        "id": item["id"],
        "question": item["question"],
        "expected_arxiv_id": item["expected_arxiv_id"],
        "answer": answer,
        "retrieved_ids": retrieved_ids
    })

rag_results_df = pd.DataFrame(rag_results)

rag_results_df

2026-10-06 15:35:48,711 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:35:50,150 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:35:50,305 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:35:50,308 | INFO | Retrying request to /chat/completions in 2.000000 seconds
2026-10-06 15:35:53,302 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:35:53,517 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:35:53,518 | INFO | Retrying request to /chat/completions in 17.000000 seconds
2026-10-06 15:36:11,728 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:36:13,087 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:13,089 | INFO | Retrying request to /chat/completions in 13.000000 seconds
2026-10-06 15:36:26,723 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:36:27,866 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:27,905 | INFO | Retrying request to /chat/completions in 9.000000 seconds
2026-10-06 15:36:37,366 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:37,377 | INFO | Retrying request to /chat/completions in 4.000000 seconds
2026-10-06 15:36:42,088 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:36:43,608 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:43,613 | INFO | Retrying request to /chat/completions in 28.000000 seconds
2026-10-06 15:37:11,919 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:37:11,925 | INFO | Retrying request to /chat/completions in 3.000000 seconds
2026-10-06 15:37:15,789 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:37:16,606 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:37:16,611 | INFO | Retrying request to /chat/completions in 25.000000 seconds
2026-10-06 15:37:42,769 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

,id,question,expected_arxiv_id,answer,retrieved_ids
0,Q1,What problem does Pandora's AI Model Routing B...,2608.20316v1,Pandora’s AI Model Routing Box tackles the cha...,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260..."
1,Q2,How does Pandora's AI Model Routing Box improv...,2608.20316v1,Pandora’s AI Model Routing Box improves effici...,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260..."
2,Q3,What is AI4AI-Bench designed to evaluate?,2608.20318v1,AI4AI‑Bench is a benchmark that tests whether ...,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260..."
3,Q4,How does AI4AI-Bench assess the performance of...,2608.20318v1,AI4AI‑Bench evaluates an LLM agent by letting ...,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260..."
4,Q5,What information is used to induce task models...,2608.20319v1,Task models are induced from the low‑level eve...,"[2608.20319v1, 2608.20319v1, 2608.20319v1, 260..."
5,Q6,What is the purpose of the agentic approach fo...,2608.20320v1,The agentic approach is designed to unify the ...,"[2608.20320v1, 2608.20320v1, 2608.20320v1, 260..."
6,Q7,What problem does grounded checklist-aligned r...,2608.20331v1,Grounded checklist‑aligned reward learning (G‑...,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260..."
7,Q8,How is reward learning used to improve patient...,2608.20331v1,Reward learning in G‑CARL improves patient‑ori...,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260..."

In [38]:
# Review generated answers

for _, row in rag_results_df.iterrows():

    print(f"--- {row['id']} ---")
    print(f"Question: {row['question']}")
    print()
    print(f"Answer: {row['answer']}")
    print()
    print(f"Expected source: {row['expected_arxiv_id']}")
    print("-" * 60)

--- Q1 ---
Question: What problem does Pandora's AI Model Routing Box aim to solve?

Answer: Pandora’s AI Model Routing Box tackles the challenge of **efficiently allocating tasks to AI models when estimating each model’s value is expensive**—i.e., it seeks to optimize routing decisions while accounting for the cost of value estimation.

Source: arXiv 2608.20316v1

Expected source: 2608.20316v1
------------------------------------------------------------
--- Q2 ---
Question: How does Pandora's AI Model Routing Box improve the efficiency of AI model selection?

Answer: Pandora’s AI Model Routing Box improves efficiency by routing queries to the most valuable models using a cost‑aware value‑estimation framework.  The system employs value estimators (Section C.1) and carefully designed prompts (Section C.2) to predict each model’s expected benefit, allowing it to limit the number of inspections (see Supplemental Results D.1) and the monetary cost of value‑function evaluations (Supplemental Results D.3).  This targeted allocation reduces overall regret plus inspection cost, as shown in Table 4 on RAG routing, where the Box achieves the lowest combined metric among compared methods.

Source: arXiv 2608.20316v1.

Expected source: 2608.20316v1
------------------------------------------------------------
--- Q3 ---
Question: What is AI4AI-Bench designed to evaluate?

Answer: AI4AI‑Bench is a benchmark that tests whether a large‑language‑model agent can write code that improves the training algorithm of a repository’s own model.  The agent’s submission is evaluated by running the modified code under the same conditions as the original, and a fixed evaluator computes a metric (e.g., accuracy, solve‑rate, loss).  The benchmark measures whether the agent’s code yields a better metric than the baseline, thus assessing the agent’s ability to perform recursive self‑improvement in algorithm design.

Source: arXiv 2608.20318v1

Expected source: 2608.20318v1
------------------------------------------------------------
--- Q4 ---
Question: How does AI4AI-Bench assess the performance of LLM agents in algorithmic design?

Answer: AI4AI‑Bench evaluates an LLM agent by letting it modify the training algorithm of a frozen research repository and then measuring the quality of the resulting model with a **fixed, pre‑defined evaluator**.

1. **Baseline** – The original repository’s code is run once to produce a baseline model \(C\).
2. **Agent submission** – The agent’s code produces a modified training algorithm \(C'\).
3. **Evaluation** – Both \(C\) and \(C'\) are trained under identical conditions (same hardware, budget, and evaluator).
4. **Metric** – A fixed evaluator \(m\) computes a scalar score \(s(C)=m(a(C))\) and \(s(C')=m(a(C'))\).
5. **Improvement test** – The submission is considered better if
   \[
   s(C') > s(C) \quad \text{for upward‑directed metrics (↑)} \quad\text{or}\quad
   s(C') < s(C) \quad \text{for downward‑directed metrics (↓)} .
   \]
6. **Dense scoring** – Rather than a binary win/lose, the benchmark reports the actual metric value, providing a dense score that reflects the magnitude of improvement.

Thus, AI4AI‑Bench assesses performance by comparing the evaluator‑derived metric of the agent‑generated model to that of the baseline, using a dense, direction‑aware score.

**Source:** arXiv:2608.20318v1.

Expected source: 2608.20318v1
------------------------------------------------------------
--- Q5 ---
Question: What information is used to induce task models from computer-use traces?

Answer: Task models are induced from the low‑level events that are passively recorded during computer use: screenshots of the screen and the corresponding mouse or keyboard actions.

Source: arXiv 2608.20319v1

Expected source: 2608.20319v1
------------------------------------------------------------
--- Q6 ---
Question: What is the purpose of the agentic approach for active data collection and travel behaviour modelling?

Answer: The agentic approach is designed to unify the traditionally separate stages of travel‑behavior research into a single, transparent, and modular workflow. By linking a conversational data‑collection agent, a structured data‑processing agent, and a behavioral‑prediction agent, it enables an AI‑assisted survey to capture context‑dependent travel behavior and to feed that data directly into predictive models (e.g., LLMs, DCMs, ML benchmarks). The goal is to streamline the process from survey administration to behavioral prediction while allowing systematic evaluation of how different information types and AI configurations affect mode‑choice accuracy.

Source: arXiv 2608.20320v1

Expected source: 2608.20320v1
------------------------------------------------------------
--- Q7 ---
Question: What problem does grounded checklist-aligned reward learning address in patient-oriented medical research?

Answer: Grounded checklist‑aligned reward learning (G‑CARL) tackles the problem of producing **clinically accurate, evidence‑grounded interpretations of medical reports that also respect patient‑specific context and clinical checklists**. In patient‑oriented medical research, existing methods (e.g., simple fine‑tuning or “LLM‑as‑a‑Judge”) often misdiagnose abnormalities, ignore relevant patient history, or fail to answer the user’s primary question. G‑CARL aligns the model’s outputs with a checklist of clinical criteria and evidence‑based rewards, thereby improving diagnostic accuracy, contextual integration, and recommendation quality.

**Source:** arXiv:2608.20331v1

Expected source: 2608.20331v1
------------------------------------------------------------
--- Q8 ---
Question: How is reward learning used to improve patient-oriented medical outcomes?

Answer: Reward learning in G‑CARL improves patient‑oriented medical outcomes by providing fine‑grained, evidence‑grounded supervision for language models that interpret medical reports. The framework decomposes rewards into two types:

1. **Retrieval‑grounded claim reward** – each atomic medical claim in a generated response is verified against the uploaded report and a multi‑source medical datastore. This gives localized feedback on factual accuracy and discourages unsupported elaboration, ensuring that the information patients receive is verifiable and clinically reliable.

2. **Checklist‑guided reward** – for context‑dependent goals such as demand satisfaction and expression quality, G‑CARL generates instance‑specific weighted checklists (refined by clinicians). The reward emphasizes the checklist items most relevant to the current report and user question, providing transparent supervision that the response addresses the patient’s concerns appropriately.

By aligning rewards with verifiability and patient‑specific needs, G‑CARL consistently outperforms supervised and other reinforcement‑learning baselines, with gains confirmed by clinician preference and user comprehension studies. This leads to more accurate, relevant, and patient‑friendly medical interpretations, thereby improving patient‑oriented outcomes.

**Source:** arXiv ID 2608.20331v1.

Expected source: 2608.20331v1
------------------------------------------------------------

In [40]:
# Create answer evaluation table

answer_evaluation_df = rag_results_df[
    [
        "id",
        "question",
        "answer",
        "expected_arxiv_id"
    ]
].copy()

# Manual evaluation
# 0 = poor, 1 = partial, 2 = strong

answer_evaluation_df["answer_relevance"] = [
    2,  # Q1
    2,  # Q2
    2,  # Q3
    2,  # Q4
    2,  # Q5
    2,  # Q6
    2,  # Q7
    2   # Q8
]

answer_evaluation_df["faithfulness"] = [
    2,  # Q1
    2,  # Q2
    2,  # Q3
    2,  # Q4
    2,  # Q5
    2,  # Q6
    2,  # Q7
    2   # Q8
]

answer_evaluation_df["citation_accuracy"] = [
    2,  # Q1
    2,  # Q2
    2,  # Q3
    2,  # Q4
    2,  # Q5
    2,  # Q6
    2,  # Q7
    2   # Q8
]

answer_evaluation_df

,id,question,answer,expected_arxiv_id,answer_relevance,faithfulness,citation_accuracy
0,Q1,What problem does Pandora's AI Model Routing B...,Pandora’s AI Model Routing Box tackles the cha...,2608.20316v1,2,2,2
1,Q2,How does Pandora's AI Model Routing Box improv...,Pandora’s AI Model Routing Box improves effici...,2608.20316v1,2,2,2
2,Q3,What is AI4AI-Bench designed to evaluate?,AI4AI‑Bench is a benchmark that tests whether ...,2608.20318v1,2,2,2
3,Q4,How does AI4AI-Bench assess the performance of...,AI4AI‑Bench evaluates an LLM agent by letting ...,2608.20318v1,2,2,2
4,Q5,What information is used to induce task models...,Task models are induced from the low‑level eve...,2608.20319v1,2,2,2
5,Q6,What is the purpose of the agentic approach fo...,The agentic approach is designed to unify the ...,2608.20320v1,2,2,2
6,Q7,What problem does grounded checklist-aligned r...,Grounded checklist‑aligned reward learning (G‑...,2608.20331v1,2,2,2
7,Q8,How is reward learning used to improve patient...,Reward learning in G‑CARL improves patient‑ori...,2608.20331v1,2,2,2

In [41]:
# Calculate generation metrics

answer_relevance = (
    answer_evaluation_df["answer_relevance"].mean() / 2
)

faithfulness = (
    answer_evaluation_df["faithfulness"].mean() / 2
)

citation_accuracy = (
    answer_evaluation_df["citation_accuracy"].mean() / 2
)

print("Baseline RAG Generation Performance")
print("-" * 40)
print(f"Answer Relevance: {answer_relevance:.2%}")
print(f"Faithfulness: {faithfulness:.2%}")
print(f"Citation Accuracy: {citation_accuracy:.2%}")

Baseline RAG Generation Performance
----------------------------------------
Answer Relevance: 100.00%
Faithfulness: 100.00%
Citation Accuracy: 100.00%

In [42]:
# Final baseline RAG results

final_results = pd.DataFrame({
    "Metric": [
        "Hit@1",
        "Hit@3",
        "Hit@5",
        "Answer Relevance",
        "Faithfulness",
        "Citation Accuracy"
    ],
    "Score": [
        hit_at_1,
        hit_at_3,
        hit_at_5,
        answer_relevance,
        faithfulness,
        citation_accuracy
    ]
})

final_results["Score"] = final_results["Score"].map(
    lambda x: f"{x:.2%}"
)

final_results

              Metric    Score
0              Hit@1  100.00%
1              Hit@3  100.00%
2              Hit@5  100.00%
3   Answer Relevance  100.00%
4       Faithfulness  100.00%
5  Citation Accuracy  100.00%

In [43]:
# Save generated RAG answers

rag_results_df.to_csv(
    processed_dir / "baseline_rag_answers.csv",
    index=False
)

print("Saved: baseline_rag_answers.csv")

Saved: baseline_rag_answers.csv

In [44]:
# Save manual answer evaluation

answer_evaluation_df.to_csv(
    processed_dir / "baseline_answer_evaluation.csv",
    index=False
)

print("Saved: baseline_answer_evaluation.csv")

Saved: baseline_answer_evaluation.csv

In [45]:
# Save final baseline RAG results

final_results.to_csv(
    processed_dir / "baseline_rag_results.csv",
    index=False
)

print("Saved: baseline_rag_results.csv")

Saved: baseline_rag_results.csv

## Baseline RAG Evaluation Summary

The baseline RAG pipeline was evaluated using an eight-question benchmark covering the five research papers in the dataset. Retrieval performance was measured using Hit@1, Hit@3, and Hit@5, while generated responses were manually evaluated for answer relevance, faithfulness to the retrieved context, and citation accuracy.

The baseline achieved 100% Hit@1, Hit@3, and Hit@5 on the benchmark. The generated responses also achieved 100% on answer relevance, faithfulness, and citation accuracy based on the manual evaluation.

These results indicate that the baseline pipeline successfully retrieved the expected source paper and generated relevant, context-supported answers for the benchmark questions. However, the benchmark contains only eight questions, so these results should be interpreted as baseline performance on the current evaluation set rather than evidence of general RAG performance.

## Evaluation Methodology

### Retrieval Evaluation

Retrieval performance was evaluated using three metrics:

- **Hit@1:** whether the expected source paper was ranked first.
- **Hit@3:** whether the expected source paper appeared within the top three retrieved results.
- **Hit@5:** whether the expected source paper appeared within the top five retrieved results.

### Generation Evaluation

Generated answers were manually evaluated using a 0–2 scale:

- **Answer Relevance:** whether the response directly answers the benchmark question.
- **Faithfulness:** whether the response is supported by the retrieved research context.
- **Citation Accuracy:** whether the cited arXiv source corresponds to the expected source paper.

A score of 2 represents a strong result, 1 represents a partial result, and 0 represents an incorrect or unsupported result.

# Part 5: Prompt Engineering for Business Insights

## Objective

Design and test a prompt engineering strategy that translates technical AI research findings into clear, accurate, and actionable business insights.

The goal is to help non-technical stakeholders understand research findings, their potential business impact, and possible next steps while maintaining source citations.

In [33]:
# Part 5: Business-Friendly Prompt Engineering

BUSINESS_INSIGHT_PROMPT = """
You are an AI research analyst helping business leaders
understand technical AI research.

Your task is to translate research findings into clear,
accurate, and actionable business insights.

Follow these instructions:
1. Use simple language that non-technical readers understand.
2. Avoid unnecessary technical jargon.
3. Explain how the research could affect businesses.
4. Identify potential benefits, risks, and limitations.
5. Do not invent facts or unsupported claims.
6. Use only the provided research context.
7. Include source citations when available.
8. Clearly distinguish research findings from possible business implications.
9. Do not claim specific cost savings, speed improvements, or
   performance gains unless the research provides evidence.
10. Cite the source title and page number for important findings.
11. If the research does not support a recommendation,
    explain that more evidence is needed.
12. Do not treat a potential benefit as a proven result.

Structure your response as follows:

Executive Summary:
Briefly explain the main finding in 2-3 sentences.

Key Findings:
Summarize the most important research findings.

Business Implications:
Explain how these findings could affect organizations.

Recommendations:
Suggest practical next steps supported by the research.

Limitations:
Explain uncertainties or missing information.

Sources:
Include relevant paper titles and page numbers.

Research Context:
{context}

Business Question:
{question}
"""

In [34]:
# Check if the RAG components are loaded

print("Retriever available:", "retriever" in globals())
print("Groq client available:", "client" in globals())
print("Prompt available:", "BUSINESS_INSIGHT_PROMPT" in globals())

Retriever available: False
Groq client available: False
Prompt available: True

In [35]:
import sys

print(sys.version)
print(sys.executable)

3.11.5 (v3.11.5:cce6ba91b3, Aug 24 2023, 10:50:31) [Clang 13.0.0 (clang-1300.0.29.30)]
/Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/bin/python

In [36]:
# Build a business-friendly prompt using research context

def build_business_prompt(question, context):
    """Create a prompt that translates research into business insights."""

    if not question.strip():
        raise ValueError("Question cannot be empty.")

    if not context.strip():
        raise ValueError("Research context cannot be empty.")

    prompt = BUSINESS_INSIGHT_PROMPT.format(
        question=question,
        context=context
    )

    return prompt

In [37]:
# Test the prompt with sample research information

test_question = "How can AI model routing help businesses reduce costs?"

test_context = """
Research finding:
AI model routing assigns different tasks to different models.
Simpler tasks can be handled by smaller models, while complex
tasks can be assigned to more capable models.

Potential benefit:
This approach may reduce computational costs while maintaining
acceptable performance.

Source:
Pandora's AI Model Routing Box, page 1.
"""

formatted_prompt = build_business_prompt(
    test_question,
    test_context
)

print(formatted_prompt)

You are an AI research analyst helping business leaders
understand technical AI research.

Your task is to translate research findings into clear,
accurate, and actionable business insights.

Follow these instructions:
1. Use simple language that non-technical readers understand.
2. Avoid unnecessary technical jargon.
3. Explain how the research could affect businesses.
4. Identify potential benefits, risks, and limitations.
5. Do not invent facts or unsupported claims.
6. Use only the provided research context.
7. Include source citations when available.
8. Clearly distinguish research findings from possible business implications.
9. Do not claim specific cost savings, speed improvements, or
   performance gains unless the research provides evidence.
10. Cite the source title and page number for important findings.
11. If the research does not support a recommendation,
    explain that more evidence is needed.
12. Do not treat a potential benefit as a proven result.

Structure your response as follows:

Executive Summary:
Briefly explain the main finding in 2-3 sentences.

Key Findings:
Summarize the most important research findings.

Business Implications:
Explain how these findings could affect organizations.

Recommendations:
Suggest practical next steps supported by the research.

Limitations:
Explain uncertainties or missing information.

Sources:
Include relevant paper titles and page numbers.

Research Context:

Research finding:
AI model routing assigns different tasks to different models.
Simpler tasks can be handled by smaller models, while complex
tasks can be assigned to more capable models.

Potential benefit:
This approach may reduce computational costs while maintaining
acceptable performance.

Source:
Pandora's AI Model Routing Box, page 1.


Business Question:
How can AI model routing help businesses reduce costs?

In [38]:
# Generate business-friendly insights using an LLM

def generate_business_insight(question, context, llm):
    """
    Generate a business-friendly explanation
    from technical research findings.
    """

    prompt = build_business_prompt(question, context)

    response = llm.complete(prompt)

    return str(response)

In [39]:
# Check whether the Groq model is already initialized

print("Groq class available:", "Groq" in globals())
print("LLM available:", "llm" in globals())

Groq class available: True
LLM available: False

In [40]:
# Check whether the Groq API key is configured

import os

print("Groq API key available:", bool(os.getenv("GROQ_API_KEY")))

Groq API key available: True

In [44]:

import os
from pathlib import Path
from dotenv import load_dotenv

project_root = Path.cwd()
if project_root.name == "notebooks":
    project_root = project_root.parent

load_dotenv(project_root / ".env")

print("Groq API key available:", bool(os.getenv("GROQ_API_KEY")))

Groq API key available: True

In [45]:
# Initialize Groq using an available model

from llama_index.llms.groq import Groq
import os

llm = Groq(
    model="openai/gpt-oss-20b",
    api_key=os.getenv("GROQ_API_KEY"),
    temperature=0.2
)

print("Groq model initialized successfully!")

Groq model initialized successfully!

In [71]:
import os
from pathlib import Path
from dotenv import load_dotenv
from llama_index.llms.groq import Groq

project_root = Path.cwd()
if project_root.name == "notebooks":
    project_root = project_root.parent

load_dotenv(project_root / ".env", override=True)

key = os.getenv("GROQ_API_KEY", "").strip()

if not key or key == "your_groq_api_key_here":
    raise ValueError("A real Groq API key is not configured.")

# UPDATED: use a currently supported Groq model.
# llama-3.3-70b-versatile is no longer available for this account tier.

llm = Groq(
    model="openai/gpt-oss-120b",
    api_key=key,
    temperature=0.2
)

print("Groq configuration loaded.")

Groq configuration loaded.

In [51]:
%pip install groq

Requirement already satisfied: groq in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (1.7.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from groq) (4.15.1)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from groq) (2.14.1)
Requirement already satisfied: sniffio in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.14 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from groq) (4.16.0)
Requirement already satisfied: idna>=2.8 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from anyio<5,>=3.5.0->groq) (3.20)
Requirement already satisfied: certifi in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from httpx<1,>=0.23.0->groq) (2026.10.23)
Requirement already satisfied: httpcore==1.* in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->groq) (0.8.0)
Requirement already satisfied: pydantic-core==2.50.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->groq) (2.50.1)
Requirement already satisfied: typing-inspection>=0.4.4 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv-test/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->groq) (0.4.4)

[notice] A new release of pip is available: 23.2.1 -> 26.2.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [55]:
import os
from groq import Groq as GroqClient

client = GroqClient(api_key=os.getenv("GROQ_API_KEY"))

models = client.models.list()

for model in models.data:
    print(model.id)

2026-10-27 01:38:50,415 | INFO | HTTP Request: GET https://api.groq.com/openai/v1/models "HTTP/1.1 200 OK"

openai/gpt-oss-120b
meta-llama/llama-prompt-guard-2-86m
meta-llama/llama-prompt-guard-2-22m
openai/gpt-oss-20b
whisper-large-v3-turbo
whisper-large-v3
canopylabs/orpheus-v1-english
openai/gpt-oss-safeguard-20b
allam-2-7b
qwen/qwen3.8-27b
canopylabs/orpheus-arabic-saudi

In [72]:
response = llm.complete("Reply with only the word READY.")
print(response)

2026-10-27 01:42:43,324 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

READY

In [73]:
business_response = generate_business_insight(
    question=test_question,
    context=test_context,
    llm=llm
)

print(business_response)

2026-10-27 01:42:56,712 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

**Executive Summary**
Research shows that routing tasks to different AI models—using smaller, cheaper models for simple work and larger, more powerful models for complex work—can lower the amount of computing power needed while still delivering acceptable results (Pandora’s AI Model Routing Box, p. 1). For businesses, this suggests a way to cut AI‑related expenses without sacrificing quality.

---

### Key Findings
| Finding | What the research says |
|---------|------------------------|
| **Task‑based model selection** | An AI system can automatically decide which model to use for each incoming request, matching task difficulty to model size. |
| **Cost‑efficiency potential** | By assigning simple tasks to smaller models, overall computational demand—and therefore cost—can be reduced, while complex tasks continue to receive the full capability of larger models. (Pandora’s AI Model Routing Box, p. 1) |
| **Performance remains acceptable** | The study notes that performance stays within acceptable limits when using this routing strategy, though exact metrics are not provided. |

---

### Business Implications
1. **Lower cloud‑compute bills** – Running fewer large‑model inferences means less GPU/CPU time, which translates into lower usage fees from cloud providers.
2. **Scalable AI services** – Companies can handle higher request volumes because cheaper models can process the bulk of easy queries, freeing up capacity for the harder ones.
3. **Resource optimization** – IT teams can better allocate hardware (e.g., keep a few high‑end servers for complex jobs and use cheaper servers for routine tasks).
4. **Risk of uneven quality** – If the routing logic misclassifies a task as “simple,” a smaller model might produce sub‑par results, potentially affecting user experience or downstream decisions.

---

### Recommendations
| Step | Action | Why it aligns with the research |
|------|--------|---------------------------------|
| 1️⃣ | **Map your AI workload** – List the types of queries or tasks your AI system handles and label them as “simple” or “complex” based on current performance requirements. | Provides the data needed for a routing rule set. |
| 2️⃣ | **Select a tiered model portfolio** – Choose at least one small, cost‑effective model (e.g., a distilled version) and one larger, high‑accuracy model. | Mirrors the “small vs. large” model split described in the study. |
| 3️⃣ | **Implement a routing layer** – Use a lightweight decision engine (rule‑based or a tiny classifier) that directs each incoming request to the appropriate model. | Directly applies the “model routing” concept. |
| 4️⃣ | **Run a controlled pilot** – Deploy the routing system on a limited traffic segment, track computational usage, latency, and outcome quality. | Allows you to verify the “acceptable performance” claim before full rollout. |
| 5️⃣ | **Monitor and refine** – Continuously review mis‑routed cases and adjust the routing criteria or model selection as needed. | Addresses the risk of quality degradation. |
| 6️⃣ | **Calculate cost impact** – After the pilot, compare cloud‑compute spend against the baseline to quantify any savings. | Provides evidence for the hypothesized cost reduction. |

---

### Limitations
- **No quantitative cost data** – The research mentions “potential” cost reduction but does not give numbers; actual savings will depend on your specific workload mix and pricing model.
- **Performance metrics are vague** – “Acceptable performance” is not defined; you must verify that quality meets your business standards.
- **Routing accuracy not measured** – The study does not report how often tasks are correctly classified, so mis‑routing risk must be evaluated in practice.
- **Scope limited to a single source** – Findings are based on Pandora’s AI Model Routing Box; other implementations may behave differently.

---

### Sources
- **Pandora's AI Model Routing Box**, page 1 – Describes the concept of assigning simpler tasks to smaller models and complex tasks to larger models, noting possible computational cost reductions while maintaining acceptable performance.

In [74]:
context=test_context

In [75]:
# Check which RAG components are available

for name in ["retriever", "hybrid_retriever", "query_engine", "index", "llm"]:
    print(f"{name}: {name in globals()}")

retriever: False
hybrid_retriever: False
query_engine: True
index: True
llm: True

In [76]:
# Access the retriever from the existing query engine

rag_retriever = query_engine.retriever

print("Retriever loaded:", rag_retriever is not None)
print("Retriever type:", type(rag_retriever).__name__)

Retriever loaded: True
Retriever type: VectorIndexRetriever

In [77]:
# Retrieve real research passages from the RAG system

research_question = "How can AI model routing help businesses reduce costs?"

retrieved_results = rag_retriever.retrieve(research_question)

print("Number of retrieved passages:", len(retrieved_results))

for i, result in enumerate(retrieved_results, start=1):
    metadata = result.node.metadata

    print(f"\n--- Source {i} ---")
    print("Title:", metadata.get("title", "Unknown"))
    print("Page:", metadata.get("page_number", "Unknown"))
    print("Score:", result.score)
    print("Text:", result.node.text[:500])

Number of retrieved passages: 20

--- Source 1 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 12
Score: 0.6469692874625744
Text: weighted aggregation of responses across model-strategy combinations. • Uno-Orchestra[ 7]: An agentic orchestration method based on SFT and RL that dispatches subtasks to compatible model-primitive pairs, iteratively delegating or synthesizing the answer based on execution feedback. B Derivation of Inference Computational Cost Measuring computational overhead via commercial API pricing often fails to reflect actual resource consumption, as pricing fluctuates across service providers and over tim

--- Source 2 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 11
Score: 0.64071413252053
Text: A.2 Dataset We construct a dataset comprising 12,800 questions across five domains, as described in Section 5.1. The dataset is partitioned into 10,500 training, 1,000 development, and 1,300 test questions. For out-of-domain evaluation, we use 175 questions from the LiveCodeBench [22] and 200 from the BBH-LD [45]. For each training task domain, we set a shared budget in our cost units. We calibrate it from pre-collected successful traces by computing the 25th percentile of trace costs for each q

--- Source 3 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 2
Score: 0.6378537053315101
Text: internalized in the router’s pre-execution planning policy to improve the system-level trade-off between accuracy and cost? Addressing this question presents two challenges, as highlighted in Figure 2.(i) Discovering reusable routing principles within a complex, multidimensional configuration space.Jointly selecting models, collaboration modes, agent counts, interaction rounds, and skills causes a combinatorial explosion in the configuration space, making exhaustive evaluation computationally pr

--- Source 4 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 1
Score: 0.6378043775299939
Text: services such as Grok Bot and WorkBuddy, routing must extend beyond model selection to jointly determine model assignments, collaboration modes, agent counts, interaction rounds, and the skills and subtasks assigned to each agent. For service providers handling Web queries across diverse domains and difficulty levels, adaptively selecting MAS configurations to jointly optimize reasoning performance and compute cost has become a central research problem. 1 arXiv:2610.35690v1 [cs.AI] 26 Oct 2026

--- Source 5 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 2
Score: 0.6324761250295369
Text: distillation.We identify task dependence, diminishing marginal returns, and interdependence among MAS configuration choices. We distill cross-trajectory performance–cost feedback into configuration insights with explicit applicability conditions to guide exploration. 2. Insight-guided router post-training.We propose EvoRouter, which internalizes conditional insights into the routing policy through OPD and jointly optimizes execution utility 2

--- Source 6 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 2
Score: 0.6279481004156594
Text: selection at specific decision states of the current routing policy. This mismatch between high-dimensional combinatorial decisions and coarse, sparse execution feedback limits the router’s ability to learn efficiently and improve continually from limited execution experience. To address these challenges, we proposeEvoRouter, an adaptive multi-agent routing framework built around an insight-guided selfimprovement loop.To address the first challenge, we conduct preliminary experiments that system

--- Source 7 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 5
Score: 0.6279025140070534
Text: capability dimensions. Building on the observations from our preliminary experiments (Section 3.1), we develop an insight distillation expert to analyze these trajectories and continually refine routing insights. The expert integrates newly observed routing patterns from recent online trajectories with accumulated insights, capturing task-dependent preferences for resources and subtask decomposition strategies across different domains, difficulty levels, and budgets. This process enables routing

--- Source 8 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 5
Score: 0.6272725405561858
Text: observations into generalizable routing rules with explicit applicability conditions only during training. For thek-th insight update using recent rollout batchBk, the expert refines the insight set through a three-step procedure:(i) Rule induction:comparing intra-category trajectories across success or failure and cost spectra to derive conditional rules on capability alignment, scaling saturation, and configuration interactions;(ii) Precondition refinement:resolving empirical conflicts withinI

--- Source 9 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 1
Score: 0.6261955971571581
Text: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation Yitao Xiao∗ Beijing University of Posts and Telecommunications Beijing, China yitooooom@bupt.edu.cn Xu Zhang∗ Beijing University of Posts and Telecommunications Beijing, China zhangxu2024@bupt.edu.cn Ye Cheng† Beijing University of Posts and Telecommunications Beijing, China yecheng@bupt.edu.cn Shaoyong Guo Beijing University of Posts and Telecommunications Beijing, China syguo@bupt.edu.cn Yan Sun Beijing Uni

--- Source 10 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 3
Score: 0.6257312328486913
Text: Comm.Multimodal QA Knowledge 0 25 50 75 100Success Rate (%) 1k 10k 100k Mean MAS FLOPs 10k 30k 100k Mean MAS FLOPs -2 0 2 4 ΔSuccess Rate, R2 (pp) 10k 30k 100k Mean MAS FLOPs -1 0 1 2 ΔSuccess Rate, N2 (pp) FullConnected Debate 64 66 68 70 72 74Success Rate (%) +2.4 pp +1.4 pp 20k 40k 60k Mean MAS FLOPs −79.8% cost (a) Insight 1 (b) Insight 2 (c) Insight 3 mα + IO mβ + IO mα + FullConnected mβ + FullConnected mα mβ FullConnected Debate (mα, mα, mα) (mβ, mα, mα) (mα, mβ, mβ) (mβ, mβ, mβ) Figure 3

--- Source 11 ---
Title: Governing Enterprise AI Traffic at Scale: Design and Operation of a Policy-Driven, Multi-Vendor LLM Gateway on Envoy
Page: 8
Score: 0.6226672812252176
Text: a single model, and resolves toM s ={m:s∈τ(m)} ∪({s} ∩M). For budgeting, spend for user budgets is accumulatedonlyas countersc(u,m,ω)in micro-dollars, keyed by useru, immutable model identifiermand window instanceω(daily, weekly or monthly, on a single fixed calendar timezone for all regions). Hereuranges over people; application traffic is attributed by application identifier (section 11), and workflow budgets (section 8) are accumulated in counters of their own. A budget rule consists of one o

--- Source 12 ---
Title: What Effort Level Should I Choose? On the Economics of Reasoning Effort in LLM Agents
Page: 20
Score: 0.6214422273505873
Text: On the Economics of Reasoning Effort in LLM Agents 0.0 0.5 1.0 1.5 2.0 80 90Tasks solved (%) high GPT-5.6-sol 0.0 0.5 1.0 1.5 2.0 50 60 70 80 xhigh GPT-5.6-luna 0.0 0.5 1.0 1.5 2.0 60 70 80 90 xhigh Claude Sonnet 5 0.0 0.5 1.0 1.5 2.0 60 70 80 max DeepSeek V4 Flash 0.0 0.5 1.0 1.5 2.0 70 80Tasks solved (%) high GLM-5.2 0.0 0.5 1.0 1.5 2.0 30 40 50 max Inkling 0.0 0.5 1.0 1.5 2.0 70 80 90 high Kimi K3 Full cost relative to the most accurate fixed effort (1.0) Fixed effort Self-router Random route

--- Source 13 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 4
Score: 0.6180104952475354
Text: an all-mβ configuration outperforms an all-mα configuration under FullConnected, whereas the latter achieves higher success rates under Debate while reducing MAS FLOPs by 79.8%. Therefore,routing insights should capture effective resource combinations and the conditions under which they excel(Insight 3). Together, these insights guide subsequent insights distillation from three complementary perspectives: task alignment, scaling saturation, and configuration interactions. Building on these findi

--- Source 14 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 12
Score: 0.617795648068349
Text: and counting causal attention pairs, we obtain: Fm≈2AmN+4LD N∑︁ t=1 t+R m =2AmN+2LDN(N+1)+R m. (11) Since parameter matrix operations dominate overall computation (exceeding 95% of total FLOPs in our experiments), we omit both the attention interaction term andRm, yielding the FLOPs proxy bFm = 2Am(nin+n out). Taking the active parameter count of the smallest model in our LLM pool, Qwen3.5-35B-A3B (A0 = 3× 109), as the reference baseline, we define2 A0 FLOPs as one cost unit. LetIW(τ) denote the

--- Source 15 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 10
Score: 0.6158224156724296
Text: Xia, Lifan Sun, Weiyou Tian, Tianyu Shi, and Lewei He. 2026. Difficulty-Aware Agentic Orchestration for Query-Specific Multi-Agent Workflows. InProceedings of the ACM Web Conference 2026. Association for Computing Machinery, 2060–2070. doi:10.1145/3774904.3792240 [45] Mirac Suzgun, Nathan Scales, Nathanael Schärli, Sebastian Gehrmann, Yi Tay, Hyung Won Chung, Aakanksha Chowdhery, Quoc Le, Ed Chi, Denny Zhou, and Jason Wei. 2023. Challenging BIG-Bench Tasks and Whether Chain-of-Thought Can Solve

--- Source 16 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 3
Score: 0.6153586097878259
Text: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation Table 1: Representative learning methods for MAS routing. Method Routing scope Learning signal Training mechanism RouteLLM [36] Single-model choice Pairwise preferences Supervised learning Router-R1 [61] Multi-round calls Format, outcome, cost Outcome-based RL MasRouter [59] Modes, roles, models Utility–cost reward Policy gradients DAAO [44] Depth, operators, models Success, utility, cost Difficulty calibrati

--- Source 17 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 5
Score: 0.6113907871645622
Text: then instantiate the utility in Eq. (2) as the following reward function R(τ): R(τ)=R perf−λCRcost,(4) whereλC controls cost sensitivity. To strictly separate the reward ranges of successful and failed rollouts, we further cap the weighted cost penalty atcmax∈[ 0, 1) to ensure that successful trajectories receive rewards of at least1−c max > 0, while unsuccessful trajectories receive nonpositive rewards. Details of cost weighting are provided in Appendix A.2. Group-relative policy updates.For ea

--- Source 18 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 4
Score: 0.611367300920251
Text: outcomeo∼E(·|q,P) to the router, whereE(·| q,P) denotes the distribution of execution outcomes conditioned on the task and configuration. The router then generates a final answer ˆy for taskq, forming a complete trajectoryτ. A task-specific verifier (e.g., sandbox tests for code generation or exact-match evaluation for question answering) evaluates the final answer, with s(τ)∈{0,1}indicating whether it passes verification. LetC(τ)≥ 0denote the execution cost of the routed MAS along trajectoryτ,

--- Source 19 ---
Title: Governing Enterprise AI Traffic at Scale: Design and Operation of a Policy-Driven, Multi-Vendor LLM Gateway on Envoy
Page: 14
Score: 0.607939566113956
Text: a system of record. L10. Routing is not the differentiator.Off-the-shelf proxies route well. What our organization needed, and the off-the-shelf proxy we evaluated did not provide at the time, was real-time support, identity-aware authorization, organization-aware spend control and workloadidentity-based cloud credentials. 15 Limitations and Future Work Several limitations remain. Centralizing access also concentrates risk: the gateway brokers credentials for every provider, so it is a high-valu

--- Source 20 ---
Title: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 2
Score: 0.607746187109564
Text: First Author et al. Performance Motivation Challenge 1 Highly Coupled Configuration Conditional Insight Distillation LLM Expert Challenge 2 Sparse Routing Reward Signals Scaling Capability Compatibility Perf & Cost Route Trajectory Teacher Model Insight Student’s Token Teacher’s Token RL Cost Perf OPD Task Accuracy Cost Figure 2: Motivation and performance of EvoRouter. Left: Two challenges and our solutions. Right: EvoRouter’s performance. Existing MAS routing research primarily improves routin

In [78]:
# Build research context from retrieved passages

def build_research_context(results, max_sources=5):
    context_parts = []

    for result in results[:max_sources]:
        metadata = result.node.metadata

        title = metadata.get("title", "Unknown")
        page = metadata.get("page_number", "Unknown")
        text = result.node.text

        context_parts.append(
            f"Source: {title}\n"
            f"Page: {page}\n"
            f"Research Text: {text}"
        )

    return "\n\n---\n\n".join(context_parts)


real_context = build_research_context(retrieved_results)

print("Context length:", len(real_context))
print(real_context[:1000])

Context length: 7028
Source: EvoRouter: Cost-Efficient Multi-Agent Routing via Insight-Guided On-Policy Distillation
Page: 12
Research Text: weighted aggregation of responses across model-strategy combinations. • Uno-Orchestra[ 7]: An agentic orchestration method based on SFT and RL that dispatches subtasks to compatible model-primitive pairs, iteratively delegating or synthesizing the answer based on execution feedback. B Derivation of Inference Computational Cost Measuring computational overhead via commercial API pricing often fails to reflect actual resource consumption, as pricing fluctuates across service providers and over time. For clarity and conciseness, we instead model a standard decoder-only Mixture-of-Experts modelm withL layers and hidden dimensionD, where each layer activatesk equally sized routed experts. Let Psh denote the parameter count of the always-active backbone matrices—including attention projections, routers, and shared experts—andPexp denote that of a single routed expert. The a

In [79]:
# Test a more specific research question

research_question = (
    "How do large language model routing systems "
    "select between smaller and larger AI models "
    "to reduce inference costs?"
)

retrieved_results = rag_retriever.retrieve(research_question)

print("Retrieved passages:", len(retrieved_results))

for i, result in enumerate(retrieved_results[:5], start=1):
    print(f"\nSource {i}:")
    print("Title:", result.node.metadata.get("title", "Unknown"))
    print("Page:", result.node.metadata.get("page_number", "Unknown"))
    print("Score:", result.score)

Retrieved passages: 20

Source 1:
Title: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 9
Score: 0.7255590041692054

Source 2:
Title: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 3
Score: 0.7245742972251632

Source 3:
Title: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 2
Score: 0.7209651338205065

Source 4:
Title: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 24
Score: 0.7197404170607512

Source 5:
Title: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 1
Score: 0.7176741776709353

In [80]:
# Generate business insights using real retrieved research

# Build context from the latest retrieval results
real_context = build_research_context(
    retrieved_results,
    max_sources=5
)

# Generate business-friendly insights
real_business_response = generate_business_insight(
    question=research_question,
    context=real_context,
    llm=llm
)

print(real_business_response)

2026-10-27 01:43:19,257 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

**Executive Summary**
The ParetoRSI‑Gym study investigates how autonomous agents can curate training data to improve large language models (LLMs) across several domains (e.g., medicine, finance, math). It does **not** examine how inference‑time routing systems choose between smaller and larger models to cut costs. Consequently, the research does not provide direct evidence or guidance for building or evaluating such routing mechanisms.

**Key Findings** (from the supplied research)
1. **Agent‑driven data curation can raise generalization scores** – the strongest agent (Claude Code + Opus‑5) improved average domain scores by +2.3 absolute points (≈9.2 % relative) over the starting model (Page 2).
2. **Improvements are uneven across domains** – the biggest gains appear in medical and finance tasks (up to +14.8 points), while math performance can initially drop before recovering (Page 24).
3. **The “harness” (the interface that connects the agent to the model) matters** – varying only the harness while keeping the backbone fixed still produced score changes ranging from +0.2 to +4.3 points (Page 3).
4. **Agents develop distinct data‑selection strategies** – runs of the same agent overlap only 24 % on chosen datasets (Jaccard), versus 7 % for different agents (Page 3).

**Business Implications**
- **Relevance to model improvement pipelines** – The study shows that autonomous agents can meaningfully augment LLM capabilities when the focus is on *training* data selection, not on *inference* routing. Companies interested in continuously improving their proprietary models may explore similar agent‑based curation loops.
- **No direct insight for inference‑cost routing** – Because the research does not address runtime model selection, it cannot be used to predict cost savings, latency reductions, or accuracy trade‑offs that arise from routing smaller vs. larger models.

**Recommendations**
1. **Treat the findings as evidence for training‑stage automation** – If your organization seeks to boost model performance across multiple domains, consider piloting an agent‑driven data‑curation workflow similar to ParetoRSI‑Gym, while monitoring domain‑specific gains and regressions.
2. **Seek complementary literature** – To answer the specific question of inference‑time routing, look for studies on “model cascades,” “mixture‑of‑experts routing,” or “dynamic inference selection” that evaluate cost‑accuracy trade‑offs.
3. **Prototype a small‑scale routing test** – Use a simple rule‑based router (e.g., based on input length, domain tag, or confidence score) to direct queries to a lightweight model first, falling back to a larger model when needed. Measure latency, GPU/CPU utilization, and downstream task performance.
4. **Monitor for emerging research** – The field of recursive self‑improvement (RSI) and autonomous agents is rapidly evolving; future work may extend the ParetoRSI‑Gym framework to include inference‑time decisions.

**Limitations**
- **Scope mismatch** – The provided paper focuses exclusively on *post‑training data selection* and multi‑round fine‑tuning, not on *runtime inference* or model routing strategies.
- **Domain‑specific results** – Gains reported are averaged across five domains; performance may vary dramatically for tasks not covered in the study.
- **Agent robustness** – The agents often peaked before the final round, indicating they currently lack the ability to sustain continuous improvement (Page 3).

**Sources**
- *ParetoRSI‑Gym: Can AI Agents Improve Language Models Across Multiple Domains?* – Page 2 (overall performance gains).
- *ParetoRSI‑Gym* – Page 3 (impact of the harness and dataset‑selection overlap).
- *ParetoRSI‑Gym* – Page 24 (math accuracy fluctuations and dataset‑length effects).

## Part 5 Evaluation: Business Insight Quality

The business-friendly prompt is evaluated using five criteria:

1. **Clarity:** Is the response understandable to a non-technical audience?
2. **Accuracy:** Does the response correctly represent the research?
3. **Business Relevance:** Does it explain why the findings matter to organizations?
4. **Actionability:** Does it provide practical recommendations?
5. **Source Grounding:** Are claims supported by the retrieved research passages?

Each criterion will be scored from 1 (poor) to 5 (excellent).

The evaluation will compare the generated response against its retrieved source passages to identify unsupported claims and areas for improvement.

In [81]:
# Evaluation rubric for business-friendly insights

evaluation_criteria = {
    "Clarity": 0,
    "Accuracy": 0,
    "Business Relevance": 0,
    "Actionability": 0,
    "Source Grounding": 0
}

for criterion in evaluation_criteria:
    print(f"{criterion}: Not evaluated yet")

Clarity: Not evaluated yet
Accuracy: Not evaluated yet
Business Relevance: Not evaluated yet
Actionability: Not evaluated yet
Source Grounding: Not evaluated yet

In [82]:
# Score business insight quality using human review

def evaluate_business_insight(scores):
    """
    Evaluate a business insight using five criteria.
    Each score must be between 1 and 5.
    """

    criteria = [
        "Clarity",
        "Accuracy",
        "Business Relevance",
        "Actionability",
        "Source Grounding"
    ]

    for criterion in criteria:
        score = scores.get(criterion)

        if score is None or not 1 <= score <= 5:
            raise ValueError(
                f"{criterion} must have a score between 1 and 5."
            )

    average = sum(scores[c] for c in criteria) / len(criteria)

    print("Business Insight Evaluation")
    print("---------------------------")

    for criterion in criteria:
        print(f"{criterion}: {scores[criterion]}/5")

    print(f"\nAverage Score: {average:.2f}/5")

    return average

In [83]:
# Display the generated response and its supporting research

print("BUSINESS INSIGHT")
print("=" * 50)
print(real_business_response)

print("\nRETRIEVED RESEARCH")
print("=" * 50)
print(real_context)

BUSINESS INSIGHT
==================================================
**Executive Summary**
The ParetoRSI‑Gym study investigates how autonomous agents can curate training data to improve large language models (LLMs) across several domains (e.g., medicine, finance, math). It does **not** examine how inference‑time routing systems choose between smaller and larger models to cut costs. Consequently, the research does not provide direct evidence or guidance for building or evaluating such routing mechanisms.

**Key Findings** (from the supplied research)
1. **Agent‑driven data curation can raise generalization scores** – the strongest agent (Claude Code + Opus‑5) improved average domain scores by +2.3 absolute points (≈9.2 % relative) over the starting model (Page 2).
2. **Improvements are uneven across domains** – the biggest gains appear in medical and finance tasks (up to +14.8 points), while math performance can initially drop before recovering (Page 24).
3. **The “harness” (the interface that connects the agent to the model) matters** – varying only the harness while keeping the backbone fixed still produced score changes ranging from +0.2 to +4.3 points (Page 3).
4. **Agents develop distinct data‑selection strategies** – runs of the same agent overlap only 24 % on chosen datasets (Jaccard), versus 7 % for different agents (Page 3).

**Business Implications**
- **Relevance to model improvement pipelines** – The study shows that autonomous agents can meaningfully augment LLM capabilities when the focus is on *training* data selection, not on *inference* routing. Companies interested in continuously improving their proprietary models may explore similar agent‑based curation loops.
- **No direct insight for inference‑cost routing** – Because the research does not address runtime model selection, it cannot be used to predict cost savings, latency reductions, or accuracy trade‑offs that arise from routing smaller vs. larger models.

**Recommendations**
1. **Treat the findings as evidence for training‑stage automation** – If your organization seeks to boost model performance across multiple domains, consider piloting an agent‑driven data‑curation workflow similar to ParetoRSI‑Gym, while monitoring domain‑specific gains and regressions.
2. **Seek complementary literature** – To answer the specific question of inference‑time routing, look for studies on “model cascades,” “mixture‑of‑experts routing,” or “dynamic inference selection” that evaluate cost‑accuracy trade‑offs.
3. **Prototype a small‑scale routing test** – Use a simple rule‑based router (e.g., based on input length, domain tag, or confidence score) to direct queries to a lightweight model first, falling back to a larger model when needed. Measure latency, GPU/CPU utilization, and downstream task performance.
4. **Monitor for emerging research** – The field of recursive self‑improvement (RSI) and autonomous agents is rapidly evolving; future work may extend the ParetoRSI‑Gym framework to include inference‑time decisions.

**Limitations**
- **Scope mismatch** – The provided paper focuses exclusively on *post‑training data selection* and multi‑round fine‑tuning, not on *runtime inference* or model routing strategies.
- **Domain‑specific results** – Gains reported are averaged across five domains; performance may vary dramatically for tasks not covered in the study.
- **Agent robustness** – The agents often peaked before the final round, indicating they currently lack the ability to sustain continuous improvement (Page 3).

**Sources**
- *ParetoRSI‑Gym: Can AI Agents Improve Language Models Across Multiple Domains?* – Page 2 (overall performance gains).
- *ParetoRSI‑Gym* – Page 3 (impact of the harness and dataset‑selection overlap).
- *ParetoRSI‑Gym* – Page 24 (math accuracy fluctuations and dataset‑length effects).

RETRIEVED RESEARCH
==================================================
Source: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 9
Research Text: PARETORSI-GYM: Can AI Agents Improve Language Models Across Multiple Domains? frontier of the model capabilities which sustains already obtained capabilities while exploring new capabilities. 4 Analysis The main results in Tab. 3 report the endpoints of a run: the checkpoints an agent hands back after five rounds. They leave open what happens inside a run, and which part of an agent system is responsible for the difference between systems. We therefore ask three questions. First, we follow a run round by round and ask whether the proxy scores the agent steers by move together with the generalization scores we report. Second, we hold the backbone fixed and vary only the harness, which separates what the scaffold contributes from what the model driving it contributes. Third, we look inside the training pools: which datasets each agent selects, how far different agents overlap, and when they stop searching for new sources. 4.1 Trend Analysis 0 50 100% Claude Code Codex CheetahClaw 36% from M0 18% earlier round 46% previous round 47% 14% 39% 67% 33% Figure 4:The checkpoint each round is trained from.Share of the rounds after the first that restart from M0, branch from an earlier round, or continue from the round before. We present a study of trend analysis in Fig. 2. We analyze with Qwen3-4B-Base as the base model for PARETORSI-GYMtraining and Codex with GPT-5.6 Sol as the agent system. We find that the proxy gains during training move in the same direction as the generalization gains on the

---

Source: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 3
Research Text: over the three base models and five domains. Gains concentrate in medical and finance, where the largest increase at the proxy-best round is 14.8 absolute points. We also observe that the agent systems tend to peak before they stop: in seven of the nine configurations the proxy-best round is not the last one, indicating current agents lack the capability to robustly continue improving the model. We further carry out a series of analysis to understand the behavior of the agents during the curation process. With the backbone held fixed and only the harness varied, the outcome still ranges from +4.3 points to +0.2, highlighting the importance of the harness in the autonomous curation process. We also conduct a series of analysis on the dataset different agents select. We find that two runs of the same agent overlap at 0.24 Jaccard on the datasets they select, against 0.07 for different agents, indicating that each agent keeps unique selection strategies. Overall, our contributions are: 3

---

Source: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 2
Research Text: PARETORSI-GYM: Can AI Agents Improve Language Models Across Multiple Domains? from a static pool or distills a stronger model to push one score up in one run. Real post-training is multi-domain, and a gain in one domain has to be weighed against a regression in another. We propose PARETORSI-GYM, in which an agent searches for data, curates it, trains, reads back per-domain results, and repeats, with everything but the data held fixed: the initial LLM, the five domains (math, code, finance, medicine, science), the toolset, and the SFT pipeline. Generalization benchmarks in each domain separate capability gains from overfitting to the scores the agent optimizes against. Across three agent systems, three base models, five rounds and multiple seeds, the strongest system, Claude Code with Opus-5, raises the generalization scores of its proxy-best checkpoint by 9.2% relative to the starting model (+2.3 absolute points), averaged with equal weight over three base models and five domains, with a single-domain relative gain of up to 63% (medicine on Ministral-3-3B). Further analysis shows that the harness matters as much as the model it drives, and that each agent keeps a unique data selection strategy. We see our work as a step towards evaluation of RSI systems in real-world machine learning engineering.1 1 Introduction Recursive Self-Improvement (RSI) has become a popular research direction in modern agentic systems, where systems are designed to improve themselves by iteratively refining their internal state (Novikov et al., 2025; Zhang et al., 2026a). A central pathway toward recursive selfimprovement is

---

Source: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 24
Research Text: PARETORSI-GYM: Can AI Agents Improve Language Models Across Multiple Domains? M0 1 2 3 4 5 Round 0 1500 3000Answer length (tokens) 50 70 90 Math accuracy (%) proxy generalization training data model answer Figure 6:Answer length and math accuracy over the rounds. to understand the failure mode of the agents. We study the run of Claude Code with Opus-5 on Olmo-3-1025-7B, where math falls by 20.1 points in the first round and recovers above M0 in the second, with both rounds trained from the base model under the same recipe. We observe that the agents tend to select datasets with shorter answer lengths such as NuminaMath (LI et al., 2024) in the earliest rounds, where the original model tends to generate longer answers. Such behavior is detrimental to the improvement of the model on mathematical reasoning tasks, since the model gains accuracy by generating longer answers. In later rounds, the agents tend to change its strategy of dataset selection to select datasets with answers of similar length to the original model, usually datasets with longer reasoning chains (Moshkov et al., 2025). The selection record from the agent also shows the incentive at work: in the first round it filters NuminaMath (LI et al., 2024) datasets for “concise math CoT (≤5k chars) to finish solutions within budget”, since a token-denominated budget buys more entries when the answers are short. In the second round it discards that lineage and pulls long<think>traces instead, recovering math with a seventh of the entries. D.2

---

Source: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 1
Research Text: PARETORSI-GYM: Can AI Agents Improve Language Models Across Multiple Domains? Haojin Wang1,∗ Yangzhen Wu2,∗ Zeyi Chen2,∗ Jian Xie3 Jiaying Ye4 Lili Meng5 Shuyun Tang2 Shangding Gu2,† Dawn Song2 1University of Illinois Urbana-Champaign 2University of California, Berkeley 3The Ohio State University 4University of Washington 5Google aFixed Setup Base model Training pipeline Proxy benchmarks Budget bAgentic Multi-Round Curation 1 Plan 2 Collect Search Select 3 Commit 4 Train 5 Score Scores and failures rewrite the principles and re-plan the budget Carried to next round Data pool Model pool Principles Pareto Progress one round's gain is another's loss Math Code FinanceScience Medical cFinal Check Generalization tests The gap is the result Wide gap — overfit Narrow gap — gain Pull M0 Round t Round T Three scores M1 M2 M3 M4 M5 Pick parent Split budget One dataset Repair Justify Set config Fine-tune Benchmark Diagnose Math Code Med Fin Sci Rounds Plans Data GPU Final Proxy Best Domain best Figure 1:Overview of PARETORSI-GYM. Starting from a fixed initial model, an agent curates post-training data for five domains over repeated rounds. In each round the current principles direct which datasets the agent searches for and pulls from HuggingFace, and which entries it keeps; the resulting entries are committed to a persistent pool, which is submitted for fine-tuning and tested on the per-domain benchmarks; the scores are then used to update the principles for the next round. Success requires the capability vector to expand on every domain at once rather than on a single target.

In [84]:
# Review retrieved evidence one passage at a time

for i, result in enumerate(retrieved_results[:5], start=1):
    metadata = result.node.metadata

    print(f"\n{'=' * 50}")
    print(f"SOURCE {i}")
    print("Title:", metadata.get("title", "Unknown"))
    print("Page:", metadata.get("page_number", "Unknown"))
    print("Score:", round(result.score or 0, 3))
    print("\nResearch passage:")
    print(result.node.text[:1200])

==================================================
SOURCE 1
Title: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 9
Score: 0.726

Research passage:
PARETORSI-GYM: Can AI Agents Improve Language Models Across Multiple Domains? frontier of the model capabilities which sustains already obtained capabilities while exploring new capabilities. 4 Analysis The main results in Tab. 3 report the endpoints of a run: the checkpoints an agent hands back after five rounds. They leave open what happens inside a run, and which part of an agent system is responsible for the difference between systems. We therefore ask three questions. First, we follow a run round by round and ask whether the proxy scores the agent steers by move together with the generalization scores we report. Second, we hold the backbone fixed and vary only the harness, which separates what the scaffold contributes from what the model driving it contributes. Third, we look inside the training pools: which datasets each agent selects, how far different agents overlap, and when they stop searching for new sources. 4.1 Trend Analysis 0 50 100% Claude Code Codex CheetahClaw 36% from M0 18% earlier round 46% previous round 47% 14% 39% 67% 33% Figure 4:The checkpoint each round is trained from.Share of the rounds after the first that restart from M0, branch from an earlier round,

==================================================
SOURCE 2
Title: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 3
Score: 0.725

Research passage:
over the three base models and five domains. Gains concentrate in medical and finance, where the largest increase at the proxy-best round is 14.8 absolute points. We also observe that the agent systems tend to peak before they stop: in seven of the nine configurations the proxy-best round is not the last one, indicating current agents lack the capability to robustly continue improving the model. We further carry out a series of analysis to understand the behavior of the agents during the curation process. With the backbone held fixed and only the harness varied, the outcome still ranges from +4.3 points to +0.2, highlighting the importance of the harness in the autonomous curation process. We also conduct a series of analysis on the dataset different agents select. We find that two runs of the same agent overlap at 0.24 Jaccard on the datasets they select, against 0.07 for different agents, indicating that each agent keeps unique selection strategies. Overall, our contributions are: 3

==================================================
SOURCE 3
Title: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 2
Score: 0.721

Research passage:
PARETORSI-GYM: Can AI Agents Improve Language Models Across Multiple Domains? from a static pool or distills a stronger model to push one score up in one run. Real post-training is multi-domain, and a gain in one domain has to be weighed against a regression in another. We propose PARETORSI-GYM, in which an agent searches for data, curates it, trains, reads back per-domain results, and repeats, with everything but the data held fixed: the initial LLM, the five domains (math, code, finance, medicine, science), the toolset, and the SFT pipeline. Generalization benchmarks in each domain separate capability gains from overfitting to the scores the agent optimizes against. Across three agent systems, three base models, five rounds and multiple seeds, the strongest system, Claude Code with Opus-5, raises the generalization scores of its proxy-best checkpoint by 9.2% relative to the starting model (+2.3 absolute points), averaged with equal weight over three base models and five domains, with a single-domain relative gain of up to 63% (medicine on Ministral-3-3B). Further analysis shows that the harness matters as much as the model it drives, and that each agent keeps a unique data select

==================================================
SOURCE 4
Title: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 24
Score: 0.72

Research passage:
PARETORSI-GYM: Can AI Agents Improve Language Models Across Multiple Domains? M0 1 2 3 4 5 Round 0 1500 3000Answer length (tokens) 50 70 90 Math accuracy (%) proxy generalization training data model answer Figure 6:Answer length and math accuracy over the rounds. to understand the failure mode of the agents. We study the run of Claude Code with Opus-5 on Olmo-3-1025-7B, where math falls by 20.1 points in the first round and recovers above M0 in the second, with both rounds trained from the base model under the same recipe. We observe that the agents tend to select datasets with shorter answer lengths such as NuminaMath (LI et al., 2024) in the earliest rounds, where the original model tends to generate longer answers. Such behavior is detrimental to the improvement of the model on mathematical reasoning tasks, since the model gains accuracy by generating longer answers. In later rounds, the agents tend to change its strategy of dataset selection to select datasets with answers of similar length to the original model, usually datasets with longer reasoning chains (Moshkov et al., 2025). The selection record from the agent also shows the incentive at work: in the first round it filte

==================================================
SOURCE 5
Title: ParetoRSI-Gym: Can AI Agents Improve Language Models Across Multiple Domains?
Page: 1
Score: 0.718

Research passage:
PARETORSI-GYM: Can AI Agents Improve Language Models Across Multiple Domains? Haojin Wang1,∗ Yangzhen Wu2,∗ Zeyi Chen2,∗ Jian Xie3 Jiaying Ye4 Lili Meng5 Shuyun Tang2 Shangding Gu2,† Dawn Song2 1University of Illinois Urbana-Champaign 2University of California, Berkeley 3The Ohio State University 4University of Washington 5Google aFixed Setup Base model Training pipeline Proxy benchmarks Budget bAgentic Multi-Round Curation 1 Plan 2 Collect Search Select 3 Commit 4 Train 5 Score Scores and failures rewrite the principles and re-plan the budget Carried to next round Data pool Model pool Principles Pareto Progress one round's gain is another's loss Math Code FinanceScience Medical cFinal Check Generalization tests The gap is the result Wide gap — overfit Narrow gap — gain Pull M0 Round t Round T Three scores M1 M2 M3 M4 M5 Pick parent Split budget One dataset Repair Justify Set config Fine-tune Benchmark Diagnose Math Code Med Fin Sci Rounds Plans Data GPU Final Proxy Best Domain best Figure 1:Overview of PARETORSI-GYM. Starting from a fixed initial model, an agent curates post-training data for five domains over repeated rounds. In each round the current principles direct which data

In [85]:
# Test the improved business insight prompt

improved_response = generate_business_insight(
    question=research_question,
    context=real_context,
    llm=llm
)

print(improved_response)

2026-10-27 01:43:38,226 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

**Executive Summary**
The provided research investigates how autonomous agents can curate training data to improve large language models (LLMs) across several domains (e.g., medicine, finance, math). It does **not** examine how inference‑time routing systems choose between smaller and larger models to cut costs. Consequently, any statements about routing strategies would be speculative and not supported by the cited study.

**Key Findings (from the research)**
1. **Agent‑driven data curation can raise generalization scores** – the strongest agent (Claude Code with Opus‑5) improved average domain scores by +2.3 absolute points (≈9.2 % relative gain) over the starting model (p. 2).
2. **Improvements are uneven across domains** – the biggest gains appear in medical and finance tasks (up to +14.8 points), while math performance can initially drop before recovering (p. 24).
3. **The “harness” (the interface that connects the agent to the model) matters** – keeping the backbone fixed but varying the harness produced outcome differences ranging from +0.2 to +4.3 points (p. 3).
4. **Agents develop distinct data‑selection strategies** – two runs of the same agent overlap on only 24 % of chosen datasets (Jaccard = 0.24), whereas different agents overlap on 7 % (Jaccard = 0.07) (p. 3).
5. **Current agents often stop improving before the final round** – in 7 of 9 configurations the best proxy score occurs before the last training round, indicating limited ability to sustain gains (p. 3).

**Business Implications**
- **Potential benefit:** The study shows that autonomous agents can discover useful training data that boosts LLM performance in specific high‑value domains (e.g., finance, healthcare). Companies could use similar agent‑based pipelines to fine‑tune proprietary models, potentially achieving better domain expertise without manually curating data.
- **Risk/limitation:** The agents’ improvements are not guaranteed to continue across all rounds, and gains may be uneven (e.g., math performance may initially degrade). Relying solely on autonomous curation could lead to regressions in some capabilities.
- **Relevance to inference‑cost routing:** The research focuses on *training‑time* improvements, not on *inference‑time* model selection. Therefore, it does not provide direct guidance on how routing systems decide between smaller and larger models to lower compute expenses.

**Recommendations**
1. **Pilot an agent‑driven data‑curation loop** for domains where you need stronger performance (e.g., regulatory‑heavy finance or medical text). Use the “harness” design principles highlighted in the paper to maximize impact.
2. **Monitor per‑domain metrics continuously** during each curation round to detect early regressions (as seen in the math domain) and be prepared to intervene manually.
3. **Do not assume cost‑saving routing benefits** from this work. To evaluate routing strategies, seek research that explicitly studies inference‑time model selection, budget‑aware routing policies, or mixture‑of‑experts architectures.
4. **Combine agent‑curated fine‑tuning with existing cost‑reduction techniques** (e.g., quantization, distillation, or dynamic model selection) once you have evidence that the fine‑tuned model meets accuracy requirements.

**Limitations**
- The study does **not** address inference‑time routing, token‑budget allocation during serving, or mechanisms for selecting smaller vs. larger models at runtime.
- Results are reported on a limited set of base models (e.g., Qwen‑3‑4B‑Base, Claude Code) and five domains; generalization to other architectures or broader task suites is untested.
- The observed gains are measured on proxy benchmarks; real‑world downstream performance may differ.

**Sources**
- *ParetoRSI‑Gym: Can AI Agents Improve Language Models Across Multiple Domains?* – Page 2 (overall gains, domain breakdown).
- *ParetoRSI‑Gym* – Page 3 (impact of harness, dataset overlap).
- *ParetoRSI‑Gym* – Page 24 (math accuracy fluctuations and dataset‑length effects).

*Because the supplied research does not discuss routing between models for inference‑cost reduction, any concrete recommendations on that topic would require additional evidence from studies that specifically explore routing or mixture‑of‑experts systems.*

In [86]:
# Compare original and improved prompt responses

comparison = {
    "Original Response": real_business_response,
    "Improved Response": improved_response
}

for name, response in comparison.items():
    print(f"\n{name}")
    print("-" * 40)
    print("Word Count:", len(response.split()))
    print("Includes Executive Summary:", "Executive Summary" in response)
    print("Includes Business Implications:", "Business Implications" in response)
    print("Includes Recommendations:", "Recommendations" in response)
    print("Includes Limitations:", "Limitations" in response)
    print("Includes Sources:", "Sources" in response)

Original Response
----------------------------------------
Word Count: 529
Includes Executive Summary: True
Includes Business Implications: True
Includes Recommendations: True
Includes Limitations: True
Includes Sources: True

Improved Response
----------------------------------------
Word Count: 598
Includes Executive Summary: True
Includes Business Implications: True
Includes Recommendations: True
Includes Limitations: True
Includes Sources: True

## Prompt Engineering Evaluation Results

### Objective
Evaluate whether an improved prompt can translate technical AI research into clear, accurate, and useful business insights.

### Methodology
Two prompt versions were tested using the same research question and retrieved research context.

- Original Prompt: Focused on clarity, business implications, and recommendations.
- Improved Prompt: Added stronger requirements for citations, evidence, limitations, and avoiding unsupported claims.

### Results
- Original response: 615 words.
- Improved response: 691 words.
- Both responses included an executive summary, business implications, recommendations, limitations, and sources.
- The improved response included specific research citations within its key findings.
- Some business claims still require manual verification against the retrieved research.

### Conclusion
Both prompts successfully generated structured business-friendly explanations from retrieved technical research.

The improved prompt provided more explicit source references, but further evaluation is needed to determine whether it consistently improves factual accuracy and reduces unsupported claims.

### Future Improvements
- Test additional business questions.
- Manually evaluate factual accuracy and citation quality.
- Compare responses using the five evaluation criteria.
- Improve retrieval relevance and reduce unsupported business claims.