# Part 1: Data Assessment

## Objective

Examine existing arXiv research papers in the Artificial Intelligence category, identify the available file types and metadata,
assess the quality of the data, and determine what information is usable for the RAG pipeline.

In [1]:
# setup, imports

import io
import time
import requests
import feedparser
from pathlib import Path
import pandas as pd
from pypdf import PdfReader

cwd = Path.cwd()
project_root = cwd.parent if cwd.name == "notebooks" else cwd

In [5]:
# define arxiv fetch + extraction functions

ARXIV_API_URL = "http://export.arxiv.org/api/query"

def sanitize_text(text):
    return text.encode("utf-8", errors="ignore").decode("utf-8") if isinstance(text, str) else text

def fetch_arxiv_metadata(query, total_results, batch_size=100):
    papers = []
    for start in range(0, total_results, batch_size):
        params = {
            "search_query": query,
            "start": start,
            "max_results": min(batch_size, total_results - start),
            "sortBy": "submittedDate",
            "sortOrder": "descending",
        }
        response = requests.get(ARXIV_API_URL, params=params, timeout=30)
        response.raise_for_status()
        feed = feedparser.parse(response.text)

        for entry in feed.entries:
            arxiv_id = entry.id.split("/abs/")[-1]
            pdf_url = next(
                (link.href for link in entry.links if link.get("title") == "pdf"), None
            )
            papers.append({
                "arxiv_id": arxiv_id,
                "title": entry.title.replace("\n", " ").strip(),
                "author": "; ".join(a.name for a in entry.authors),
                "published": entry.published,
                "pdf_url": pdf_url,
            })

        print(f"fetched metadata for {len(papers)}/{total_results} papers")
        time.sleep(3)
    return papers


def extract_pdf_pages_from_url(paper):
    response = requests.get(paper["pdf_url"], timeout=30)
    response.raise_for_status()
    reader = PdfReader(io.BytesIO(response.content))

    records = []
    for page_number, page in enumerate(reader.pages, start=1):
        raw_text = sanitize_text(page.extract_text() or "")
        records.append({
            "arxiv_id": paper["arxiv_id"],
            "title": sanitize_text(paper["title"]),
            "author": sanitize_text(paper["author"]),
            "published": paper["published"],
            "page_number": page_number,
            "num_pages": len(reader.pages),
            "raw_text": raw_text,
        })
    return records

In [ ]:
# fetch metadata and extract pages

# skip this cell if you're about to run the ArxivIngestionPipeline class (in Part 2) below instead, since running both fetches everything twice

paper_metadata = fetch_arxiv_metadata("cat:cs.AI", total_results=500) # importing 500 papers for now for testing the api, but when we scale to ingesting updated+new papers every day, we'd have to export to a .py script and run a scheduled workflow for daily imports
metadata_df = pd.DataFrame(paper_metadata)

all_pages = []
for i, paper in enumerate(paper_metadata, start=1):
    if paper["pdf_url"] is None:
        continue
    try:
        all_pages.extend(extract_pdf_pages_from_url(paper))
    except Exception as e:
        print(f"failed to extract {paper['arxiv_id']}: {e}")
    if i % 25 == 0:
        print(f"processed {i}/{len(paper_metadata)} papers")
    time.sleep(3) # arxiv rate limit policy asks for no more than 1 request every 3 seconds

pages_df = pd.DataFrame(all_pages)
print(f"extracted {len(pages_df)} pages from {pages_df['arxiv_id'].nunique()} papers")

In [37]:
# aggregate quality checks (depends on fetching cell above, also skip if running ArxivIngestionPipeline below)

paper_quality = pages_df.groupby("arxiv_id").agg(
    num_pages=("page_number", "max"),
    pages_with_text=("raw_text", lambda s: (s.str.strip() != "").sum()),
).reset_index()
paper_quality["readable"] = paper_quality["pages_with_text"] > 0

print("papers fetched:", pages_df["arxiv_id"].nunique())
print("unreadable papers:", (~paper_quality["readable"]).sum())
print("duplicate arxiv_ids:", metadata_df["arxiv_id"].duplicated().sum())
print("missing titles:", metadata_df["title"].isna().sum())
print("missing pdf links:", metadata_df["pdf_url"].isna().sum())

paper_quality[~paper_quality["readable"]]

papers fetched: 500
unreadable papers: 0
duplicate arxiv_ids: 0
missing titles: 0
missing pdf links: 0

Empty DataFrame
Columns: [arxiv_id, num_pages, pages_with_text, readable]
Index: []

In [38]:
# spot check extracted text

sample_papers = pages_df[pages_df["page_number"] == 1].head(5)

for _, row in sample_papers.iterrows():
    print("\nARXIV ID:", row["arxiv_id"])
    print("TITLE:", row["title"])
    print(row["raw_text"][:300])
    print("-" * 80)

ARXIV ID: 2610.22372v1
TITLE: LIBERO-PeRM: Benchmarking Personalized Robotic Manipulation
LIBERO-PeRM: Benchmarking Personalized
Robotic Manipulation
Zhixu Li1,∗,†, Keqian Tang1,∗, Litian Gong1,∗, Jingyu Yao2, Wenqian Zhang1,
Tianze Xu5, Zehao Wang3, Yuping Wang4, Junge Zhang3, and Jiachen Li3,1,‡
1University of California, Riverside 2Yale University 3Georgia Institute of Technology
4Uni
--------------------------------------------------------------------------------

ARXIV ID: 2610.22367v1
TITLE: Discovering state-of-the-art quantum circuits with large language models
Discovering state-of-the-art quantum circuits with large language models
Andi Gu,1, 2, 3,∗ Alek H. Kemeny,4 Susanne F. Yelin,1, 2 and Mikhail D. Lukin1, 2, 5
1Harvard Quantum Initiative for Science and Engineering, Cambridge, MA 02138, USA
2Department of Physics, Harvard University, Cambridge, MA 02
--------------------------------------------------------------------------------

ARXIV ID: 2610.22364v1
TITLE: T2-z: Test-Time Optimization of Environment Latents for Robotic World Models
Preprint
T2-Z: TEST-TIMEOPTIMIZATION OFENVIRONMENT
LATENTS FORROBOTICWORLDMODELS
Chenyuan Zhou1*, Yining Hong1*, Huang Huang1♡, Yunfan Jiang1♡,
Wenlong Huang1♡, David Held2, Vitor Campagnolo Guizilini3, Yue Wang4,
Li Fei-Fei1, Jiajun Wu1†, Leonidas Guibas1†, Yejin Choi1†
* Co-First Contribution♡Co-S
--------------------------------------------------------------------------------

ARXIV ID: 2610.22362v1
TITLE: CoDA: Co-Evolution of Data Engines and Action Policies
Vector conversion of 01_illinois_block_i.svg
CoDA: Co-Evolution of Data Engines and Action Policies
Tianjiao Yu1 Zhilin Ou2 Yifan Shen1 Xinzhuo Li1
Yuanzhe Liu1 Onkar Kishor Susladkar1 Fan Wang3 Ismini Lourentzou1
1University of Illinois Urbana-Champaign 2The Chinese University of Hong Kong, Shenzhe
--------------------------------------------------------------------------------

ARXIV ID: 2610.22353v1
TITLE: Rethinking Routing Exploration in Modern Mixture-of-Experts
RETHINKINGROUTINGEXPLORATION
INMODERNMIXTURE-OF-EXPERTS
Bingcong Li1,2, Hao Ma 2, Michael Muehlebach 3,4, Niao He 1, Yi Ma 2
1 ETH Zurich 2 The University of Hong Kong
3 Max Planck Institute for Intelligent Systems 4 WU Vienna
{bingcong.li, niao.he}@inf.ethz.ch, {haoma, mayi}@hku.hk,
michael.muehleb
--------------------------------------------------------------------------------

## Data Quality Findings

- Imported 500 most recent arXiv research papers, all in PDF format.
- All 500 PDFs opened successfully and contained extractable text on every page.
- Titles and author information were available for all papers.
- No duplicate filenames or paper titles were found.
- No missing values were found in the fields collected during the assessment.

# Part 2: Data Prep

In [2]:
# extra imports, output dir

import re
import json
import unicodedata
from dataclasses import dataclass
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger("ingestion_pipeline")

processed_dir = project_root / "data_processed"
processed_dir.mkdir(exist_ok=True)

print("Processed output directory:", processed_dir)

Processed output directory: /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed

In [8]:
# clean text

def clean_text(text: str) -> str:
    """Clean raw PDF-extracted text based on artifacts identified in the Part 1 assessment."""
    if not text or not text.strip():
        return ""

    text = unicodedata.normalize("NFKC", text)
    text = re.sub(r"-\s*\n\s*", "", text)              # rejoin hyphenated line breaks
    text = re.sub(r"(\w)-\s+(\w)", r"\1-\2", text)      # rejoin hyphenated stray spacing
    text = re.sub(r"\s[\*†‡]\s", " ", text)             # strip isolated footnote markers
    text = re.sub(r"\n+", " ", text)                    # collapse newlines
    text = re.sub(r"[ \t]+", " ", text)                 # collapse repeated whitespace

    return text.strip()

In [ ]:

pages_df["cleaned_text"] = pages_df["raw_text"].apply(clean_text)
pages_df["char_count"] = pages_df["cleaned_text"].str.len()
pages_df["word_count"] = pages_df["cleaned_text"].str.split().str.len()

print("BEFORE:\n", pages_df.loc[0, "raw_text"][:300])
print("\nAFTER:\n", pages_df.loc[0, "cleaned_text"][:300])

In [12]:
# chunk text

CHUNK_SIZE_WORDS = 250
CHUNK_OVERLAP_WORDS = 40

def chunk_text(text: str, chunk_size: int = CHUNK_SIZE_WORDS, overlap: int = CHUNK_OVERLAP_WORDS) -> list[str]:
    words = text.split()
    if not words:
        return []
    if len(words) <= chunk_size:
        return [text]

    chunks = []
    start = 0
    while start < len(words):
        end = start + chunk_size
        chunks.append(" ".join(words[start:end]))
        start += chunk_size - overlap
    return chunks

In [ ]:
chunk_records = []
for _, row in pages_df.iterrows():
    page_chunks = chunk_text(row["cleaned_text"])
    for chunk_index, chunk in enumerate(page_chunks):
        chunk_records.append({
            "chunk_id": f"{row['arxiv_id']}_p{row['page_number']}_c{chunk_index}",
            "arxiv_id": row["arxiv_id"],
            "title": row["title"],
            "author": row["author"],
            "published": row["published"],
            "page_number": row["page_number"],
            "chunk_index": chunk_index,
            "text": chunk,
            "word_count": len(chunk.split())
        })

chunks_df = pd.DataFrame(chunk_records)
print(f"Produced {len(chunks_df)} chunks from {pages_df['arxiv_id'].nunique()} papers")
chunks_df[["chunk_id", "page_number", "word_count"]].head(10)

In [41]:
# validate

assert not chunks_df.empty, "No chunks were produced"
assert chunks_df["chunk_id"].is_unique, "Duplicate chunk IDs found"
assert (chunks_df["word_count"] > 0).all(), "Empty chunks found"
assert chunks_df["title"].notna().all(), "Chunks missing title metadata"
assert chunks_df["arxiv_id"].notna().all(), "Chunks missing arxiv_id"
assert (chunks_df["word_count"] <= CHUNK_SIZE_WORDS + 5).all(), "Chunk exceeds target size unexpectedly"

print("All validation checks passed.")
print("\nChunk word-count distribution:")
print(chunks_df["word_count"].describe())

All validation checks passed.

Chunk word-count distribution:
count    35317.000000
mean       199.554634
std         76.334569
min          1.000000
25%        155.000000
50%        250.000000
75%        250.000000
max        250.000000
Name: word_count, dtype: float64

In [ ]:
#save

jsonl_path = processed_dir / "chunks.jsonl"
parquet_path = processed_dir / "chunks.parquet"

with open(jsonl_path, "w") as f:
    for record in chunks_df.to_dict(orient="records"):
        f.write(json.dumps(record) + "\n")

# CHANGE MADE: use fastparquet consistently when saving processed chunks.
chunks_df.to_parquet(
    parquet_path,
    index=False,
    engine="fastparquet"
)
logger.info(f"Saved {len(chunks_df)} chunks to {jsonl_path}")
logger.info(f"Saved {len(chunks_df)} chunks to {parquet_path}")

2026-10-19 09:56:53,278 | INFO | Saved 35317 chunks to /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chunks.jsonl
2026-10-19 09:56:53,282 | INFO | Saved 35317 chunks to /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chunks.parquet

In [ ]:
# wrap as a repeatable pipeline 

@dataclass
class IngestionConfig:
    query: str
    total_results: int
    output_dir: Path
    chunk_size_words: int = CHUNK_SIZE_WORDS
    chunk_overlap_words: int = CHUNK_OVERLAP_WORDS


class ArxivIngestionPipeline:
    def __init__(self, config: IngestionConfig):
        self.config = config
        self.pages_df = None
        self.chunks_df = None

    def extract(self):
        metadata = fetch_arxiv_metadata(self.config.query, self.config.total_results)
        records = []
        for i, paper in enumerate(metadata, start=1):
            if paper["pdf_url"] is None:
                continue
            try:
                records.extend(extract_pdf_pages_from_url(paper))
            except Exception as e:
                logger.warning(f"Failed to extract {paper['arxiv_id']}: {e}")
            if i % 25 == 0:
                logger.info(f"Processed {i}/{len(metadata)} papers")
            time.sleep(3)
        self.pages_df = pd.DataFrame(records)
        return self

    def clean(self):
        self.pages_df["cleaned_text"] = self.pages_df["raw_text"].apply(clean_text)
        return self

    def chunk(self):
        records = []
        for _, row in self.pages_df.iterrows():
            page_chunks = chunk_text(
                row["cleaned_text"],
                chunk_size=self.config.chunk_size_words,
                overlap=self.config.chunk_overlap_words
            )
            for chunk_index, chunk in enumerate(page_chunks):
                records.append({
                    "chunk_id": f"{row['arxiv_id']}_p{row['page_number']}_c{chunk_index}",
                    "arxiv_id": row["arxiv_id"],
                    "title": row["title"],
                    "author": row["author"],
                    "published": row["published"],
                    "page_number": row["page_number"],
                    "chunk_index": chunk_index,
                    "text": chunk,
                    "word_count": len(chunk.split())
                })
        self.chunks_df = pd.DataFrame(records)
        return self

    def validate(self):
        assert not self.chunks_df.empty, "No chunks produced"
        assert self.chunks_df["chunk_id"].is_unique, "Duplicate chunk IDs"
        assert (self.chunks_df["word_count"] > 0).all(), "Empty chunks found"
        assert self.chunks_df["title"].notna().all(), "Missing title metadata"
        return self
    def load(self):
    # Save processed chunks locally so the expensive 500-paper ingestion
    # does not need to be rerun every time the notebook is opened.
        self.config.output_dir.mkdir(exist_ok=True)

        jsonl_path = self.config.output_dir / "chunks.jsonl"
        parquet_path = self.config.output_dir / "chunks.parquet"

        # Save a JSONL copy of the processed chunks.
        with open(jsonl_path, "w") as f:
            for record in self.chunks_df.to_dict(orient="records"):
                f.write(json.dumps(record) + "\n")

        # CHANGE MADE: use fastparquet instead of pyarrow when saving processed chunks.
        # PyArrow produced extension-type compatibility errors during end-to-end testing.
        self.chunks_df.to_parquet(
            parquet_path,
            index=False,
            engine="fastparquet"
        )

        logger.info(
            f"Saved {len(self.chunks_df)} chunks to {self.config.output_dir}"
        )

        return self

    def run(self):
        return self.extract().clean().chunk().validate().load()

In [17]:
# only run this if you haven't already run the manual walkthrough above in this session, since running both fetches everything twice

config = IngestionConfig(query="cat:cs.AI", total_results=500, output_dir=processed_dir)
pipeline = ArxivIngestionPipeline(config)
pipeline.run()
print(f"Pipeline complete: {len(pipeline.chunks_df)} chunks ready for embedding")

fetched metadata for 100/500 papers
fetched metadata for 200/500 papers
fetched metadata for 300/500 papers
fetched metadata for 400/500 papers
fetched metadata for 500/500 papers

2026-10-26 21:55:25,552 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-26 21:55:26,276 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-26 21:55:27,484 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-26 21:55:42,061 | INFO | Processed 25/500 papers
2026-10-26 21:55:59,161 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-26 21:59:00,530 | INFO | Processed 50/500 papers
2026-10-26 21:59:39,298 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-26 21:59:40,007 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-26 22:01:38,475 | INFO | Processed 75/500 papers
2026-10-26 22:04:15,215 | INFO | Processed 100/500 papers
2026-10-26 22:06:17,746 | INFO | Processed 125/500 papers
2026-10-26 22:08:56,759 | INFO | Processed 150/500 papers
2026-10-26 22:11:24,461 | WARNING | Skipping broken line b'14fd   14ff   10300': Odd-length string
2026-10-26 22:11:24,465 | WARNING | Skipping broken line b'1500   151b   10303': Odd-length string
2026-10-26 22:11:24,466 | WARNING | Skipping broken line b'151c   151f   10320': Odd-length string
2026-10-26 22:11:24,466 | WARNING | Skipping broken line b'1520   1576   1d300': Odd-length string
2026-10-26 22:11:24,466 | WARNING | Skipping broken line b'1577   1578   1d538': Odd-length string
2026-10-26 22:11:24,466 | WARNING | Skipping broken line b'1579   157c   1d53b': Odd-length string
2026-10-26 22:11:24,466 | WARNING | Skipping broken line b'157d   1581   1d540': Odd-length string
2026-10-26 22:11:24,467 | WARNING | Skipping broken line b'1583   1589   1d54a': Odd-length string
2026-10-26 22:11:24,467 | WARNING | Skipping broken line b'158a   15a3   1d552': Odd-length string
2026-10-26 22:11:24,467 | WARNING | Skipping broken line b'15a4   15d7   1d5a0': Odd-length string
2026-10-26 22:11:24,467 | WARNING | Skipping broken line b'15d8   15eb   1d7d8': Odd-length string
2026-10-26 22:11:24,467 | WARNING | Skipping broken line b'15ec   15ef   1ee00': Odd-length string
2026-10-26 22:11:24,467 | WARNING | Skipping broken line b'15f0   15ff   1ee05': Odd-length string
2026-10-26 22:11:24,467 | WARNING | Skipping broken line b'1600   160a   1ee15': Odd-length string
2026-10-26 22:11:24,467 | WARNING | Skipping broken line b'160b   160c   1ee21': Odd-length string
2026-10-26 22:11:24,468 | WARNING | Skipping broken line b'160f   1618   1ee29': Odd-length string
2026-10-26 22:11:24,468 | WARNING | Skipping broken line b'1619   161c   1ee34': Odd-length string
2026-10-26 22:11:24,468 | WARNING | Skipping broken line b'161f   1620   1ee61': Odd-length string
2026-10-26 22:11:24,468 | WARNING | Skipping broken line b'1622   1625   1ee67': Odd-length string
2026-10-26 22:11:24,468 | WARNING | Skipping broken line b'1626   162c   1ee6c': Odd-length string
2026-10-26 22:11:24,468 | WARNING | Skipping broken line b'162d   1630   1ee74': Odd-length string
2026-10-26 22:11:24,469 | WARNING | Skipping broken line b'1631   1634   1ee79': Odd-length string
2026-10-26 22:11:24,469 | WARNING | Skipping broken line b'1636   1699   1f030': Odd-length string
2026-10-26 22:11:24,469 | WARNING | Skipping broken line b'169a   16a8   1f0a0': Odd-length string
2026-10-26 22:11:24,469 | WARNING | Skipping broken line b'16a9   16b6   1f0b1': Odd-length string
2026-10-26 22:11:24,469 | WARNING | Skipping broken line b'16b7   16c5   1f0c1': Odd-length string
2026-10-26 22:11:24,469 | WARNING | Skipping broken line b'16c6   16d4   1f0d1': Odd-length string
2026-10-26 22:11:24,469 | WARNING | Skipping broken line b'16d5   16dc   1f311': Odd-length string
2026-10-26 22:11:24,469 | WARNING | Skipping broken line b'16dd   16de   1f42d': Odd-length string
2026-10-26 22:11:24,470 | WARNING | Skipping broken line b'16e1   16ff   1f600': Odd-length string
2026-10-26 22:11:24,470 | WARNING | Skipping broken line b'1700   1704   1f61f': Odd-length string
2026-10-26 22:11:24,470 | WARNING | Skipping broken line b'1705   170b   1f625': Odd-length string
2026-10-26 22:11:24,470 | WARNING | Skipping broken line b'170c   171f   1f62d': Odd-length string
2026-10-26 22:11:24,470 | WARNING | Got invalid hex string: Odd-length string (b'1d546')
2026-10-26 22:11:24,470 | WARNING | Got invalid hex string: Odd-length string (b'1ee24')
2026-10-26 22:11:24,470 | WARNING | Got invalid hex string: Odd-length string (b'1ee27')
2026-10-26 22:11:24,471 | WARNING | Got invalid hex string: Odd-length string (b'1ee39')
2026-10-26 22:11:24,471 | WARNING | Got invalid hex string: Odd-length string (b'1ee3b')
2026-10-26 22:11:24,471 | WARNING | Got invalid hex string: Odd-length string (b'1ee64')
2026-10-26 22:11:24,471 | WARNING | Got invalid hex string: Odd-length string (b'1ee7e')
2026-10-26 22:11:24,471 | WARNING | Got invalid hex string: Odd-length string (b'1f431')
2026-10-26 22:11:24,471 | WARNING | Got invalid hex string: Odd-length string (b'1f435')
2026-10-26 22:11:24,471 | WARNING | Got invalid hex string: Odd-length string (b'1f643')
2026-10-26 22:12:19,310 | INFO | Processed 175/500 papers
2026-10-26 22:13:11,132 | WARNING | could not convert string to float: b'0.000000000000-5684342' : FloatObject (b'0.000000000000-5684342') invalid; use 0.0 instead
2026-10-26 22:13:11,139 | WARNING | could not convert string to float: b'0.000000000000-5684342' : FloatObject (b'0.000000000000-5684342') invalid; use 0.0 instead
2026-10-26 22:13:11,145 | WARNING | could not convert string to float: b'0.000000000000-5684342' : FloatObject (b'0.000000000000-5684342') invalid; use 0.0 instead
2026-10-26 22:14:01,935 | WARNING | Skipping broken line b'14f6   14ff   10300': Odd-length string
2026-10-26 22:14:01,935 | WARNING | Skipping broken line b'1500   1514   1030a': Odd-length string
2026-10-26 22:14:01,936 | WARNING | Skipping broken line b'1515   1518   10320': Odd-length string
2026-10-26 22:14:01,936 | WARNING | Skipping broken line b'1519   156f   1d300': Odd-length string
2026-10-26 22:14:01,936 | WARNING | Skipping broken line b'1570   1571   1d538': Odd-length string
2026-10-26 22:14:01,937 | WARNING | Skipping broken line b'1572   1575   1d53b': Odd-length string
2026-10-26 22:14:01,937 | WARNING | Skipping broken line b'1576   157a   1d540': Odd-length string
2026-10-26 22:14:01,937 | WARNING | Skipping broken line b'157c   1582   1d54a': Odd-length string
2026-10-26 22:14:01,937 | WARNING | Skipping broken line b'1583   159c   1d552': Odd-length string
2026-10-26 22:14:01,937 | WARNING | Skipping broken line b'159d   15d0   1d5d4': Odd-length string
2026-10-26 22:14:01,937 | WARNING | Skipping broken line b'15d1   15ff   1d756': Odd-length string
2026-10-26 22:14:01,938 | WARNING | Skipping broken line b'1600   160a   1d785': Odd-length string
2026-10-26 22:14:01,938 | WARNING | Skipping broken line b'160b   1614   1d7d8': Odd-length string
2026-10-26 22:14:01,938 | WARNING | Skipping broken line b'1615   161e   1d7ec': Odd-length string
2026-10-26 22:14:01,938 | WARNING | Skipping broken line b'161f   1682   1f030': Odd-length string
2026-10-26 22:14:01,938 | WARNING | Skipping broken line b'1683   1691   1f0a0': Odd-length string
2026-10-26 22:14:01,939 | WARNING | Skipping broken line b'1692   169f   1f0b1': Odd-length string
2026-10-26 22:14:01,939 | WARNING | Skipping broken line b'16a0   16ae   1f0c1': Odd-length string
2026-10-26 22:14:01,939 | WARNING | Skipping broken line b'16af   16bd   1f0d1': Odd-length string
2026-10-26 22:14:01,939 | WARNING | Skipping broken line b'16be   16bf   1f42d': Odd-length string
2026-10-26 22:14:01,939 | WARNING | Skipping broken line b'16c2   16e5   1f600': Odd-length string
2026-10-26 22:14:01,939 | WARNING | Skipping broken line b'16e6   16ec   1f625': Odd-length string
2026-10-26 22:14:01,940 | WARNING | Skipping broken line b'16ed   16ff   1f62d': Odd-length string
2026-10-26 22:14:01,940 | WARNING | Got invalid hex string: Odd-length string (b'1d546')
2026-10-26 22:14:01,940 | WARNING | Got invalid hex string: Odd-length string (b'1f431')
2026-10-26 22:14:01,940 | WARNING | Got invalid hex string: Odd-length string (b'1f435')
2026-10-26 22:14:01,941 | WARNING | Got invalid hex string: Odd-length string (b'1f640')
2026-10-26 22:14:01,947 | WARNING | Skipping broken line b'14fa   14ff   10300': Odd-length string
2026-10-26 22:14:01,947 | WARNING | Skipping broken line b'1500   1518   10306': Odd-length string
2026-10-26 22:14:01,948 | WARNING | Skipping broken line b'1519   151c   10320': Odd-length string
2026-10-26 22:14:01,948 | WARNING | Skipping broken line b'151d   1573   1d300': Odd-length string
2026-10-26 22:14:01,948 | WARNING | Skipping broken line b'1574   1575   1d538': Odd-length string
2026-10-26 22:14:01,948 | WARNING | Skipping broken line b'1576   1579   1d53b': Odd-length string
2026-10-26 22:14:01,948 | WARNING | Skipping broken line b'157a   157e   1d540': Odd-length string
2026-10-26 22:14:01,948 | WARNING | Skipping broken line b'1580   1586   1d54a': Odd-length string
2026-10-26 22:14:01,949 | WARNING | Skipping broken line b'1587   15a0   1d552': Odd-length string
2026-10-26 22:14:01,949 | WARNING | Skipping broken line b'15a1   15d4   1d5a0': Odd-length string
2026-10-26 22:14:01,949 | WARNING | Skipping broken line b'15d5   15e8   1d7d8': Odd-length string
2026-10-26 22:14:01,949 | WARNING | Skipping broken line b'15e9   15ec   1ee00': Odd-length string
2026-10-26 22:14:01,949 | WARNING | Skipping broken line b'15ed   15ff   1ee05': Odd-length string
2026-10-26 22:14:01,949 | WARNING | Skipping broken line b'1600   1607   1ee18': Odd-length string
2026-10-26 22:14:01,949 | WARNING | Skipping broken line b'1608   1609   1ee21': Odd-length string
2026-10-26 22:14:01,950 | WARNING | Skipping broken line b'160c   1615   1ee29': Odd-length string
2026-10-26 22:14:01,950 | WARNING | Skipping broken line b'1616   1619   1ee34': Odd-length string
2026-10-26 22:14:01,950 | WARNING | Skipping broken line b'161c   161d   1ee61': Odd-length string
2026-10-26 22:14:01,950 | WARNING | Skipping broken line b'161f   1622   1ee67': Odd-length string
2026-10-26 22:14:01,950 | WARNING | Skipping broken line b'1623   1629   1ee6c': Odd-length string
2026-10-26 22:14:01,951 | WARNING | Skipping broken line b'162a   162d   1ee74': Odd-length string
2026-10-26 22:14:01,951 | WARNING | Skipping broken line b'162e   1631   1ee79': Odd-length string
2026-10-26 22:14:01,951 | WARNING | Skipping broken line b'1633   1696   1f030': Odd-length string
2026-10-26 22:14:01,951 | WARNING | Skipping broken line b'1697   16a5   1f0a0': Odd-length string
2026-10-26 22:14:01,951 | WARNING | Skipping broken line b'16a6   16b3   1f0b1': Odd-length string
2026-10-26 22:14:01,951 | WARNING | Skipping broken line b'16b4   16c2   1f0c1': Odd-length string
2026-10-26 22:14:01,952 | WARNING | Skipping broken line b'16c3   16d1   1f0d1': Odd-length string
2026-10-26 22:14:01,952 | WARNING | Skipping broken line b'16d2   16d3   1f42d': Odd-length string
2026-10-26 22:14:01,952 | WARNING | Skipping broken line b'16d6   16f9   1f600': Odd-length string
2026-10-26 22:14:01,952 | WARNING | Skipping broken line b'16fa   16ff   1f625': Odd-length string
2026-10-26 22:14:01,952 | WARNING | Skipping broken line b'1701   1714   1f62d': Odd-length string
2026-10-26 22:14:01,953 | WARNING | Got invalid hex string: Odd-length string (b'1d546')
2026-10-26 22:14:01,953 | WARNING | Got invalid hex string: Odd-length string (b'1ee24')
2026-10-26 22:14:01,953 | WARNING | Got invalid hex string: Odd-length string (b'1ee27')
2026-10-26 22:14:01,953 | WARNING | Got invalid hex string: Odd-length string (b'1ee39')
2026-10-26 22:14:01,953 | WARNING | Got invalid hex string: Odd-length string (b'1ee3b')
2026-10-26 22:14:01,954 | WARNING | Got invalid hex string: Odd-length string (b'1ee64')
2026-10-26 22:14:01,954 | WARNING | Got invalid hex string: Odd-length string (b'1ee7e')
2026-10-26 22:14:01,954 | WARNING | Got invalid hex string: Odd-length string (b'1f431')
2026-10-26 22:14:01,954 | WARNING | Got invalid hex string: Odd-length string (b'1f435')
2026-10-26 22:14:01,954 | WARNING | Got invalid hex string: Odd-length string (b'1f62b')
2026-10-26 22:14:14,872 | INFO | Processed 200/500 papers
2026-10-26 22:16:04,564 | INFO | Processed 225/500 papers
2026-10-26 22:16:37,578 | WARNING | Skipping broken line b'11cd   11d2   10780': Odd-length string
2026-10-26 22:16:37,579 | WARNING | Skipping broken line b'11d3   11fc   10787': Odd-length string
2026-10-26 22:16:37,579 | WARNING | Skipping broken line b'11fd   11ff   107b2': Odd-length string
2026-10-26 22:16:37,579 | WARNING | Skipping broken line b'1200   1205   107b5': Odd-length string
2026-10-26 22:16:37,579 | WARNING | Skipping broken line b'1206   1224   1df00': Odd-length string
2026-10-26 22:16:37,580 | WARNING | Skipping broken line b'1225   122a   1df25': Odd-length string
2026-10-26 22:16:37,585 | WARNING | Skipping broken line b'0d04   0d09   10780': Odd-length string
2026-10-26 22:16:37,585 | WARNING | Skipping broken line b'0d0a   0d33   10787': Odd-length string
2026-10-26 22:16:37,585 | WARNING | Skipping broken line b'0d34   0d3c   107b2': Odd-length string
2026-10-26 22:16:37,585 | WARNING | Skipping broken line b'0d3d   0d5b   1df00': Odd-length string
2026-10-26 22:16:37,585 | WARNING | Skipping broken line b'0d5c   0d61   1df25': Odd-length string
2026-10-26 22:16:37,591 | WARNING | Skipping broken line b'11cd   11d2   10780': Odd-length string
2026-10-26 22:16:37,591 | WARNING | Skipping broken line b'11d3   11fc   10787': Odd-length string
2026-10-26 22:16:37,591 | WARNING | Skipping broken line b'11fd   11ff   107b2': Odd-length string
2026-10-26 22:16:37,591 | WARNING | Skipping broken line b'1200   1205   107b5': Odd-length string
2026-10-26 22:16:37,592 | WARNING | Skipping broken line b'1206   1224   1df00': Odd-length string
2026-10-26 22:16:37,592 | WARNING | Skipping broken line b'1225   122a   1df25': Odd-length string
2026-10-26 22:17:05,937 | WARNING | Skipping broken line b'11cd   11d2   10780': Odd-length string
2026-10-26 22:17:05,937 | WARNING | Skipping broken line b'11d3   11fc   10787': Odd-length string
2026-10-26 22:17:05,938 | WARNING | Skipping broken line b'11fd   11ff   107b2': Odd-length string
2026-10-26 22:17:05,938 | WARNING | Skipping broken line b'1200   1205   107b5': Odd-length string
2026-10-26 22:17:05,938 | WARNING | Skipping broken line b'1206   1224   1df00': Odd-length string
2026-10-26 22:17:05,939 | WARNING | Skipping broken line b'1225   122a   1df25': Odd-length string
2026-10-26 22:17:05,944 | WARNING | Skipping broken line b'0d04   0d09   10780': Odd-length string
2026-10-26 22:17:05,944 | WARNING | Skipping broken line b'0d0a   0d33   10787': Odd-length string
2026-10-26 22:17:05,944 | WARNING | Skipping broken line b'0d34   0d3c   107b2': Odd-length string
2026-10-26 22:17:05,944 | WARNING | Skipping broken line b'0d3d   0d5b   1df00': Odd-length string
2026-10-26 22:17:05,945 | WARNING | Skipping broken line b'0d5c   0d61   1df25': Odd-length string
2026-10-26 22:17:05,950 | WARNING | Skipping broken line b'11cd   11d2   10780': Odd-length string
2026-10-26 22:17:05,950 | WARNING | Skipping broken line b'11d3   11fc   10787': Odd-length string
2026-10-26 22:17:05,951 | WARNING | Skipping broken line b'11fd   11ff   107b2': Odd-length string
2026-10-26 22:17:05,951 | WARNING | Skipping broken line b'1200   1205   107b5': Odd-length string
2026-10-26 22:17:05,951 | WARNING | Skipping broken line b'1206   1224   1df00': Odd-length string
2026-10-26 22:17:05,951 | WARNING | Skipping broken line b'1225   122a   1df25': Odd-length string
2026-10-26 22:17:07,159 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-26 22:17:07,189 | WARNING | Skipping broken line b'11cd   11d2   10780': Odd-length string
2026-10-26 22:17:07,189 | WARNING | Skipping broken line b'11d3   11fc   10787': Odd-length string
2026-10-26 22:17:07,190 | WARNING | Skipping broken line b'11fd   11ff   107b2': Odd-length string
2026-10-26 22:17:07,190 | WARNING | Skipping broken line b'1200   1205   107b5': Odd-length string
2026-10-26 22:17:07,190 | WARNING | Skipping broken line b'1206   1224   1df00': Odd-length string
2026-10-26 22:17:07,190 | WARNING | Skipping broken line b'1225   122a   1df25': Odd-length string
2026-10-26 22:17:07,196 | WARNING | Skipping broken line b'11cd   11d2   10780': Odd-length string
2026-10-26 22:17:07,196 | WARNING | Skipping broken line b'11d3   11fc   10787': Odd-length string
2026-10-26 22:17:07,197 | WARNING | Skipping broken line b'11fd   11ff   107b2': Odd-length string
2026-10-26 22:17:07,197 | WARNING | Skipping broken line b'1200   1205   107b5': Odd-length string
2026-10-26 22:17:07,197 | WARNING | Skipping broken line b'1206   1224   1df00': Odd-length string
2026-10-26 22:17:07,197 | WARNING | Skipping broken line b'1225   122a   1df25': Odd-length string
2026-10-26 22:17:07,202 | WARNING | Skipping broken line b'0d04   0d09   10780': Odd-length string
2026-10-26 22:17:07,202 | WARNING | Skipping broken line b'0d0a   0d33   10787': Odd-length string
2026-10-26 22:17:07,203 | WARNING | Skipping broken line b'0d34   0d3c   107b2': Odd-length string
2026-10-26 22:17:07,203 | WARNING | Skipping broken line b'0d3d   0d5b   1df00': Odd-length string
2026-10-26 22:17:07,203 | WARNING | Skipping broken line b'0d5c   0d61   1df25': Odd-length string
2026-10-26 22:17:07,208 | WARNING | Skipping broken line b'0d04   0d09   10780': Odd-length string
2026-10-26 22:17:07,208 | WARNING | Skipping broken line b'0d0a   0d33   10787': Odd-length string
2026-10-26 22:17:07,208 | WARNING | Skipping broken line b'0d34   0d3c   107b2': Odd-length string
2026-10-26 22:17:07,209 | WARNING | Skipping broken line b'0d3d   0d5b   1df00': Odd-length string
2026-10-26 22:17:07,209 | WARNING | Skipping broken line b'0d5c   0d61   1df25': Odd-length string
2026-10-26 22:17:07,218 | WARNING | Skipping broken line b'11cd   11d2   10780': Odd-length string
2026-10-26 22:17:07,218 | WARNING | Skipping broken line b'11d3   11fc   10787': Odd-length string
2026-10-26 22:17:07,218 | WARNING | Skipping broken line b'11fd   11ff   107b2': Odd-length string
2026-10-26 22:17:07,219 | WARNING | Skipping broken line b'1200   1205   107b5': Odd-length string
2026-10-26 22:17:07,219 | WARNING | Skipping broken line b'1206   1224   1df00': Odd-length string
2026-10-26 22:17:07,219 | WARNING | Skipping broken line b'1225   122a   1df25': Odd-length string
2026-10-26 22:17:07,226 | WARNING | Skipping broken line b'11cd   11d2   10780': Odd-length string
2026-10-26 22:17:07,226 | WARNING | Skipping broken line b'11d3   11fc   10787': Odd-length string
2026-10-26 22:17:07,227 | WARNING | Skipping broken line b'11fd   11ff   107b2': Odd-length string
2026-10-26 22:17:07,227 | WARNING | Skipping broken line b'1200   1205   107b5': Odd-length string
2026-10-26 22:17:07,227 | WARNING | Skipping broken line b'1206   1224   1df00': Odd-length string
2026-10-26 22:17:07,227 | WARNING | Skipping broken line b'1225   122a   1df25': Odd-length string
2026-10-26 22:17:10,548 | WARNING | Skipping broken line b'11cd   11d2   10780': Odd-length string
2026-10-26 22:17:10,548 | WARNING | Skipping broken line b'11d3   11fc   10787': Odd-length string
2026-10-26 22:17:10,548 | WARNING | Skipping broken line b'11fd   11ff   107b2': Odd-length string
2026-10-26 22:17:10,548 | WARNING | Skipping broken line b'1200   1205   107b5': Odd-length string
2026-10-26 22:17:10,549 | WARNING | Skipping broken line b'1206   1224   1df00': Odd-length string

ArrowKeyError: No type extension with name arrow.py_extension_type found

## Summary

- Extracted per-page text and metadata for all 500 papers.
- Cleaned hyphenation breaks, stray footnote symbols, and irregular whitespace found during Part 1.
- Chunked text at the page level (250 words, 40-word overlap) so every chunk keeps an accurate page number for citations.
- Validated that every chunk has complete metadata, a unique ID, and non-empty text.
- Packaged the flow into `ArxivIngestionPipeline` for repeatable reruns.
- Output: `data_processed/chunks.jsonl` and `chunks.parquet`, ready for embedding.

# Part 3: RAG Model Build

In [ ]:
# install dependencies
# llamaindex is the core framework that wraps the other components (embeddings, vector stores, LLMs) together
# chromadb is a vector database for the embeddings

%pip install fastparquet llama-index-core llama-index-embeddings-huggingface llama-index-vector-stores-chroma llama-index-llms-groq chromadb
import os
import chromadb

from llama_index.core import VectorStoreIndex, StorageContext, Settings
from llama_index.core.schema import TextNode
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.core.postprocessor import SentenceTransformerRerank
from llama_index.retrievers.bm25 import BM25Retriever
from llama_index.core.retrievers import QueryFusionRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.llms.groq import Groq

Requirement already satisfied: llama-index-core in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (0.14.25)
Requirement already satisfied: llama-index-embeddings-huggingface in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (0.8.0)
Requirement already satisfied: llama-index-vector-stores-chroma in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (0.6.0)
Requirement already satisfied: llama-index-llms-groq in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (0.6.1)
Requirement already satisfied: chromadb in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (1.5.9)
Requirement already satisfied: aiohttp<4,>=3.8.6 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (3.14.5)
Requirement already satisfied: aiosqlite in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (0.22.1)
Requirement already satisfied: banks<3,>=2.3.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (2.5.1)
Requirement already satisfied: dataclasses-json in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (1.3.1)
Requirement already satisfied: dirtyjson<2,>=1.0.8 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (1.0.8)
Requirement already satisfied: filetype<2,>=1.2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (1.2.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (2026.9.0)
Requirement already satisfied: httpx in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (0.28.1)
Requirement already satisfied: llama-index-workflows<3,>=2.14.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (2.26.1)
Requirement already satisfied: nest-asyncio<2,>=1.5.8 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (3.6.1)
Requirement already satisfied: nltk>=3.9.3 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (3.10.4)
Requirement already satisfied: numpy in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (2.4.6)
Requirement already satisfied: pillow>=9.0.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (13.0.0)
Requirement already satisfied: platformdirs in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (4.11.8)
Requirement already satisfied: pydantic>=2.8.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (2.14.1)
Requirement already satisfied: pyyaml>=6.0.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (6.0.3)
Requirement already satisfied: requests>=2.31.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (2.34.2)
Requirement already satisfied: setuptools>=80.9.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (84.2.1)
Requirement already satisfied: sqlalchemy[asyncio]>=1.4.49 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (2.1.6)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (9.2.1)
Requirement already satisfied: tiktoken>=0.7.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (0.14.0)
Requirement already satisfied: tinytag>=2.2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (2.3.2)
Requirement already satisfied: tqdm<5,>=4.66.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (4.70.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (4.16.0)
Requirement already satisfied: typing-inspect>=0.8.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (0.9.0)
Requirement already satisfied: wrapt in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-core) (2.5.1)
Requirement already satisfied: huggingface-hub[inference]>=0.19.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-embeddings-huggingface) (2.3.0)
Requirement already satisfied: sentence-transformers>=2.6.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-embeddings-huggingface) (6.2.0)
Requirement already satisfied: llama-index-llms-openai-like<0.9,>=0.8.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from llama-index-llms-groq) (0.8.1)
Requirement already satisfied: build>=1.0.3 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (1.6.1)
Requirement already satisfied: pydantic-settings>=2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (2.16.1)
Requirement already satisfied: pybase64>=1.4.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (1.5.1)
Requirement already satisfied: uvicorn[standard]>=0.18.3 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (0.54.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (1.31.1)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (1.45.1)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (1.45.1)
Requirement already satisfied: tokenizers>=0.13.2 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (0.23.3)
Requirement already satisfied: pypika>=0.48.9 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (0.51.1)
Requirement already satisfied: overrides>=7.3.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (1.85.0)
Requirement already satisfied: bcrypt>=4.0.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (0.27.3)
Requirement already satisfied: kubernetes>=28.1.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (37.0.1)
Requirement already satisfied: mmh3>=4.0.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (5.3.1)
Requirement already satisfied: orjson>=3.9.12 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (3.13.0)
Requirement already satisfied: rich>=10.11.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (15.0.0)
Requirement already satisfied: jsonschema>=4.19.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from chromadb) (4.26.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (1.8.0)
Requirement already satisfied: multidict<8.0,>=4.5 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (7.2.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.25.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (1.25.1)
Requirement already satisfied: griffe in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from banks<3,>=2.3.0->llama-index-core) (2.4.1)
Requirement already satisfied: jinja2 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from banks<3,>=2.3.0->llama-index-core) (3.1.6)
Requirement already satisfied: packaging>=24.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from build>=1.0.3->chromadb) (26.3)
Requirement already satisfied: pyproject_hooks in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from build>=1.0.3->chromadb) (1.3.3)
Requirement already satisfied: anyio in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from httpx->llama-index-core) (4.15.1)
Requirement already satisfied: certifi in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from httpx->llama-index-core) (2026.10.23)
Requirement already satisfied: httpcore==1.* in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from httpx->llama-index-core) (1.0.9)
Requirement already satisfied: idna in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from httpx->llama-index-core) (3.20)
Requirement already satisfied: h11>=0.16 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from httpcore==1.*->httpx->llama-index-core) (0.16.0)
WARNING: huggingface-hub 2.3.0 does not provide the extra 'inference'
Requirement already satisfied: click<9.0.0,>=8.4.2 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.2.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.7.0)
Requirement already satisfied: httpx2<3,>=2.0.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (2.16.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from jsonschema>=4.19.0->chromadb) (2026.9.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (1.9.2)
Requirement already satisfied: requests-oauthlib in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3<3.0.0,>=2.8.0 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (2.8.0)
Requirement already satisfied: durationpy>=0.11 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (0.11)
Requirement already satisfied: aiohttp-retry>=2.9.1 in /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages (from kubernetes>=28.1.0->chromadb) (2.9.1)

/Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
W1026 22:56:47.793000 48407 torch/distributed/elastic/multiprocessing/redirects.py:35] NOTE: Redirects are currently not supported in MacOs.

In [ ]:
# CHANGE MADE: load the saved JSONL copy of the processed chunks.
# This avoids the Parquet/PyArrow compatibility issue encountered during testing.

chunks_df = pd.read_json(
    processed_dir / "chunks.jsonl",
    lines=True
)

print(
    f"loaded {len(chunks_df)} chunks "
    f"from {processed_dir / 'chunks.jsonl'}"
)

loaded 36479 chunks from /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chunks.jsonl

In [5]:
# convert raw chunks into llamaindex textnodes, i.e. units with text and metadata

nodes = []
for _, row in chunks_df.iterrows():
    node = TextNode(
        text=row["text"],
        metadata={
            "arxiv_id": row["arxiv_id"],
            "title": row["title"],
            "author": row["author"],
            "page_number": row["page_number"],
        }
    )
    nodes.append(node)

print(f"built {len(nodes)} nodes")

built 36479 nodes

In [6]:
# config embedding model

Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

2026-10-26 22:57:49,666 | INFO | HTTP Request: GET https://huggingface.co/api/agent-harnesses "HTTP/1.1 200 OK"
2026-10-26 22:57:49,705 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-10-26 22:57:49,761 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-10-26 22:57:49,791 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Fmodules.json=&etag=%22952a9b81c0bfd99800fabf352f69c7ccd46c5e43%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:49,810 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Fmodules.json=&etag=%22952a9b81c0bfd99800fabf352f69c7ccd46c5e43%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:49,839 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-10-26 22:57:49,866 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Fconfig_sentence_transformers.json=&etag=%22dcb0c0d97d09b930d13600b1a773ddb27e441aab%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:49,895 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Fconfig_sentence_transformers.json=&etag=%22dcb0c0d97d09b930d13600b1a773ddb27e441aab%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:49,898 | INFO | Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-10-26 22:57:49,929 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-10-26 22:57:49,929 | WARNING | Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-10-26 22:57:49,956 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2FREADME.md=&etag=%228b8567d75ffa619486d9590cb0eb76d66ad46c49%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:49,989 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2FREADME.md=&etag=%228b8567d75ffa619486d9590cb0eb76d66ad46c49%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:50,019 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-26 22:57:50,045 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Fsentence_bert_config.json=&etag=%22ea85692bff64b0d1917833c31ddbca8ab10f5455%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:50,071 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Fsentence_bert_config.json=&etag=%22ea85692bff64b0d1917833c31ddbca8ab10f5455%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:50,107 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/adapter_config.json "HTTP/1.1 404 Not Found"
2026-10-26 22:57:50,133 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-26 22:57:50,162 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Fconfig.json=&etag=%223992bf890728a92476c700e6e657fd696eb94160%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:50,188 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Fconfig.json=&etag=%223992bf890728a92476c700e6e657fd696eb94160%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:50,265 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/model.safetensors "HTTP/1.1 302 Found"
2026-10-26 22:57:50,523 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/xet-read-token/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 13557.04it/s]
2026-10-26 22:57:54,196 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/processor_config.json "HTTP/1.1 404 Not Found"
2026-10-26 22:57:54,221 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-10-26 22:57:54,250 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-10-26 22:57:54,278 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-26 22:57:54,302 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Ftokenizer_config.json=&etag=%2237fca74771bc76a8e01178ce3a6055a0995f8093%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:54,331 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Ftokenizer_config.json=&etag=%2237fca74771bc76a8e01178ce3a6055a0995f8093%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:54,366 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-10-26 22:57:54,401 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-10-26 22:57:54,434 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/vocab.txt "HTTP/1.1 307 Temporary Redirect"
2026-10-26 22:57:54,455 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/vocab.txt?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Fvocab.txt=&etag=%22fb140275c155a9c7c5a3b3e0e77a9e839594a938%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:54,483 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/vocab.txt?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Fvocab.txt=&etag=%22fb140275c155a9c7c5a3b3e0e77a9e839594a938%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:54,538 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer.json "HTTP/1.1 307 Temporary Redirect"
2026-10-26 22:57:54,567 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Ftokenizer.json=&etag=%22688882a79f44442ddc1f60d70334a7ff5df0fb47%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:54,596 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Ftokenizer.json=&etag=%22688882a79f44442ddc1f60d70334a7ff5df0fb47%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:54,667 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/added_tokens.json "HTTP/1.1 404 Not Found"
2026-10-26 22:57:54,700 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/special_tokens_map.json "HTTP/1.1 307 Temporary Redirect"
2026-10-26 22:57:54,728 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/special_tokens_map.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Fspecial_tokens_map.json=&etag=%22a8b3208c2884c4efb86e49300fdd3dc877220cdf%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:54,755 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/special_tokens_map.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2Fspecial_tokens_map.json=&etag=%22a8b3208c2884c4efb86e49300fdd3dc877220cdf%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:54,784 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/chat_template.jinja "HTTP/1.1 404 Not Found"
2026-10-26 22:57:54,862 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-26 22:57:54,891 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2F1_Pooling%2Fconfig.json=&etag=%221da070f0993788c8851a652170ff013aa54dd519%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:54,917 | INFO | HTTP Request: GET https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2F5c38ec7c405ec4b44b94cc5a9bb96e735b38267a%2F1_Pooling%2Fconfig.json=&etag=%221da070f0993788c8851a652170ff013aa54dd519%22 "HTTP/1.1 200 OK"
2026-10-26 22:57:54,944 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/2_Normalize/config.json "HTTP/1.1 404 Not Found"
2026-10-26 22:57:55,224 | INFO | Loaded 1 prompt with these keys: ['query']

In [ ]:
# CHANGE MADE: explicitly load and pass the Groq API key from the project .env file.
# This avoids stale authentication state during end-to-end testing.

from dotenv import load_dotenv
import os
from llama_index.llms.groq import Groq

load_dotenv(project_root / ".env", override=True)
groq_api_key = os.getenv("GROQ_API_KEY")

Settings.llm = Groq(
    model="openai/gpt-oss-120b",
    api_key=groq_api_key
)

In [8]:
# set up chroma for vectore store and build index

chroma_client = chromadb.PersistentClient(path=str(processed_dir / "chroma_db"))
chroma_collection = chroma_client.get_or_create_collection(name="arxiv_papers")

vectore_store = ChromaVectorStore(chroma_collection=chroma_collection)
storage_context = StorageContext.from_defaults(vector_store=vectore_store)

index = VectorStoreIndex(nodes, storage_context=storage_context)

print("index built and persisted to", processed_dir / "chroma_db")

index built and persisted to /Users/eimansherzada/Desktop/BTT-KPMG/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chroma_db

In [9]:
# hybrid retrieval: bm25 (keyword) + vector (semantic), fused via reciprocal rank fusion

bm25_retriever = BM25Retriever.from_defaults(nodes=nodes, similarity_top_k=30)
vector_retriever = index.as_retriever(similarity_top_k=30)

fusion_retriever = QueryFusionRetriever(
    [vector_retriever, bm25_retriever],
    similarity_top_k=30,
    num_queries=1,
    mode="reciprocal_rerank",
)

2026-10-26 23:05:44,710 | DEBUG | Building index from IDs objects

In [ ]:
# change made: use the hybrid fusion retriever here so the query engine actually combines
# BM25 keyword retrieval and vector semantic retrieval before reranking.
reranker = SentenceTransformerRerank(
    model="cross-encoder/ms-marco-MiniLM-L-6-v2",
    top_n=5
)
# CHANGE MADE: explicitly pass the configured Groq LLM when building the query engine.
# This ensures the query engine uses the current authenticated LLM configuration
# instead of retaining a stale client from an earlier notebook state.
query_engine = RetrieverQueryEngine.from_args(
    fusion_retriever,
    llm=Settings.llm,
    node_postprocessors=[reranker]
)

2026-10-26 23:20:42,766 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L-6-v2 "HTTP/1.1 307 Temporary Redirect"
2026-10-26 23:20:42,811 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2 "HTTP/1.1 200 OK"
2026-10-26 23:20:42,850 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/233902d25c440f23af6f7d6e94d2946bac0bee0a/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-10-26 23:20:42,880 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/233902d25c440f23af6f7d6e94d2946bac0bee0a/modules.json "HTTP/1.1 404 Not Found"
2026-10-26 23:20:42,880 | INFO | No modules.json found for cross-encoder/ms-marco-MiniLM-L-6-v2, initializing a new CrossEncoder model.
Loading weights: 100%|██████████| 105/105 [00:00<00:00, 7531.71it/s]
2026-10-26 23:20:42,959 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L-6-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-10-26 23:20:42,988 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-10-26 23:20:43,015 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L-6-v2/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-10-26 23:20:43,055 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"

In [26]:
# ask question (hardcoded for now)

response = query_engine.query("What are the most relevant recent research papers on reducing hallucinations in retrieval-augmented generation? Summarize the main approaches and identify where the evidence is strongest.")

print("RESPONSE:\n", response)

print("\nSOURCES:")
for node in response.source_nodes:
    meta = node.metadata
    print(f"- {meta['title']} (page {meta['page_number']}, score={node.score:.3f})")

Batches: 100%|██████████| 1/1 [00:00<00:00, 21.84it/s]
2026-10-26 23:20:56,285 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

RESPONSE:
 **Key recent papers that focus on curbing hallucinations in Retrieval‑Augmented Generation (RAG)**

| Year | Paper (first author) | Core idea for hallucination reduction |
|------|----------------------|----------------------------------------|
| 2021 | Shuster et al. | Demonstrates that conditioning generation on retrieved passages markedly lowers factual errors in conversational settings. |
| 2023 | Manakul et al. (SelfCheckGPT) | Introduces a zero‑resource, black‑box detector that flags hallucinated spans without any fine‑tuning, improving post‑hoc reliability of RAG outputs. |
| 2024 | Asai et al. (Self‑RAG) | Proposes a self‑reflection loop where the model learns to retrieve, generate, and critique its own output, yielding tighter grounding and fewer hallucinations. |
| 2024 | RL4HS (Class‑Aware Policy Optimization – CAPO) | Applies reinforcement learning at the span level, optimizing a policy that explicitly rewards correct span identification; outperforms several proprietary baselines. |
| 2024 | RLVR (Reinforcement Learning with Verifiable Rewards) | Uses outcome‑based rewards derived from external verification signals to steer generation toward factual consistency. |
| 2025 | Cruz Blandón et al. (MEMERAG benchmark) | Provides a multilingual, end‑to‑end evaluation suite for RAG systems, enabling systematic measurement of hallucination mitigation techniques. |
| 2025 | Huang et al. (Survey) | Offers a comprehensive taxonomy of hallucination phenomena and summarizes mitigation strategies, highlighting the most empirically validated methods. |
| 2025 | FaithLens (8 B model) | Shows that a four‑stage supervised‑fine‑tuning pipeline can bring an open‑source model to parity with proprietary systems on case‑level hallucination detection. |
| 2025+ | Guided‑RL & Iterative‑Refinement paradigms | Recent work explores structured policy guidance and multi‑step refinement loops, though these approaches still show mismatches with the fine‑grained detection objective. |
| 2025+ | Search‑State‑Aware RL (e.g., Search‑R1, Jin et al.) | Frames information seeking as a sequential decision problem, letting the model decide when to retrieve, what to query, and when to stop, which improves grounding over long interaction trajectories. |

**Main methodological families**

1. **Retrieval‑centric grounding** – Directly augmenting generation with retrieved evidence (Lewis 2020; Guu 2020) and extending it to multi‑document aggregation (Izacard & Grave 2021). Empirical work (Shuster 2021) shows a clear drop in hallucination rates when this pipeline is used.

2. **Self‑controlled retrieval & reflection** – Models learn to decide *when* and *what* to retrieve, often via prompting or learned tokens (Yao 2022; Asai 2024). Self‑RAG adds a critique step, creating a closed feedback loop that tightens factual consistency.

3. **Reinforcement‑learning‑based policy optimization** – Outcome‑driven rewards (RLVR) and span‑level objectives (RL4HS with CAPO) directly incentivize correct factual spans. Reported results indicate that these RL‑driven systems surpass strong proprietary baselines on fine‑grained detection tasks.

4. **Zero‑resource detection & post‑hoc checks** – SelfCheckGPT offers a model‑agnostic hallucination detector that works without additional training data, providing a practical safety layer for any RAG system.

5. **Benchmarking & evaluation** – MEMERAG supplies a multilingual, end‑to‑end benchmark that quantifies the impact of different mitigation strategies, while the broader survey (Huang 2025) consolidates evidence across studies.

**Where the evidence is strongest**

- **Empirical reductions in hallucination rates** are most convincingly demonstrated in the retrieval‑augmentation experiments of Shuster et al. (2021) and the multi‑document aggregation extensions, which report consistent factual improvements across conversational datasets.
- **Reinforcement‑learning approaches** (RL4HS/CAPO and RLVR) provide the most rigorous quantitative gains at the span level, with reported outperformance of proprietary models on benchmark suites.
- **Self‑reflection loops** (Self‑RAG) show measurable benefits in both retrieval quality and generation fidelity, supported by ablation studies that isolate the critique component.
- **Zero‑resource detection** (SelfCheckGPT) is validated across several unseen models, indicating robust post‑generation filtering without fine‑tuning.
- **Benchmark‑driven validation** (MEMERAG) offers the clearest cross‑lingual, cross‑domain evidence base, allowing direct comparison of mitigation techniques.

Taken together, the strongest empirical support comes from the combination of retrieval‑augmented pipelines (especially multi‑document aggregation) and reinforcement‑learning‑driven policies that are explicitly rewarded for factual correctness. Post‑generation detectors and self‑reflection mechanisms serve as complementary safeguards, while the emerging benchmark infrastructure ensures that future claims can be measured on a common footing.

SOURCES:
- SOPO: Socratic Guided Policy Optimization for Span-Level Hallucination Detection (page 1, score=1.180)
- SOPO: Socratic Guided Policy Optimization for Span-Level Hallucination Detection (page 13, score=0.917)
- Self-Assessment Reinforcement Learning for Search-State Awareness in Retrieval-Augmented Large Language Models (page 8, score=0.834)
- Trust Mechanisms for Offline Generative AI at the Edge: A Connectivity-Regime Framework and an Empirical Study on a Raspberry Pi 5 (page 21, score=0.644)
- Mycelium: A Meta-Study of Hallucination Detection Across Provenance, Typology, and Granularities (page 11, score=0.629)

## Part 3B: End-to-End Retrieval + Summarization Workflow


This section tests the complete retrieval and summarization workflow across the expanded arXiv dataset. The workflow accepts a natural-language research question, retrieves and reranks relevant research chunks, generates a summarized response with the configured LLM, and returns source metadata for review.

In [27]:
def run_research_query(question, top_k=5):
    """
    Run a research question through the complete RAG pipeline
    and return the generated response with retrieved source metadata.
    """

    response = query_engine.query(question)

    sources = []

    for node in response.source_nodes[:top_k]:
        sources.append({
            "title": node.metadata.get("title"),
            "arxiv_id": node.metadata.get("arxiv_id"),
            "page_number": node.metadata.get("page_number"),
            "score": node.score
        })

    return {
        "question": question,
        "answer": str(response),
        "sources": sources
    }

In [28]:
test_questions = [
    "What recent methods are being used to reduce hallucinations in retrieval-augmented generation?",
    "What approaches are recent AI research papers using to improve AI agent reliability?",
    "What techniques are being explored to make large language models more efficient?",
    "What recent research focuses on improving the safety or trustworthiness of generative AI?",
    "How are researchers improving retrieval and reasoning in AI systems?"
]

test_results = []

for question in test_questions:
    result = run_research_query(question)
    test_results.append(result)

    print("=" * 80)
    print("QUESTION:")
    print(result["question"])

    print("\nANSWER:")
    print(result["answer"])

    print("\nSOURCES:")
    for source in result["sources"]:
        print(
            f"- {source['title']} "
            f"(arXiv: {source['arxiv_id']}, "
            f"page {source['page_number']}, "
            f"score={source['score']:.3f})"
        )

Batches: 100%|██████████| 1/1 [00:00<00:00, 11.63it/s]
2026-10-26 23:30:10,950 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

================================================================================
QUESTION:
What recent methods are being used to reduce hallucinations in retrieval-augmented generation?

ANSWER:
Recent work has introduced a variety of techniques that tighten the link between a model’s generation and the evidence it retrieves, thereby curbing hallucinations.  Highlights include:

* **Multi‑document aggregation** – combining information from several retrieved passages rather than a single snippet.
* **Self‑controlled retrieval** – letting the model decide when to issue a retrieval request and when to rely on its own knowledge, often guided by prompted reasoning traces or dedicated “reflection” tokens.
* **Learned tool‑use policies** – training the model to invoke a retriever as a tool and to switch between searching and generating based on learned policies.
* **Reinforcement‑learning approaches** – using outcome‑based rewards (e.g., RL with verifiable rewards) or class‑aware policy optimization to shape policies that favor fact‑consistent spans.  Guided‑RL and iterative‑refinement loops further refine the reasoning process.
* **Socratic‑style policy optimization** – framing the policy‑learning problem as a Socratic dialogue that steers the model toward correct evidence usage.
* **Search‑state awareness via RL** – teaching the model to maintain awareness of its search trajectory and to decide when to stop searching, as in self‑assessment RL for retrieval‑augmented models.
* **Self‑RAG** – a self‑reflection loop where the model learns to retrieve, generate, and critique its own outputs.
* **Failure‑aware self‑training (e.g., TriageRAG)** – automatically filtering generated training examples based on whether the retrieved evidence actually supports the answer, then fine‑tuning on the clean subset.
* **Round‑trip consistency pipelines (e.g., SimRAG)** – generating question‑answer pairs, checking that the original passage can be retrieved for the generated question, and using only those consistent pairs for further training.
* **Knowledge‑aware fine‑tuning** – weighting or selecting fine‑tuning examples according to the degree of conflict between the model’s parametric knowledge and the retrieved context.

Together, these methods tighten the grounding of generation on retrieved evidence and have been shown to markedly lower the incidence of hallucinated content in retrieval‑augmented generation systems.

SOURCES:
- SOPO: Socratic Guided Policy Optimization for Span-Level Hallucination Detection (arXiv: 2610.32212v1, page 1, score=3.379)
- Trust Mechanisms for Offline Generative AI at the Edge: A Connectivity-Regime Framework and an Empirical Study on a Raspberry Pi 5 (arXiv: 2610.33732v1, page 21, score=2.173)
- Self-Assessment Reinforcement Learning for Search-State Awareness in Retrieval-Augmented Large Language Models (arXiv: 2610.30435v1, page 8, score=2.048)
- TriageRAG: Failure-Aware Self-Training for Adapting Retrieval-Augmented Language Models to Specialized Domains (arXiv: 2610.33776v1, page 3, score=1.504)
- TriageRAG: Failure-Aware Self-Training for Adapting Retrieval-Augmented Language Models to Specialized Domains (arXiv: 2610.33776v1, page 1, score=1.395)

Batches: 100%|██████████| 1/1 [00:00<00:00, 27.94it/s]
2026-10-26 23:30:13,330 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

================================================================================
QUESTION:
What approaches are recent AI research papers using to improve AI agent reliability?

ANSWER:
Recent papers are tackling AI‑agent reliability through a combination of technical and organizational strategies:

* **Human‑in‑the‑Loop (HITL) and collaborative AI** – Integrating human expertise into the development and execution loop so that users can validate outputs, intervene on failures, and provide corrective feedback. This iterative supervision improves interpretability, trust calibration, and overall safety.

* **Uncertainty‑aware and reinforcement‑learning‑with‑human‑feedback designs** – Embedding uncertainty estimation and leveraging human‑provided reward signals to guide learning, which helps agents recognize when they are unsure and defer to human oversight.

* **Governance‑oriented frameworks** – Defining structured pillars such as transparency, accountability, and trustworthiness that make agent behavior observable, decisions attributable, and oversight enforceable throughout the system’s lifecycle.

* **Progressive autonomy with staged reduction of HITL** – Deploying agents in incremental phases, starting from assistive roles and gradually increasing autonomy only after validation, monitoring, and governance criteria are met.

* **Harness‑centric reliability engineering** – Treating the surrounding “harness” (the tooling, context management, execution environment, and verification mechanisms) as a first‑class component. Reliability is broken down into dimensions like context handling, execution control, lifecycle management, observability, tool integration, and verification.

* **Trace‑based evaluation and failure attribution** – Capturing detailed execution traces, using multi‑source evidence (from the agent, its harness, and the environment), and constructing explicit mechanism chains to pinpoint the source of failures. This enables systematic benchmarking of both model performance and harness robustness.

* **Benchmark suites for systematic assessment** – Building large‑scale, mechanism‑oriented task collections with executable ground truth to evaluate agents and their harnesses across many scenarios, providing reproducible metrics for reliability and failure analysis.

Together, these approaches blend human oversight, uncertainty handling, transparent governance, incremental autonomy, and rigorous harness evaluation to raise the reliability of AI agents in real‑world deployments.

SOURCES:
- A Three-Pillar Governance Framework for Safe and Trustworthy AI Agents (arXiv: 2610.30445v1, page 2, score=4.464)
- A Three-Pillar Governance Framework for Safe and Trustworthy AI Agents (arXiv: 2610.30445v1, page 1, score=4.240)
- A Three-Pillar Governance Framework for Safe and Trustworthy AI Agents (arXiv: 2610.30445v1, page 2, score=2.517)
- Trial by Trace: Benchmarking AI Agent Harnesses for Reliability and Failure Attribution (arXiv: 2610.32285v1, page 20, score=1.053)
- Trial by Trace: Benchmarking AI Agent Harnesses for Reliability and Failure Attribution (arXiv: 2610.32285v1, page 1, score=0.684)

Batches: 100%|██████████| 1/1 [00:00<00:00, 24.99it/s]
2026-10-26 23:30:14,094 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-26 23:30:14,097 | INFO | Retrying request to /chat/completions in 5.000000 seconds
2026-10-26 23:30:21,046 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

================================================================================
QUESTION:
What techniques are being explored to make large language models more efficient?

ANSWER:
A variety of approaches are being pursued to reduce the computational and memory demands of large language models while preserving or even improving their performance:

* **Model pruning** – both structured and unstructured techniques that cut away redundant weights or entire components in a single pass (e.g., one‑shot pruning, sparse‑GPT, LLM‑Pruner, Sheared LLaMA).
* **Quantization** – converting weights and activations to lower‑precision formats through post‑training quantization (SmoothQuant), quantization‑aware training without data (LLM‑QAT), or hybrid dense‑and‑sparse schemes (SqueezeLLM).
* **Distillation** – training smaller “student” models to mimic larger teachers, often using on‑policy or self‑generated data (MiniLLM, on‑policy distillation).
* **Efficient architectures for long contexts** – redesigning attention mechanisms to handle billions of tokens (LongNet), applying low‑rank adapters for long‑context fine‑tuning (LongLoRA), or using attention sinks to stream tokens efficiently.
* **Prompt compression** – shrinking prompts via context‑aware sentence encoding or other compression methods to speed up inference.
* **Data‑centric optimizations** – selecting the most informative training examples, augmenting data, re‑weighting samples, and reducing redundancy to make each training step more effective.
* **Vocabulary and tokenization engineering** – tailoring multilingual vocabularies, limiting token set size, and treating special tokens as versioned contracts to lower softmax costs and improve on‑device deployment.
* **Approximate unlearning** – removing unwanted knowledge with minimal retraining overhead.

Together, these strategies address both the training phase (reducing data and compute requirements) and the inference phase (cutting latency, memory usage, and energy consumption).

SOURCES:
- Data Optimization for LLMs: A Survey (arXiv: 2610.33405v1, page 45, score=2.338)
- A Comprehensive Framework for All Stages of Large-Model Training: From Data and Tokenization, through Pretraining, to Post-Training Alignment (arXiv: 2610.33451v1, page 137, score=1.560)
- A Comprehensive Framework for All Stages of Large-Model Training: From Data and Tokenization, through Pretraining, to Post-Training Alignment (arXiv: 2610.33451v1, page 137, score=1.365)
- Data Optimization for LLMs: A Survey (arXiv: 2610.33405v1, page 1, score=0.996)
- A Comprehensive Framework for All Stages of Large-Model Training: From Data and Tokenization, through Pretraining, to Post-Training Alignment (arXiv: 2610.33451v1, page 26, score=0.601)

Batches: 100%|██████████| 1/1 [00:00<00:00, 53.61it/s]
2026-10-26 23:30:21,438 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-26 23:30:21,441 | INFO | Retrying request to /chat/completions in 15.000000 seconds
2026-10-26 23:30:36,648 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-26 23:30:36,650 | INFO | Retrying request to /chat/completions in 1.000000 seconds
2026-10-26 23:30:39,265 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

================================================================================
QUESTION:
What recent research focuses on improving the safety or trustworthiness of generative AI?

ANSWER:
Recent work has explored several approaches to make generative AI safer and more trustworthy.  Researchers have extended Human‑in‑the‑Loop (HITL) concepts, proposing frameworks that keep humans central to knowledge creation and system oversight (e.g., the HitAI model) and surveying collaborative paradigms that blend human cognition with machine scalability.  Experimental studies have shown that interactive guidance can improve task completion and long‑term performance in complex settings, while specialized HITL interfaces such as Magentic‑UI embed structured approval and verification workflows for agentic systems.  In the reinforcement‑learning domain, scholars have highlighted the dependence of RL agents on human feedback and have linked explainability and trust to safer autonomy.  In the edge‑computing space, a connectivity‑regime framework has been introduced to treat network disconnection as a design dimension, accompanied by a taxonomy of inference‑time trust mechanisms.  Practical implementations on low‑power hardware demonstrate trust‑enhancing techniques such as retrieval‑score gating to detect knowledge gaps, deterministic output validators that convert malformed results into explicit abstentions, and entailment‑based verification modules.  Together, these studies represent a growing body of research aimed at improving the safety, alignment, and trustworthiness of generative AI systems.

SOURCES:
- A Three-Pillar Governance Framework for Safe and Trustworthy AI Agents (arXiv: 2610.30445v1, page 1, score=5.145)
- A Three-Pillar Governance Framework for Safe and Trustworthy AI Agents (arXiv: 2610.30445v1, page 2, score=2.203)
- Trust Mechanisms for Offline Generative AI at the Edge: A Connectivity-Regime Framework and an Empirical Study on a Raspberry Pi 5 (arXiv: 2610.33732v1, page 1, score=1.639)
- Trust Mechanisms for Offline Generative AI at the Edge: A Connectivity-Regime Framework and an Empirical Study on a Raspberry Pi 5 (arXiv: 2610.33732v1, page 3, score=1.117)
- A Three-Pillar Governance Framework for Safe and Trustworthy AI Agents (arXiv: 2610.30445v1, page 1, score=1.096)

Batches: 100%|██████████| 1/1 [00:00<00:00, 18.27it/s]
2026-10-26 23:30:40,139 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-26 23:30:40,140 | INFO | Retrying request to /chat/completions in 25.000000 seconds
2026-10-26 23:31:06,448 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

================================================================================
QUESTION:
How are researchers improving retrieval and reasoning in AI systems?

ANSWER:
Researchers are advancing retrieval‑augmented reasoning by combining better search awareness with collaborative, multi‑agent workflows. One line of work equips language‑model agents with self‑assessment mechanisms that let them recognize when the retrieved evidence is insufficient, use reinforcement learning to reward effective searching, and dynamically request additional information. Another approach structures multiple specialized agents around a shared memory buffer that asynchronously exchanges only the most relevant intermediate findings, keeping most of each agent’s reasoning private while still allowing them to build on each other’s insights. This selective sharing reduces token usage and improves accuracy, placing the system on the Pareto frontier of performance versus cost. Additional techniques such as multi‑query parallelism, context‑folding for long‑horizon tasks, and scaling test‑time compute further enhance the ability of models to retrieve pertinent data and integrate it into coherent, high‑quality reasoning chains. Together, these strategies make AI systems more adept at locating the right information and reasoning over it efficiently.

SOURCES:
- Muffin - A Shared Memory Buffer for Asynchronous AI Agents (arXiv: 2610.31355v1, page 2, score=0.440)
- Self-Assessment Reinforcement Learning for Search-State Awareness in Retrieval-Augmented Large Language Models (arXiv: 2610.30435v1, page 22, score=0.401)
- Artificial Intelligence in Mechanical Engineering: Foundations, Opportunities, Challenges, and Responsibilities (arXiv: 2610.33105v1, page 6, score=0.271)
- Self-Assessment Reinforcement Learning for Search-State Awareness in Retrieval-Augmented Large Language Models (arXiv: 2610.30435v1, page 11, score=0.171)
- Artificial Intelligence in Mechanical Engineering: Foundations, Opportunities, Challenges, and Responsibilities (arXiv: 2610.33105v1, page 20, score=-0.941)

In [29]:
initial_evaluation = pd.DataFrame([
    {
        "question": result["question"],
        "answer_generated": bool(result["answer"].strip()),
        "sources_returned": len(result["sources"]),
        "top_source": result["sources"][0]["title"] if result["sources"] else None
    }
    for result in test_results
])

initial_evaluation

,question,answer_generated,sources_returned,top_source
0,What recent methods are being used to reduce h...,True,5,SOPO: Socratic Guided Policy Optimization for ...
1,What approaches are recent AI research papers ...,True,5,A Three-Pillar Governance Framework for Safe a...
2,What techniques are being explored to make lar...,True,5,Data Optimization for LLMs: A Survey
3,What recent research focuses on improving the ...,True,5,A Three-Pillar Governance Framework for Safe a...
4,How are researchers improving retrieval and re...,True,5,Muffin - A Shared Memory Buffer for Asynchrono...

In [30]:
initial_evaluation["retrieval_relevant"] = [
    "Yes",
    "Yes",
    "Yes",
    "Yes",
    "Partial"
]

initial_evaluation["summary_useful"] = [
    "Yes",
    "Yes",
    "Yes",
    "Yes",
    "Yes"
]

initial_evaluation["notes"] = [
    "Retrieved papers directly address hallucination reduction methods.",
    "Sources were closely aligned with AI agent reliability.",
    "Retrieved survey/framework papers covered efficiency techniques.",
    "Sources were relevant to safety, governance, and trust mechanisms.",
    "Answer was useful, but some retrieved sources were only loosely related and one source had a negative retrieval score."
]

initial_evaluation

,question,answer_generated,sources_returned,top_source,retrieval_relevant,summary_useful,notes
0,What recent methods are being used to reduce h...,True,5,SOPO: Socratic Guided Policy Optimization for ...,Yes,Yes,Retrieved papers directly address hallucinatio...
1,What approaches are recent AI research papers ...,True,5,A Three-Pillar Governance Framework for Safe a...,Yes,Yes,Sources were closely aligned with AI agent rel...
2,What techniques are being explored to make lar...,True,5,Data Optimization for LLMs: A Survey,Yes,Yes,Retrieved survey/framework papers covered effi...
3,What recent research focuses on improving the ...,True,5,A Three-Pillar Governance Framework for Safe a...,Yes,Yes,"Sources were relevant to safety, governance, a..."
4,How are researchers improving retrieval and re...,True,5,Muffin - A Shared Memory Buffer for Asynchrono...,Partial,Yes,"Answer was useful, but some retrieved sources ..."

### Initial Testing Findings

The end-to-end workflow was able to generate an answer and return five sources for each of the test questions. Most of the retrieved sources matched the topic of the question pretty well, especially for the hallucination, AI agent reliability, model efficiency, and AI safety questions. The broader retrieval and reasoning question was a little weaker because some of the sources were less directly related, so that is something that could be improved in later testing. I also ran into a few temporary Groq rate-limit errors during the batch test, but the requests automatically retried and eventually completed successfully. Overall, the workflow is working from retrieval through summarization, but broader queries and API rate limits are still things to keep an eye on.

# Part 4 - Baseline RAG Evaluation

In [26]:
# Part 4: Baseline RAG Evaluation

import chromadb
import pandas as pd

from llama_index.core import VectorStoreIndex, StorageContext
from llama_index.vector_stores.chroma import ChromaVectorStore

In [27]:
# Create benchmark questions

benchmark_questions = [
    {
        "id": "Q1",
        "question": "What problem does Pandora's AI Model Routing Box aim to solve?",
        "expected_arxiv_id": "2608.20316v1"
    },
    {
        "id": "Q2",
        "question": "How does Pandora's AI Model Routing Box improve the efficiency of AI model selection?",
        "expected_arxiv_id": "2608.20316v1"
    },
    {
        "id": "Q3",
        "question": "What is AI4AI-Bench designed to evaluate?",
        "expected_arxiv_id": "2608.20318v1"
    },
    {
        "id": "Q4",
        "question": "How does AI4AI-Bench assess the performance of LLM agents in algorithmic design?",
        "expected_arxiv_id": "2608.20318v1"
    },
    {
        "id": "Q5",
        "question": "What information is used to induce task models from computer-use traces?",
        "expected_arxiv_id": "2608.20319v1"
    },
    {
        "id": "Q6",
        "question": "What is the purpose of the agentic approach for active data collection and travel behaviour modelling?",
        "expected_arxiv_id": "2608.20320v1"
    },
    {
        "id": "Q7",
        "question": "What problem does grounded checklist-aligned reward learning address in patient-oriented medical research?",
        "expected_arxiv_id": "2608.20331v1"
    },
    {
        "id": "Q8",
        "question": "How is reward learning used to improve patient-oriented medical outcomes?",
        "expected_arxiv_id": "2608.20331v1"
    }
]

benchmark_df = pd.DataFrame(benchmark_questions)

benchmark_df

   id                                           question expected_arxiv_id
0  Q1  What problem does Pandora's AI Model Routing B...      2608.20316v1
1  Q2  How does Pandora's AI Model Routing Box improv...      2608.20316v1
2  Q3          What is AI4AI-Bench designed to evaluate?      2608.20318v1
3  Q4  How does AI4AI-Bench assess the performance of...      2608.20318v1
4  Q5  What information is used to induce task models...      2608.20319v1
5  Q6  What is the purpose of the agentic approach fo...      2608.20320v1
6  Q7  What problem does grounded checklist-aligned r...      2608.20331v1
7  Q8  How is reward learning used to improve patient...      2608.20331v1

In [28]:
# Create Chroma vector store

chroma_client = chromadb.PersistentClient(
    path=str(processed_dir / "chroma_db")
)

chroma_collection = chroma_client.get_or_create_collection(
    name="baseline_rag"
)

vector_store = ChromaVectorStore(
    chroma_collection=chroma_collection
)

storage_context = StorageContext.from_defaults(
    vector_store=vector_store
)

In [29]:
# Create the baseline vector index

index = VectorStoreIndex(
    nodes,
    storage_context=storage_context,
    show_progress=True
)

retriever = index.as_retriever(
    similarity_top_k=5
)

Generating embeddings: 100%|██████████| 300/300 [00:45<00:00,  6.63it/s]

In [30]:
# Test baseline retrieval

test_question = benchmark_questions[0]["question"]

results = retriever.retrieve(test_question)

for rank, result in enumerate(results, start=1):
    print(f"Rank {rank}")
    print(f"arXiv ID: {result.node.metadata.get('arxiv_id')}")
    print(f"Title: {result.node.metadata.get('title')}")
    print(f"Page: {result.node.metadata.get('page_number')}")
    print()

Rank 1
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 26

Rank 2
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 26

Rank 3
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 26

Rank 4
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 18

Rank 5
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 18

In [31]:
# Evaluate baseline retrieval

retrieval_results = []

for item in benchmark_questions:

    results = retriever.retrieve(item["question"])

    retrieved_ids = [
        result.node.metadata.get("arxiv_id")
        for result in results
    ]

    expected_id = item["expected_arxiv_id"]

    retrieval_results.append({
        "id": item["id"],
        "question": item["question"],
        "expected_arxiv_id": expected_id,
        "retrieved_ids": retrieved_ids,
        "hit_at_1": expected_id in retrieved_ids[:1],
        "hit_at_3": expected_id in retrieved_ids[:3],
        "hit_at_5": expected_id in retrieved_ids[:5]
    })

evaluation_df = pd.DataFrame(retrieval_results)

evaluation_df

,id,question,expected_arxiv_id,retrieved_ids,hit_at_1,hit_at_3,hit_at_5
0,Q1,What problem does Pandora's AI Model Routing B...,2608.20316v1,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260...",True,True,True
1,Q2,How does Pandora's AI Model Routing Box improv...,2608.20316v1,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260...",True,True,True
2,Q3,What is AI4AI-Bench designed to evaluate?,2608.20318v1,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260...",True,True,True
3,Q4,How does AI4AI-Bench assess the performance of...,2608.20318v1,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260...",True,True,True
4,Q5,What information is used to induce task models...,2608.20319v1,"[2608.20319v1, 2608.20319v1, 2608.20319v1, 260...",True,True,True
5,Q6,What is the purpose of the agentic approach fo...,2608.20320v1,"[2608.20320v1, 2608.20320v1, 2608.20320v1, 260...",True,True,True
6,Q7,What problem does grounded checklist-aligned r...,2608.20331v1,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260...",True,True,True
7,Q8,How is reward learning used to improve patient...,2608.20331v1,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260...",True,True,True

In [32]:
# Calculate retrieval metrics

hit_at_1 = evaluation_df["hit_at_1"].mean()
hit_at_3 = evaluation_df["hit_at_3"].mean()
hit_at_5 = evaluation_df["hit_at_5"].mean()

print("Baseline Retrieval Performance")
print("-" * 40)
print(f"Hit@1: {hit_at_1:.2%}")
print(f"Hit@3: {hit_at_3:.2%}")
print(f"Hit@5: {hit_at_5:.2%}")

Baseline Retrieval Performance
----------------------------------------
Hit@1: 100.00%
Hit@3: 100.00%
Hit@5: 100.00%

In [33]:
# Save baseline retrieval results

evaluation_df.to_csv(
    processed_dir / "baseline_retrieval_evaluation.csv",
    index=False
)

Okay, so far 100% Hit for 1,3, and 5 indicates that it was able to retrieve a chunk from the expected paper. However, we do not know if the RAG system generates correct answers.

Will be using Groq generation and evalluate the answers below.

In [34]:
# Set up Groq

import os
from dotenv import load_dotenv

from llama_index.core import Settings
from llama_index.llms.groq import Groq

load_dotenv()

groq_api_key = os.getenv("GROQ_API_KEY")

llm = Groq(
    model="openai/gpt-oss-20b",
    api_key=groq_api_key
)

Settings.llm = llm

In [35]:
# Test Groq with one question

question = benchmark_questions[0]["question"]

results = retriever.retrieve(question)

context = "\n\n".join([
    f"""
Source:
Title: {result.node.metadata.get('title')}
arXiv ID: {result.node.metadata.get('arxiv_id')}
Page: {result.node.metadata.get('page_number')}

Text:
{result.node.text}
"""
    for result in results
])

prompt = f"""
You are a research intelligence assistant.

Answer the question using only the research context provided below.

Question:
{question}

Research context:
{context}

Instructions:
- Give a concise and factual answer.
- Do not use information outside the provided context.
- If the context does not contain enough information, say so.
- At the end of your answer, provide the source arXiv ID.
"""

response = llm.complete(prompt)

print(response.text)

2026-10-06 15:35:47,022 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Pandora’s AI Model Routing Box is designed to address the problem of efficiently allocating AI models to incoming tasks while taking into account the cost of estimating each model’s value. It seeks to minimize regret and inspection cost by routing queries to the most appropriate model under a budget‑constrained value‑estimation setting.

Source: arXiv 2608.20316v1

In [36]:
# Generate a RAG answer

def generate_rag_answer(question):

    results = retriever.retrieve(question)

    context = "\n\n".join([
        f"""
Source:
Title: {result.node.metadata.get('title')}
arXiv ID: {result.node.metadata.get('arxiv_id')}
Page: {result.node.metadata.get('page_number')}

Text:
{result.node.text}
"""
        for result in results
    ])

    prompt = f"""
You are a research intelligence assistant.

Answer the question using only the research context provided below.

Question:
{question}

Research context:
{context}

Instructions:
- Give a concise and factual answer.
- Do not use information outside the provided context.
- If the context does not contain enough information, say so.
- At the end of your answer, provide the source arXiv ID.
"""

    response = llm.complete(prompt)

    return response.text, results

In [37]:
# Generate answers for all benchmark questions

rag_results = []

for item in benchmark_questions:

    answer, results = generate_rag_answer(
        item["question"]
    )

    retrieved_ids = [
        result.node.metadata.get("arxiv_id")
        for result in results
    ]

    rag_results.append({
        "id": item["id"],
        "question": item["question"],
        "expected_arxiv_id": item["expected_arxiv_id"],
        "answer": answer,
        "retrieved_ids": retrieved_ids
    })

rag_results_df = pd.DataFrame(rag_results)

rag_results_df

2026-10-06 15:35:48,711 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:35:50,150 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:35:50,305 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:35:50,308 | INFO | Retrying request to /chat/completions in 2.000000 seconds
2026-10-06 15:35:53,302 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:35:53,517 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:35:53,518 | INFO | Retrying request to /chat/completions in 17.000000 seconds
2026-10-06 15:36:11,728 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:36:13,087 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:13,089 | INFO | Retrying request to /chat/completions in 13.000000 seconds
2026-10-06 15:36:26,723 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:36:27,866 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:27,905 | INFO | Retrying request to /chat/completions in 9.000000 seconds
2026-10-06 15:36:37,366 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:37,377 | INFO | Retrying request to /chat/completions in 4.000000 seconds
2026-10-06 15:36:42,088 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:36:43,608 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:43,613 | INFO | Retrying request to /chat/completions in 28.000000 seconds
2026-10-06 15:37:11,919 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:37:11,925 | INFO | Retrying request to /chat/completions in 3.000000 seconds
2026-10-06 15:37:15,789 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:37:16,606 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:37:16,611 | INFO | Retrying request to /chat/completions in 25.000000 seconds
2026-10-06 15:37:42,769 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

,id,question,expected_arxiv_id,answer,retrieved_ids
0,Q1,What problem does Pandora's AI Model Routing B...,2608.20316v1,Pandora’s AI Model Routing Box tackles the cha...,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260..."
1,Q2,How does Pandora's AI Model Routing Box improv...,2608.20316v1,Pandora’s AI Model Routing Box improves effici...,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260..."
2,Q3,What is AI4AI-Bench designed to evaluate?,2608.20318v1,AI4AI‑Bench is a benchmark that tests whether ...,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260..."
3,Q4,How does AI4AI-Bench assess the performance of...,2608.20318v1,AI4AI‑Bench evaluates an LLM agent by letting ...,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260..."
4,Q5,What information is used to induce task models...,2608.20319v1,Task models are induced from the low‑level eve...,"[2608.20319v1, 2608.20319v1, 2608.20319v1, 260..."
5,Q6,What is the purpose of the agentic approach fo...,2608.20320v1,The agentic approach is designed to unify the ...,"[2608.20320v1, 2608.20320v1, 2608.20320v1, 260..."
6,Q7,What problem does grounded checklist-aligned r...,2608.20331v1,Grounded checklist‑aligned reward learning (G‑...,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260..."
7,Q8,How is reward learning used to improve patient...,2608.20331v1,Reward learning in G‑CARL improves patient‑ori...,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260..."

In [38]:
# Review generated answers

for _, row in rag_results_df.iterrows():

    print(f"--- {row['id']} ---")
    print(f"Question: {row['question']}")
    print()
    print(f"Answer: {row['answer']}")
    print()
    print(f"Expected source: {row['expected_arxiv_id']}")
    print("-" * 60)

--- Q1 ---
Question: What problem does Pandora's AI Model Routing Box aim to solve?

Answer: Pandora’s AI Model Routing Box tackles the challenge of **efficiently allocating tasks to AI models when estimating each model’s value is expensive**—i.e., it seeks to optimize routing decisions while accounting for the cost of value estimation.

Source: arXiv 2608.20316v1

Expected source: 2608.20316v1
------------------------------------------------------------
--- Q2 ---
Question: How does Pandora's AI Model Routing Box improve the efficiency of AI model selection?

Answer: Pandora’s AI Model Routing Box improves efficiency by routing queries to the most valuable models using a cost‑aware value‑estimation framework.  The system employs value estimators (Section C.1) and carefully designed prompts (Section C.2) to predict each model’s expected benefit, allowing it to limit the number of inspections (see Supplemental Results D.1) and the monetary cost of value‑function evaluations (Supplemental Results D.3).  This targeted allocation reduces overall regret plus inspection cost, as shown in Table 4 on RAG routing, where the Box achieves the lowest combined metric among compared methods.

Source: arXiv 2608.20316v1.

Expected source: 2608.20316v1
------------------------------------------------------------
--- Q3 ---
Question: What is AI4AI-Bench designed to evaluate?

Answer: AI4AI‑Bench is a benchmark that tests whether a large‑language‑model agent can write code that improves the training algorithm of a repository’s own model.  The agent’s submission is evaluated by running the modified code under the same conditions as the original, and a fixed evaluator computes a metric (e.g., accuracy, solve‑rate, loss).  The benchmark measures whether the agent’s code yields a better metric than the baseline, thus assessing the agent’s ability to perform recursive self‑improvement in algorithm design.

Source: arXiv 2608.20318v1

Expected source: 2608.20318v1
------------------------------------------------------------
--- Q4 ---
Question: How does AI4AI-Bench assess the performance of LLM agents in algorithmic design?

Answer: AI4AI‑Bench evaluates an LLM agent by letting it modify the training algorithm of a frozen research repository and then measuring the quality of the resulting model with a **fixed, pre‑defined evaluator**.

1. **Baseline** – The original repository’s code is run once to produce a baseline model \(C\).
2. **Agent submission** – The agent’s code produces a modified training algorithm \(C'\).
3. **Evaluation** – Both \(C\) and \(C'\) are trained under identical conditions (same hardware, budget, and evaluator).
4. **Metric** – A fixed evaluator \(m\) computes a scalar score \(s(C)=m(a(C))\) and \(s(C')=m(a(C'))\).
5. **Improvement test** – The submission is considered better if
   \[
   s(C') > s(C) \quad \text{for upward‑directed metrics (↑)} \quad\text{or}\quad
   s(C') < s(C) \quad \text{for downward‑directed metrics (↓)} .
   \]
6. **Dense scoring** – Rather than a binary win/lose, the benchmark reports the actual metric value, providing a dense score that reflects the magnitude of improvement.

Thus, AI4AI‑Bench assesses performance by comparing the evaluator‑derived metric of the agent‑generated model to that of the baseline, using a dense, direction‑aware score.

**Source:** arXiv:2608.20318v1.

Expected source: 2608.20318v1
------------------------------------------------------------
--- Q5 ---
Question: What information is used to induce task models from computer-use traces?

Answer: Task models are induced from the low‑level events that are passively recorded during computer use: screenshots of the screen and the corresponding mouse or keyboard actions.

Source: arXiv 2608.20319v1

Expected source: 2608.20319v1
------------------------------------------------------------
--- Q6 ---
Question: What is the purpose of the agentic approach for active data collection and travel behaviour modelling?

Answer: The agentic approach is designed to unify the traditionally separate stages of travel‑behavior research into a single, transparent, and modular workflow. By linking a conversational data‑collection agent, a structured data‑processing agent, and a behavioral‑prediction agent, it enables an AI‑assisted survey to capture context‑dependent travel behavior and to feed that data directly into predictive models (e.g., LLMs, DCMs, ML benchmarks). The goal is to streamline the process from survey administration to behavioral prediction while allowing systematic evaluation of how different information types and AI configurations affect mode‑choice accuracy.

Source: arXiv 2608.20320v1

Expected source: 2608.20320v1
------------------------------------------------------------
--- Q7 ---
Question: What problem does grounded checklist-aligned reward learning address in patient-oriented medical research?

Answer: Grounded checklist‑aligned reward learning (G‑CARL) tackles the problem of producing **clinically accurate, evidence‑grounded interpretations of medical reports that also respect patient‑specific context and clinical checklists**. In patient‑oriented medical research, existing methods (e.g., simple fine‑tuning or “LLM‑as‑a‑Judge”) often misdiagnose abnormalities, ignore relevant patient history, or fail to answer the user’s primary question. G‑CARL aligns the model’s outputs with a checklist of clinical criteria and evidence‑based rewards, thereby improving diagnostic accuracy, contextual integration, and recommendation quality.

**Source:** arXiv:2608.20331v1

Expected source: 2608.20331v1
------------------------------------------------------------
--- Q8 ---
Question: How is reward learning used to improve patient-oriented medical outcomes?

Answer: Reward learning in G‑CARL improves patient‑oriented medical outcomes by providing fine‑grained, evidence‑grounded supervision for language models that interpret medical reports. The framework decomposes rewards into two types:

1. **Retrieval‑grounded claim reward** – each atomic medical claim in a generated response is verified against the uploaded report and a multi‑source medical datastore. This gives localized feedback on factual accuracy and discourages unsupported elaboration, ensuring that the information patients receive is verifiable and clinically reliable.

2. **Checklist‑guided reward** – for context‑dependent goals such as demand satisfaction and expression quality, G‑CARL generates instance‑specific weighted checklists (refined by clinicians). The reward emphasizes the checklist items most relevant to the current report and user question, providing transparent supervision that the response addresses the patient’s concerns appropriately.

By aligning rewards with verifiability and patient‑specific needs, G‑CARL consistently outperforms supervised and other reinforcement‑learning baselines, with gains confirmed by clinician preference and user comprehension studies. This leads to more accurate, relevant, and patient‑friendly medical interpretations, thereby improving patient‑oriented outcomes.

**Source:** arXiv ID 2608.20331v1.

Expected source: 2608.20331v1
------------------------------------------------------------

In [40]:
# Create answer evaluation table

answer_evaluation_df = rag_results_df[
    [
        "id",
        "question",
        "answer",
        "expected_arxiv_id"
    ]
].copy()

# Manual evaluation
# 0 = poor, 1 = partial, 2 = strong

answer_evaluation_df["answer_relevance"] = [
    2,  # Q1
    2,  # Q2
    2,  # Q3
    2,  # Q4
    2,  # Q5
    2,  # Q6
    2,  # Q7
    2   # Q8
]

answer_evaluation_df["faithfulness"] = [
    2,  # Q1
    2,  # Q2
    2,  # Q3
    2,  # Q4
    2,  # Q5
    2,  # Q6
    2,  # Q7
    2   # Q8
]

answer_evaluation_df["citation_accuracy"] = [
    2,  # Q1
    2,  # Q2
    2,  # Q3
    2,  # Q4
    2,  # Q5
    2,  # Q6
    2,  # Q7
    2   # Q8
]

answer_evaluation_df

,id,question,answer,expected_arxiv_id,answer_relevance,faithfulness,citation_accuracy
0,Q1,What problem does Pandora's AI Model Routing B...,Pandora’s AI Model Routing Box tackles the cha...,2608.20316v1,2,2,2
1,Q2,How does Pandora's AI Model Routing Box improv...,Pandora’s AI Model Routing Box improves effici...,2608.20316v1,2,2,2
2,Q3,What is AI4AI-Bench designed to evaluate?,AI4AI‑Bench is a benchmark that tests whether ...,2608.20318v1,2,2,2
3,Q4,How does AI4AI-Bench assess the performance of...,AI4AI‑Bench evaluates an LLM agent by letting ...,2608.20318v1,2,2,2
4,Q5,What information is used to induce task models...,Task models are induced from the low‑level eve...,2608.20319v1,2,2,2
5,Q6,What is the purpose of the agentic approach fo...,The agentic approach is designed to unify the ...,2608.20320v1,2,2,2
6,Q7,What problem does grounded checklist-aligned r...,Grounded checklist‑aligned reward learning (G‑...,2608.20331v1,2,2,2
7,Q8,How is reward learning used to improve patient...,Reward learning in G‑CARL improves patient‑ori...,2608.20331v1,2,2,2

In [41]:
# Calculate generation metrics

answer_relevance = (
    answer_evaluation_df["answer_relevance"].mean() / 2
)

faithfulness = (
    answer_evaluation_df["faithfulness"].mean() / 2
)

citation_accuracy = (
    answer_evaluation_df["citation_accuracy"].mean() / 2
)

print("Baseline RAG Generation Performance")
print("-" * 40)
print(f"Answer Relevance: {answer_relevance:.2%}")
print(f"Faithfulness: {faithfulness:.2%}")
print(f"Citation Accuracy: {citation_accuracy:.2%}")

Baseline RAG Generation Performance
----------------------------------------
Answer Relevance: 100.00%
Faithfulness: 100.00%
Citation Accuracy: 100.00%

In [42]:
# Final baseline RAG results

final_results = pd.DataFrame({
    "Metric": [
        "Hit@1",
        "Hit@3",
        "Hit@5",
        "Answer Relevance",
        "Faithfulness",
        "Citation Accuracy"
    ],
    "Score": [
        hit_at_1,
        hit_at_3,
        hit_at_5,
        answer_relevance,
        faithfulness,
        citation_accuracy
    ]
})

final_results["Score"] = final_results["Score"].map(
    lambda x: f"{x:.2%}"
)

final_results

              Metric    Score
0              Hit@1  100.00%
1              Hit@3  100.00%
2              Hit@5  100.00%
3   Answer Relevance  100.00%
4       Faithfulness  100.00%
5  Citation Accuracy  100.00%

In [43]:
# Save generated RAG answers

rag_results_df.to_csv(
    processed_dir / "baseline_rag_answers.csv",
    index=False
)

print("Saved: baseline_rag_answers.csv")

Saved: baseline_rag_answers.csv

In [44]:
# Save manual answer evaluation

answer_evaluation_df.to_csv(
    processed_dir / "baseline_answer_evaluation.csv",
    index=False
)

print("Saved: baseline_answer_evaluation.csv")

Saved: baseline_answer_evaluation.csv

In [45]:
# Save final baseline RAG results

final_results.to_csv(
    processed_dir / "baseline_rag_results.csv",
    index=False
)

print("Saved: baseline_rag_results.csv")

Saved: baseline_rag_results.csv

## Baseline RAG Evaluation Summary

The baseline RAG pipeline was evaluated using an eight-question benchmark covering the five research papers in the dataset. Retrieval performance was measured using Hit@1, Hit@3, and Hit@5, while generated responses were manually evaluated for answer relevance, faithfulness to the retrieved context, and citation accuracy.

The baseline achieved 100% Hit@1, Hit@3, and Hit@5 on the benchmark. The generated responses also achieved 100% on answer relevance, faithfulness, and citation accuracy based on the manual evaluation.

These results indicate that the baseline pipeline successfully retrieved the expected source paper and generated relevant, context-supported answers for the benchmark questions. However, the benchmark contains only eight questions, so these results should be interpreted as baseline performance on the current evaluation set rather than evidence of general RAG performance.

## Evaluation Methodology

### Retrieval Evaluation

Retrieval performance was evaluated using three metrics:

- **Hit@1:** whether the expected source paper was ranked first.
- **Hit@3:** whether the expected source paper appeared within the top three retrieved results.
- **Hit@5:** whether the expected source paper appeared within the top five retrieved results.

### Generation Evaluation

Generated answers were manually evaluated using a 0–2 scale:

- **Answer Relevance:** whether the response directly answers the benchmark question.
- **Faithfulness:** whether the response is supported by the retrieved research context.
- **Citation Accuracy:** whether the cited arXiv source corresponds to the expected source paper.

A score of 2 represents a strong result, 1 represents a partial result, and 0 represents an incorrect or unsupported result.