# Part 1: Data Assessment

## Objective

Examine existing arXiv research papers in the Artificial Intelligence category, identify the available file types and metadata,
assess the quality of the data, and determine what information is usable for the RAG pipeline.

In [17]:
# setup, imports

import io
import time
import requests
import feedparser
from pathlib import Path
import pandas as pd
from pypdf import PdfReader

cwd = Path.cwd()
project_root = cwd.parent if cwd.name == "notebooks" else cwd

In [ ]:
# define arxiv fetch + extraction functions

ARXIV_API_URL = "http://export.arxiv.org/api/query"

def sanitize_text(text):
    return text.encode("utf-8", errors="ignore").decode("utf-8") if isinstance(text, str) else text

def fetch_arxiv_metadata(query, total_results, batch_size=100):
    papers = []
    for start in range(0, total_results, batch_size):
        params = {
            "search_query": query,
            "start": start,
            "max_results": min(batch_size, total_results - start),
            "sortBy": "submittedDate",
            "sortOrder": "descending",
        }
        response = requests.get(ARXIV_API_URL, params=params, timeout=30)
        response.raise_for_status()
        feed = feedparser.parse(response.text)

        for entry in feed.entries:
            arxiv_id = entry.id.split("/abs/")[-1]
            pdf_url = next(
                (link.href for link in entry.links if link.get("title") == "pdf"), None
            )
            papers.append({
                "arxiv_id": arxiv_id,
                "title": entry.title.replace("\n", " ").strip(),
                "author": "; ".join(a.name for a in entry.authors),
                "published": entry.published,
                "pdf_url": pdf_url,
            })

        print(f"fetched metadata for {len(papers)}/{total_results} papers")
        time.sleep(3)
    return papers


def extract_pdf_pages_from_url(paper):
    response = requests.get(paper["pdf_url"], timeout=30)
    response.raise_for_status()
    reader = PdfReader(io.BytesIO(response.content))

    records = []
    for page_number, page in enumerate(reader.pages, start=1):
        raw_text = sanitize_text(page.extract_text() or "")
        records.append({
            "arxiv_id": paper["arxiv_id"],
            "title": sanitize_text(paper["title"]),
            "author": sanitize_text(paper["author"]),
            "published": paper["published"],
            "page_number": page_number,
            "num_pages": len(reader.pages),
            "raw_text": raw_text,
        })
    return records

In [ ]:
# fetch metadata and extract pages

# skip this cell if you're about to run the ArxivIngestionPipeline class (in Part 2) below instead, since running both fetches everything twice

paper_metadata = fetch_arxiv_metadata("cat:cs.AI", total_results=500) # importing 500 papers for now for testing the api, but when we scale to ingesting updated+new papers every day, we'd have to export to a .py script and run a scheduled workflow for daily imports
metadata_df = pd.DataFrame(paper_metadata)

all_pages = []
for i, paper in enumerate(paper_metadata, start=1):
    if paper["pdf_url"] is None:
        continue
    try:
        all_pages.extend(extract_pdf_pages_from_url(paper))
    except Exception as e:
        print(f"failed to extract {paper['arxiv_id']}: {e}")
    if i % 25 == 0:
        print(f"processed {i}/{len(paper_metadata)} papers")
    time.sleep(3) # arxiv rate limit policy asks for no more than 1 request every 3 seconds

pages_df = pd.DataFrame(all_pages)
print(f"extracted {len(pages_df)} pages from {pages_df['arxiv_id'].nunique()} papers")

In [37]:
# aggregate quality checks (depends on fetching cell above, also skip if running ArxivIngestionPipeline below)

paper_quality = pages_df.groupby("arxiv_id").agg(
    num_pages=("page_number", "max"),
    pages_with_text=("raw_text", lambda s: (s.str.strip() != "").sum()),
).reset_index()
paper_quality["readable"] = paper_quality["pages_with_text"] > 0

print("papers fetched:", pages_df["arxiv_id"].nunique())
print("unreadable papers:", (~paper_quality["readable"]).sum())
print("duplicate arxiv_ids:", metadata_df["arxiv_id"].duplicated().sum())
print("missing titles:", metadata_df["title"].isna().sum())
print("missing pdf links:", metadata_df["pdf_url"].isna().sum())

paper_quality[~paper_quality["readable"]]

papers fetched: 500
unreadable papers: 0
duplicate arxiv_ids: 0
missing titles: 0
missing pdf links: 0

Empty DataFrame
Columns: [arxiv_id, num_pages, pages_with_text, readable]
Index: []

In [38]:
# spot check extracted text

sample_papers = pages_df[pages_df["page_number"] == 1].head(5)

for _, row in sample_papers.iterrows():
    print("\nARXIV ID:", row["arxiv_id"])
    print("TITLE:", row["title"])
    print(row["raw_text"][:300])
    print("-" * 80)

ARXIV ID: 2610.22372v1
TITLE: LIBERO-PeRM: Benchmarking Personalized Robotic Manipulation
LIBERO-PeRM: Benchmarking Personalized
Robotic Manipulation
Zhixu Li1,∗,†, Keqian Tang1,∗, Litian Gong1,∗, Jingyu Yao2, Wenqian Zhang1,
Tianze Xu5, Zehao Wang3, Yuping Wang4, Junge Zhang3, and Jiachen Li3,1,‡
1University of California, Riverside 2Yale University 3Georgia Institute of Technology
4Uni
--------------------------------------------------------------------------------

ARXIV ID: 2610.22367v1
TITLE: Discovering state-of-the-art quantum circuits with large language models
Discovering state-of-the-art quantum circuits with large language models
Andi Gu,1, 2, 3,∗ Alek H. Kemeny,4 Susanne F. Yelin,1, 2 and Mikhail D. Lukin1, 2, 5
1Harvard Quantum Initiative for Science and Engineering, Cambridge, MA 02138, USA
2Department of Physics, Harvard University, Cambridge, MA 02
--------------------------------------------------------------------------------

ARXIV ID: 2610.22364v1
TITLE: T2-z: Test-Time Optimization of Environment Latents for Robotic World Models
Preprint
T2-Z: TEST-TIMEOPTIMIZATION OFENVIRONMENT
LATENTS FORROBOTICWORLDMODELS
Chenyuan Zhou1*, Yining Hong1*, Huang Huang1♡, Yunfan Jiang1♡,
Wenlong Huang1♡, David Held2, Vitor Campagnolo Guizilini3, Yue Wang4,
Li Fei-Fei1, Jiajun Wu1†, Leonidas Guibas1†, Yejin Choi1†
* Co-First Contribution♡Co-S
--------------------------------------------------------------------------------

ARXIV ID: 2610.22362v1
TITLE: CoDA: Co-Evolution of Data Engines and Action Policies
Vector conversion of 01_illinois_block_i.svg
CoDA: Co-Evolution of Data Engines and Action Policies
Tianjiao Yu1 Zhilin Ou2 Yifan Shen1 Xinzhuo Li1
Yuanzhe Liu1 Onkar Kishor Susladkar1 Fan Wang3 Ismini Lourentzou1
1University of Illinois Urbana-Champaign 2The Chinese University of Hong Kong, Shenzhe
--------------------------------------------------------------------------------

ARXIV ID: 2610.22353v1
TITLE: Rethinking Routing Exploration in Modern Mixture-of-Experts
RETHINKINGROUTINGEXPLORATION
INMODERNMIXTURE-OF-EXPERTS
Bingcong Li1,2, Hao Ma 2, Michael Muehlebach 3,4, Niao He 1, Yi Ma 2
1 ETH Zurich 2 The University of Hong Kong
3 Max Planck Institute for Intelligent Systems 4 WU Vienna
{bingcong.li, niao.he}@inf.ethz.ch, {haoma, mayi}@hku.hk,
michael.muehleb
--------------------------------------------------------------------------------

## Data Quality Findings

- Imported 500 most recent arXiv research papers, all in PDF format.
- All 500 PDFs opened successfully and contained extractable text on every page.
- Titles and author information were available for all papers.
- No duplicate filenames or paper titles were found.
- No missing values were found in the fields collected during the assessment.

# Part 2: Data Prep

In [31]:
# extra imports, output dir

import re
import json
import unicodedata
from dataclasses import dataclass
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger("ingestion_pipeline")

processed_dir = project_root / "data_processed"
processed_dir.mkdir(exist_ok=True)

print("Processed output directory:", processed_dir)

Processed output directory: /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed

In [39]:
# clean text

def clean_text(text: str) -> str:
    """Clean raw PDF-extracted text based on artifacts identified in the Part 1 assessment."""
    if not text or not text.strip():
        return ""

    text = unicodedata.normalize("NFKC", text)
    text = re.sub(r"-\s*\n\s*", "", text)              # rejoin hyphenated line breaks
    text = re.sub(r"(\w)-\s+(\w)", r"\1-\2", text)      # rejoin hyphenated stray spacing
    text = re.sub(r"\s[\*†‡]\s", " ", text)             # strip isolated footnote markers
    text = re.sub(r"\n+", " ", text)                    # collapse newlines
    text = re.sub(r"[ \t]+", " ", text)                 # collapse repeated whitespace

    return text.strip()


pages_df["cleaned_text"] = pages_df["raw_text"].apply(clean_text)
pages_df["char_count"] = pages_df["cleaned_text"].str.len()
pages_df["word_count"] = pages_df["cleaned_text"].str.split().str.len()

print("BEFORE:\n", pages_df.loc[0, "raw_text"][:300])
print("\nAFTER:\n", pages_df.loc[0, "cleaned_text"][:300])

BEFORE:
 LIBERO-PeRM: Benchmarking Personalized
Robotic Manipulation
Zhixu Li1,∗,†, Keqian Tang1,∗, Litian Gong1,∗, Jingyu Yao2, Wenqian Zhang1,
Tianze Xu5, Zehao Wang3, Yuping Wang4, Junge Zhang3, and Jiachen Li3,1,‡
1University of California, Riverside 2Yale University 3Georgia Institute of Technology
4Uni

AFTER:
 LIBERO-PeRM: Benchmarking Personalized Robotic Manipulation Zhixu Li1,∗,†, Keqian Tang1,∗, Litian Gong1,∗, Jingyu Yao2, Wenqian Zhang1, Tianze Xu5, Zehao Wang3, Yuping Wang4, Junge Zhang3, and Jiachen Li3,1,‡ 1University of California, Riverside 2Yale University 3Georgia Institute of Technology 4Uni

In [40]:
# chunk text

CHUNK_SIZE_WORDS = 250
CHUNK_OVERLAP_WORDS = 40

def chunk_text(text: str, chunk_size: int = CHUNK_SIZE_WORDS, overlap: int = CHUNK_OVERLAP_WORDS) -> list[str]:
    words = text.split()
    if not words:
        return []
    if len(words) <= chunk_size:
        return [text]

    chunks = []
    start = 0
    while start < len(words):
        end = start + chunk_size
        chunks.append(" ".join(words[start:end]))
        start += chunk_size - overlap
    return chunks


chunk_records = []
for _, row in pages_df.iterrows():
    page_chunks = chunk_text(row["cleaned_text"])
    for chunk_index, chunk in enumerate(page_chunks):
        chunk_records.append({
            "chunk_id": f"{row['arxiv_id']}_p{row['page_number']}_c{chunk_index}",
            "arxiv_id": row["arxiv_id"],
            "title": row["title"],
            "author": row["author"],
            "published": row["published"]
            "page_number": row["page_number"],
            "chunk_index": chunk_index,
            "text": chunk,
            "word_count": len(chunk.split())
        })

chunks_df = pd.DataFrame(chunk_records)
print(f"Produced {len(chunks_df)} chunks from {pages_df['arxiv_id'].nunique()} papers")
chunks_df[["chunk_id", "page_number", "word_count"]].head(10)

Produced 35317 chunks from 500 papers

             chunk_id  page_number  word_count
0  2610.22372v1_p1_c0            1         250
1  2610.22372v1_p1_c1            1         250
2  2610.22372v1_p1_c2            1          40
3  2610.22372v1_p2_c0            2         250
4  2610.22372v1_p2_c1            2         250
5  2610.22372v1_p2_c2            2          82
6  2610.22372v1_p3_c0            3         250
7  2610.22372v1_p3_c1            3         250
8  2610.22372v1_p3_c2            3         163
9  2610.22372v1_p4_c0            4         250

In [41]:
# validate

assert not chunks_df.empty, "No chunks were produced"
assert chunks_df["chunk_id"].is_unique, "Duplicate chunk IDs found"
assert (chunks_df["word_count"] > 0).all(), "Empty chunks found"
assert chunks_df["title"].notna().all(), "Chunks missing title metadata"
assert chunks_df["arxiv_id"].notna().all(), "Chunks missing arxiv_id"
assert (chunks_df["word_count"] <= CHUNK_SIZE_WORDS + 5).all(), "Chunk exceeds target size unexpectedly"

print("All validation checks passed.")
print("\nChunk word-count distribution:")
print(chunks_df["word_count"].describe())

All validation checks passed.

Chunk word-count distribution:
count    35317.000000
mean       199.554634
std         76.334569
min          1.000000
25%        155.000000
50%        250.000000
75%        250.000000
max        250.000000
Name: word_count, dtype: float64

In [42]:
#save

jsonl_path = processed_dir / "chunks.jsonl"
parquet_path = processed_dir / "chunks.parquet"

with open(jsonl_path, "w") as f:
    for record in chunks_df.to_dict(orient="records"):
        f.write(json.dumps(record) + "\n")

chunks_df.to_parquet(parquet_path, index=False)

logger.info(f"Saved {len(chunks_df)} chunks to {jsonl_path}")
logger.info(f"Saved {len(chunks_df)} chunks to {parquet_path}")

2026-10-19 09:56:53,278 | INFO | Saved 35317 chunks to /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chunks.jsonl
2026-10-19 09:56:53,282 | INFO | Saved 35317 chunks to /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chunks.parquet

In [ ]:
# wrap as a repeatable pipeline 

@dataclass
class IngestionConfig:
    query: str
    total_results: int
    output_dir: Path
    chunk_size_words: int = CHUNK_SIZE_WORDS
    chunk_overlap_words: int = CHUNK_OVERLAP_WORDS


class ArxivIngestionPipeline:
    def __init__(self, config: IngestionConfig):
        self.config = config
        self.pages_df = None
        self.chunks_df = None

    def extract(self):
        metadata = fetch_arxiv_metadata(self.config.query, self.config.total_results)
        records = []
        for i, paper in enumerate(metadata, start=1):
            if paper["pdf_url"] is None:
                continue
            try:
                records.extend(extract_pdf_pages_from_url(paper))
            except Exception as e:
                logger.warning(f"Failed to extract {paper['arxiv_id']}: {e}")
            if i % 25 == 0:
                logger.info(f"Processed {i}/{len(metadata)} papers")
            time.sleep(3)
        self.pages_df = pd.DataFrame(records)
        return self

    def clean(self):
        self.pages_df["cleaned_text"] = self.pages_df["raw_text"].apply(clean_text)
        return self

    def chunk(self):
        records = []
        for _, row in self.pages_df.iterrows():
            page_chunks = chunk_text(
                row["cleaned_text"],
                chunk_size=self.config.chunk_size_words,
                overlap=self.config.chunk_overlap_words
            )
            for chunk_index, chunk in enumerate(page_chunks):
                records.append({
                    "chunk_id": f"{row['arxiv_id']}_p{row['page_number']}_c{chunk_index}",
                    "arxiv_id": row["arxiv_id"],
                    "title": row["title"],
                    "author": row["author"],
                    "published": row["published"]
                    "page_number": row["page_number"],
                    "chunk_index": chunk_index,
                    "text": chunk,
                    "word_count": len(chunk.split())
                })
        self.chunks_df = pd.DataFrame(records)
        return self

    def validate(self):
        assert not self.chunks_df.empty, "No chunks produced"
        assert self.chunks_df["chunk_id"].is_unique, "Duplicate chunk IDs"
        assert (self.chunks_df["word_count"] > 0).all(), "Empty chunks found"
        assert self.chunks_df["title"].notna().all(), "Missing title metadata"
        return self

    def load(self):
        self.config.output_dir.mkdir(exist_ok=True)
        jsonl_path = self.config.output_dir / "chunks.jsonl"
        with open(jsonl_path, "w") as f:
            for record in self.chunks_df.to_dict(orient="records"):
                f.write(json.dumps(record) + "\n")
        self.chunks_df.to_parquet(self.config.output_dir / "chunks.parquet", index=False)
        logger.info(f"Saved {len(self.chunks_df)} chunks to {self.config.output_dir}")
        return self

    def run(self):
        return self.extract().clean().chunk().validate().load()

In [43]:
# only run this if you haven't already run the manual walkthrough above in this session, since running both fetches everything twice

config = IngestionConfig(query="cat:cs.AI", total_results=500, output_dir=processed_dir)
pipeline = ArxivIngestionPipeline(config)
pipeline.run()
print(f"Pipeline complete: {len(pipeline.chunks_df)} chunks ready for embedding")

fetched metadata for 100/500 papers
fetched metadata for 200/500 papers
fetched metadata for 300/500 papers
fetched metadata for 400/500 papers
fetched metadata for 500/500 papers

2026-10-19 10:22:58,474 | WARNING | Ignoring wrong pointing object 6 0 (offset 0)
2026-10-19 10:22:58,475 | WARNING | Ignoring wrong pointing object 8 0 (offset 0)
2026-10-19 10:22:58,475 | WARNING | Ignoring wrong pointing object 10 0 (offset 0)
2026-10-19 10:22:58,476 | WARNING | Ignoring wrong pointing object 12 0 (offset 0)
2026-10-19 10:22:58,477 | WARNING | Ignoring wrong pointing object 14 0 (offset 0)
2026-10-19 10:22:58,477 | WARNING | Ignoring wrong pointing object 16 0 (offset 0)
2026-10-19 10:22:58,477 | WARNING | Ignoring wrong pointing object 18 0 (offset 0)
2026-10-19 10:22:58,478 | WARNING | Ignoring wrong pointing object 28 0 (offset 0)
2026-10-19 10:22:58,478 | WARNING | Ignoring wrong pointing object 30 0 (offset 0)
2026-10-19 10:22:58,478 | WARNING | Ignoring wrong pointing object 32 0 (offset 0)
2026-10-19 10:22:58,478 | WARNING | Ignoring wrong pointing object 34 0 (offset 0)
2026-10-19 10:22:58,478 | WARNING | Ignoring wrong pointing object 36 0 (offset 0)
2026-10-19 10:22:58,478 | WARNING | Ignoring wrong pointing object 41 0 (offset 0)
2026-10-19 10:22:58,479 | WARNING | Ignoring wrong pointing object 46 0 (offset 0)
2026-10-19 10:22:58,479 | WARNING | Ignoring wrong pointing object 79 0 (offset 0)
2026-10-19 10:24:03,483 | INFO | Processed 25/500 papers
2026-10-19 10:24:10,040 | WARNING | Skipping broken line b'0d0e   0d2e   1d434': Odd-length string
2026-10-19 10:24:10,040 | WARNING | Skipping broken line b'0d2f   0d40   1d456': Odd-length string
2026-10-19 10:24:10,040 | WARNING | Skipping broken line b'0d41   0d42   1d538': Odd-length string
2026-10-19 10:24:10,041 | WARNING | Skipping broken line b'0d43   0d46   1d53b': Odd-length string
2026-10-19 10:24:10,041 | WARNING | Skipping broken line b'0d47   0d4b   1d540': Odd-length string
2026-10-19 10:24:10,041 | WARNING | Skipping broken line b'0d4d   0d53   1d54a': Odd-length string
2026-10-19 10:24:10,041 | WARNING | Skipping broken line b'0d54   0d6d   1d552': Odd-length string
2026-10-19 10:24:10,041 | WARNING | Skipping broken line b'0d6e   0d6f   1d6a4': Odd-length string
2026-10-19 10:24:10,041 | WARNING | Skipping broken line b'0d70   0d79   1d7d8': Odd-length string
2026-10-19 10:24:10,041 | WARNING | Got invalid hex string: Odd-length string (b'1d546')
2026-10-19 10:24:45,232 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-19 10:24:46,015 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-19 10:24:46,529 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-19 10:24:47,044 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-19 10:24:47,514 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-19 10:24:48,031 | WARNING | Exceeded 5000 form XObject invocations while extracting text; further form content is skipped.
2026-10-19 10:25:16,489 | WARNING | Ignoring wrong pointing object 6 0 (offset 0)
2026-10-19 10:25:16,491 | WARNING | Ignoring wrong pointing object 8 0 (offset 0)
2026-10-19 10:25:16,493 | WARNING | Ignoring wrong pointing object 10 0 (offset 0)
2026-10-19 10:25:16,494 | WARNING | Ignoring wrong pointing object 12 0 (offset 0)
2026-10-19 10:25:16,494 | WARNING | Ignoring wrong pointing object 14 0 (offset 0)
2026-10-19 10:25:16,495 | WARNING | Ignoring wrong pointing object 27 0 (offset 0)
2026-10-19 10:25:16,496 | WARNING | Ignoring wrong pointing object 29 0 (offset 0)
2026-10-19 10:25:16,496 | WARNING | Ignoring wrong pointing object 31 0 (offset 0)
2026-10-19 10:25:16,497 | WARNING | Ignoring wrong pointing object 33 0 (offset 0)
2026-10-19 10:25:16,497 | WARNING | Ignoring wrong pointing object 35 0 (offset 0)
2026-10-19 10:25:16,498 | WARNING | Ignoring wrong pointing object 37 0 (offset 0)
2026-10-19 10:25:16,498 | WARNING | Ignoring wrong pointing object 39 0 (offset 0)
2026-10-19 10:25:16,499 | WARNING | Ignoring wrong pointing object 41 0 (offset 0)
2026-10-19 10:25:16,499 | WARNING | Ignoring wrong pointing object 43 0 (offset 0)
2026-10-19 10:25:16,501 | WARNING | Ignoring wrong pointing object 51 0 (offset 0)
2026-10-19 10:25:16,502 | WARNING | Ignoring wrong pointing object 59 0 (offset 0)
2026-10-19 10:25:16,502 | WARNING | Ignoring wrong pointing object 61 0 (offset 0)
2026-10-19 10:25:16,503 | WARNING | Ignoring wrong pointing object 63 0 (offset 0)
2026-10-19 10:25:16,503 | WARNING | Ignoring wrong pointing object 94 0 (offset 0)
2026-10-19 10:25:16,503 | WARNING | Ignoring wrong pointing object 96 0 (offset 0)
2026-10-19 10:25:39,954 | INFO | Processed 50/500 papers
2026-10-19 10:25:53,504 | WARNING | Ignoring wrong pointing object 6 0 (offset 0)
2026-10-19 10:25:53,505 | WARNING | Ignoring wrong pointing object 8 0 (offset 0)
2026-10-19 10:25:53,505 | WARNING | Ignoring wrong pointing object 10 0 (offset 0)
2026-10-19 10:25:53,505 | WARNING | Ignoring wrong pointing object 12 0 (offset 0)
2026-10-19 10:25:53,506 | WARNING | Ignoring wrong pointing object 14 0 (offset 0)
2026-10-19 10:25:53,506 | WARNING | Ignoring wrong pointing object 21 0 (offset 0)
2026-10-19 10:25:53,506 | WARNING | Ignoring wrong pointing object 23 0 (offset 0)
2026-10-19 10:25:53,506 | WARNING | Ignoring wrong pointing object 25 0 (offset 0)
2026-10-19 10:25:53,507 | WARNING | Ignoring wrong pointing object 27 0 (offset 0)
2026-10-19 10:25:53,507 | WARNING | Ignoring wrong pointing object 34 0 (offset 0)
2026-10-19 10:25:53,508 | WARNING | Ignoring wrong pointing object 39 0 (offset 0)
2026-10-19 10:25:53,508 | WARNING | Ignoring wrong pointing object 46 0 (offset 0)
2026-10-19 10:25:53,508 | WARNING | Ignoring wrong pointing object 164 0 (offset 0)
2026-10-19 10:25:53,509 | WARNING | Ignoring wrong pointing object 166 0 (offset 0)
2026-10-19 10:25:53,509 | WARNING | Ignoring wrong pointing object 168 0 (offset 0)
2026-10-19 10:25:53,509 | WARNING | Ignoring wrong pointing object 175 0 (offset 0)
2026-10-19 10:25:53,509 | WARNING | Ignoring wrong pointing object 177 0 (offset 0)
2026-10-19 10:25:53,510 | WARNING | Ignoring wrong pointing object 179 0 (offset 0)
2026-10-19 10:25:53,510 | WARNING | Ignoring wrong pointing object 184 0 (offset 0)
2026-10-19 10:25:53,510 | WARNING | Ignoring wrong pointing object 186 0 (offset 0)
2026-10-19 10:25:53,510 | WARNING | Ignoring wrong pointing object 188 0 (offset 0)
2026-10-19 10:25:53,511 | WARNING | Ignoring wrong pointing object 191 0 (offset 0)
2026-10-19 10:25:53,511 | WARNING | Ignoring wrong pointing object 199 0 (offset 0)
2026-10-19 10:25:53,511 | WARNING | Ignoring wrong pointing object 207 0 (offset 0)
2026-10-19 10:25:53,512 | WARNING | Ignoring wrong pointing object 292 0 (offset 0)
2026-10-19 10:25:53,512 | WARNING | Ignoring wrong pointing object 293 0 (offset 0)
2026-10-19 10:25:53,512 | WARNING | Ignoring wrong pointing object 294 0 (offset 0)
2026-10-19 10:25:53,512 | WARNING | Ignoring wrong pointing object 295 0 (offset 0)
2026-10-19 10:25:53,513 | WARNING | Ignoring wrong pointing object 296 0 (offset 0)
2026-10-19 10:25:53,513 | WARNING | Ignoring wrong pointing object 297 0 (offset 0)
2026-10-19 10:25:53,514 | WARNING | Ignoring wrong pointing object 298 0 (offset 0)
2026-10-19 10:25:53,514 | WARNING | Ignoring wrong pointing object 299 0 (offset 0)
2026-10-19 10:25:53,514 | WARNING | Ignoring wrong pointing object 300 0 (offset 0)
2026-10-19 10:25:53,515 | WARNING | Ignoring wrong pointing object 301 0 (offset 0)
2026-10-19 10:25:53,515 | WARNING | Ignoring wrong pointing object 302 0 (offset 0)
2026-10-19 10:25:53,515 | WARNING | Ignoring wrong pointing object 303 0 (offset 0)
2026-10-19 10:25:53,516 | WARNING | Ignoring wrong pointing object 304 0 (offset 0)
2026-10-19 10:25:53,516 | WARNING | Ignoring wrong pointing object 305 0 (offset 0)
2026-10-19 10:25:53,516 | WARNING | Ignoring wrong pointing object 306 0 (offset 0)
2026-10-19 10:25:53,516 | WARNING | Ignoring wrong pointing object 307 0 (offset 0)
2026-10-19 10:25:53,517 | WARNING | Ignoring wrong pointing object 308 0 (offset 0)
2026-10-19 10:25:53,517 | WARNING | Ignoring wrong pointing object 309 0 (offset 0)
2026-10-19 10:25:53,517 | WARNING | Ignoring wrong pointing object 310 0 (offset 0)
2026-10-19 10:25:53,518 | WARNING | Ignoring wrong pointing object 311 0 (offset 0)
2026-10-19 10:25:53,518 | WARNING | Ignoring wrong pointing object 312 0 (offset 0)
2026-10-19 10:25:53,518 | WARNING | Ignoring wrong pointing object 313 0 (offset 0)
2026-10-19 10:25:53,518 | WARNING | Ignoring wrong pointing object 314 0 (offset 0)
2026-10-19 10:25:53,519 | WARNING | Ignoring wrong pointing object 315 0 (offset 0)
2026-10-19 10:25:53,519 | WARNING | Ignoring wrong pointing object 316 0 (offset 0)
2026-10-19 10:25:53,519 | WARNING | Ignoring wrong pointing object 317 0 (offset 0)
2026-10-19 10:25:53,519 | WARNING | Ignoring wrong pointing object 318 0 (offset 0)
2026-10-19 10:25:53,519 | WARNING | Ignoring wrong pointing object 319 0 (offset 0)
2026-10-19 10:25:53,520 | WARNING | Ignoring wrong pointing object 320 0 (offset 0)
2026-10-19 10:25:53,520 | WARNING | Ignoring wrong pointing object 321 0 (offset 0)
2026-10-19 10:25:53,520 | WARNING | Ignoring wrong pointing object 322 0 (offset 0)
2026-10-19 10:25:53,520 | WARNING | Ignoring wrong pointing object 323 0 (offset 0)
2026-10-19 10:25:53,521 | WARNING | Ignoring wrong pointing object 324 0 (offset 0)
2026-10-19 10:25:53,521 | WARNING | Ignoring wrong pointing object 325 0 (offset 0)
2026-10-19 10:25:53,521 | WARNING | Ignoring wrong pointing object 326 0 (offset 0)
2026-10-19 10:25:53,521 | WARNING | Ignoring wrong pointing object 327 0 (offset 0)
2026-10-19 10:25:53,522 | WARNING | Ignoring wrong pointing object 328 0 (offset 0)
2026-10-19 10:25:53,522 | WARNING | Ignoring wrong pointing object 329 0 (offset 0)
2026-10-19 10:25:53,522 | WARNING | Ignoring wrong pointing object 330 0 (offset 0)
2026-10-19 10:25:53,522 | WARNING | Ignoring wrong pointing object 331 0 (offset 0)
2026-10-19 10:25:53,522 | WARNING | Ignoring wrong pointing object 332 0 (offset 0)
2026-10-19 10:25:53,522 | WARNING | Ignoring wrong pointing object 333 0 (offset 0)
2026-10-19 10:26:37,228 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,230 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,231 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,231 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,231 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,231 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:37,234 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,236 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,236 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,236 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,237 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,237 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:37,441 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,443 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,443 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,444 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,444 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,444 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:37,447 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,449 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,450 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,450 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,450 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,450 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:37,584 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,586 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,586 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,586 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,587 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,587 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:37,589 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,591 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,592 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,592 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,592 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,592 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:37,817 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,819 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,820 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,820 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,820 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,820 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:37,823 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:37,825 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:37,825 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:37,825 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:37,826 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:37,826 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:38,029 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:38,031 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:38,031 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:38,031 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:38,032 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:38,032 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:38,035 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:38,037 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:38,037 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:38,037 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:38,038 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:38,038 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:38,138 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:38,140 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:38,140 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:38,140 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:38,141 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:38,141 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:38,144 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:38,146 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:38,146 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:38,146 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:38,146 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:38,147 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:38,242 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:38,244 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:38,244 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:38,244 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:38,244 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:38,245 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:38,248 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:38,249 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:38,250 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:38,250 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:38,250 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:38,250 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:39,092 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:39,094 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:39,094 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:39,094 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:39,095 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:39,095 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:39,098 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:39,101 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:39,101 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:39,101 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:39,102 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:39,102 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:39,105 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:39,107 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:39,107 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:39,107 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')
2026-10-19 10:26:39,107 | WARNING | Got invalid hex string: Odd-length string (b'1f850')
2026-10-19 10:26:39,107 | WARNING | Got invalid hex string: Odd-length string (b'1f852')
2026-10-19 10:26:39,110 | WARNING | Skipping broken line b'0744   075d   1f130': Odd-length string
2026-10-19 10:26:39,112 | WARNING | Got invalid hex string: Odd-length string (b'1f12f')
2026-10-19 10:26:39,112 | WARNING | Got invalid hex string: Odd-length string (b'1f16b')
2026-10-19 10:26:39,112 | WARNING | Got invalid hex string: Odd-length string (b'1f16a')

Pipeline complete: 35449 chunks ready for embedding

## Summary

- Extracted per-page text and metadata for all 500 papers.
- Cleaned hyphenation breaks, stray footnote symbols, and irregular whitespace found during Part 1.
- Chunked text at the page level (250 words, 40-word overlap) so every chunk keeps an accurate page number for citations.
- Validated that every chunk has complete metadata, a unique ID, and non-empty text.
- Packaged the flow into `ArxivIngestionPipeline` for repeatable reruns.
- Output: `data_processed/chunks.jsonl` and `chunks.parquet`, ready for embedding.

# Part 3: RAG Model Build

In [62]:
# install dependencies
# llamaindex is the core framework that wraps the other components (embeddings, vector stores, LLMs) together
# chromadb is a vector database for the embeddings

%pip install llama-index-core llama-index-embeddings-huggingface llama-index-vector-stores-chroma llama-index-llms-groq chromadb

import os
import chromadb

from llama_index.core import VectorStoreIndex, StorageContext, Settings
from llama_index.core.schema import TextNode
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.core.postprocessor import SentenceTransformerRerank
from llama_index.retrievers.bm25 import BM25Retriever
from llama_index.core.retrievers import QueryFusionRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.llms.groq import Groq

145197.37s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Requirement already satisfied: llama-index-core in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (0.14.25)
Requirement already satisfied: llama-index-embeddings-huggingface in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (0.8.0)
Requirement already satisfied: llama-index-vector-stores-chroma in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (0.6.0)
Requirement already satisfied: llama-index-llms-groq in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (0.6.1)
Requirement already satisfied: chromadb in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (1.5.9)
Requirement already satisfied: aiohttp<4,>=3.8.6 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (3.14.3)
Requirement already satisfied: aiosqlite in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (0.22.1)
Requirement already satisfied: banks<3,>=2.3.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (2.5.1)
Requirement already satisfied: dataclasses-json in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (0.6.7)
Requirement already satisfied: deprecated>=1.2.9.3 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (3.0.0)
Requirement already satisfied: dirtyjson<2,>=1.0.8 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (1.0.8)
Requirement already satisfied: filetype<2,>=1.2.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (1.2.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (2026.9.0)
Requirement already satisfied: httpx in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (0.28.1)
Requirement already satisfied: llama-index-workflows<3,>=2.14.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (2.25.0)
Requirement already satisfied: nest-asyncio<2,>=1.5.8 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (1.6.0)
Requirement already satisfied: networkx>=3.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (3.7)
Requirement already satisfied: nltk>=3.9.3 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (3.10.3)
Requirement already satisfied: numpy in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (2.5.3)
Requirement already satisfied: pillow>=9.0.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (12.3.0)
Requirement already satisfied: platformdirs in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (4.12.0)
Requirement already satisfied: pydantic>=2.8.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (2.13.5)
Requirement already satisfied: pyyaml>=6.0.1 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (6.0.3)
Requirement already satisfied: requests>=2.31.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (2.34.2)
Requirement already satisfied: setuptools>=80.9.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (84.0.0)
Requirement already satisfied: sqlalchemy>=1.4.49 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from sqlalchemy[asyncio]>=1.4.49->llama-index-core) (2.1.1)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.2.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (9.1.4)
Requirement already satisfied: tiktoken>=0.7.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (0.14.0)
Requirement already satisfied: tinytag>=2.2.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (2.3.2)
Requirement already satisfied: tqdm<5,>=4.66.1 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (4.70.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (4.16.0)
Requirement already satisfied: typing-inspect>=0.8.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (0.9.0)
Requirement already satisfied: wrapt in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-core) (2.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (6.9.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from aiohttp<4,>=3.8.6->llama-index-core) (1.25.1)
Requirement already satisfied: griffe in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from banks<3,>=2.3.0->llama-index-core) (2.3.0)
Requirement already satisfied: jinja2 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from banks<3,>=2.3.0->llama-index-core) (3.1.6)
Requirement already satisfied: llama-index-instrumentation>=0.4.3 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-workflows<3,>=2.14.0->llama-index-core) (0.6.0)
Requirement already satisfied: idna>=2.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from yarl<2.0,>=1.17.0->aiohttp<4,>=3.8.6->llama-index-core) (3.20)
Requirement already satisfied: huggingface-hub>=0.19.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.33.0)
Requirement already satisfied: sentence-transformers>=2.6.1 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-embeddings-huggingface) (6.1.0)
Requirement already satisfied: llama-index-llms-openai-like<0.9,>=0.8.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-llms-groq) (0.8.0)
Requirement already satisfied: llama-index-llms-openai<0.8,>=0.7.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-llms-openai-like<0.9,>=0.8.0->llama-index-llms-groq) (0.7.10)
Requirement already satisfied: openai<3,>=1.108.1 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from llama-index-llms-openai<0.8,>=0.7.0->llama-index-llms-openai-like<0.9,>=0.8.0->llama-index-llms-groq) (2.54.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from openai<3,>=1.108.1->llama-index-llms-openai<0.8,>=0.7.0->llama-index-llms-openai-like<0.9,>=0.8.0->llama-index-llms-groq) (4.15.1)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from openai<3,>=1.108.1->llama-index-llms-openai<0.8,>=0.7.0->llama-index-llms-openai-like<0.9,>=0.8.0->llama-index-llms-groq) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from openai<3,>=1.108.1->llama-index-llms-openai<0.8,>=0.7.0->llama-index-llms-openai-like<0.9,>=0.8.0->llama-index-llms-groq) (0.17.0)
Requirement already satisfied: sniffio in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from openai<3,>=1.108.1->llama-index-llms-openai<0.8,>=0.7.0->llama-index-llms-openai-like<0.9,>=0.8.0->llama-index-llms-groq) (1.3.1)
Requirement already satisfied: certifi in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from httpx->llama-index-core) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from httpx->llama-index-core) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from httpcore==1.*->httpx->llama-index-core) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from pydantic>=2.8.0->llama-index-core) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from pydantic>=2.8.0->llama-index-core) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from pydantic>=2.8.0->llama-index-core) (0.4.4)
Requirement already satisfied: build>=1.0.3 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (1.6.1)
Requirement already satisfied: pydantic-settings>=2.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (2.15.0)
Requirement already satisfied: pybase64>=1.4.1 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (1.5.0)
Requirement already satisfied: uvicorn>=0.18.3 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.54.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (1.30.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (1.45.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (1.45.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (1.45.0)
Requirement already satisfied: tokenizers>=0.13.2 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (0.23.2)
Requirement already satisfied: pypika>=0.48.9 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (0.51.1)
Requirement already satisfied: overrides>=7.3.1 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (1.84.0)
Requirement already satisfied: bcrypt>=4.0.1 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (0.27.2)
Requirement already satisfied: kubernetes>=28.1.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (36.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (5.3.0)
Requirement already satisfied: orjson>=3.9.12 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (3.12.0)
Requirement already satisfied: rich>=10.11.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (15.0.0)
Requirement already satisfied: jsonschema>=4.19.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from build>=1.0.3->chromadb) (26.3)
Requirement already satisfied: pyproject_hooks in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from build>=1.0.3->chromadb) (1.3.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (4.0.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from huggingface-hub>=0.19.0->huggingface-hub[inference]>=0.19.0->llama-index-embeddings-huggingface) (1.6.0)
WARNING: huggingface-hub 1.33.0 does not provide the extra 'inference'
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from jsonschema>=4.19.0->chromadb) (2026.6.3)
Requirement already satisfied: six>=1.9.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from kubernetes>=28.1.0->chromadb) (1.9.2)
Requirement already satisfied: requests-oauthlib in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/.venv/lib/python3.13/site-packages (from kubernetes>=28.1.0->chromadb) (2.8.0)

In [45]:
# load chunks

chunks_df = pd.read_parquet(processed_dir / "chunks.parquet")
print(f"loaded {len(chunks_df)} chunks from {processed_dir / 'chunks.parquet'}")

loaded 35449 chunks from /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chunks.parquet

In [46]:
# convert raw chunks into llamaindex textnodes, i.e. units with text and metadata

nodes = []
for _, row in chunks_df.iterrows():
    node = TextNode(
        text=row["text"],
        metadata={
            "arxiv_id": row["arxiv_id"],
            "title": row["title"],
            "author": row["author"],
            "page_number": row["page_number"],
        }
    )
    nodes.append(node)

print(f"built {len(nodes)} nodes")

built 35449 nodes

In [54]:
# config embedding model

Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

2026-10-19 12:19:03,491 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 12:19:03,515 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fmodules.json=&etag=%22952a9b81c0bfd99800fabf352f69c7ccd46c5e43%22 "HTTP/1.1 200 OK"
2026-10-19 12:19:03,548 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 12:19:03,573 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fconfig_sentence_transformers.json=&etag=%22dcb0c0d97d09b930d13600b1a773ddb27e441aab%22 "HTTP/1.1 200 OK"
2026-10-19 12:19:03,575 | INFO | Loading SentenceTransformer model from BAAI/bge-small-en-v1.5.
2026-10-19 12:19:03,608 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 12:19:03,631 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config_sentence_transformers.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fconfig_sentence_transformers.json=&etag=%22dcb0c0d97d09b930d13600b1a773ddb27e441aab%22 "HTTP/1.1 200 OK"
2026-10-19 12:19:03,667 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-10-19 12:19:03,692 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/README.md?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2FREADME.md=&etag=%228b8567d75ffa619486d9590cb0eb76d66ad46c49%22 "HTTP/1.1 200 OK"
2026-10-19 12:19:03,730 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 12:19:03,752 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/modules.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fmodules.json=&etag=%22952a9b81c0bfd99800fabf352f69c7ccd46c5e43%22 "HTTP/1.1 200 OK"
2026-10-19 12:19:03,788 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 12:19:03,814 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/sentence_bert_config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fsentence_bert_config.json=&etag=%22ea85692bff64b0d1917833c31ddbca8ab10f5455%22 "HTTP/1.1 200 OK"
2026-10-19 12:19:03,922 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-10-19 12:19:03,960 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 12:19:03,983 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fconfig.json=&etag=%223992bf890728a92476c700e6e657fd696eb94160%22 "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8272.38it/s]
2026-10-19 12:19:04,180 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-10-19 12:19:04,214 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-10-19 12:19:04,247 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-10-19 12:19:04,279 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-10-19 12:19:04,310 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 12:19:04,335 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Ftokenizer_config.json=&etag=%2237fca74771bc76a8e01178ce3a6055a0995f8093%22 "HTTP/1.1 200 OK"
2026-10-19 12:19:04,445 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 12:19:04,470 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fconfig.json=&etag=%223992bf890728a92476c700e6e657fd696eb94160%22 "HTTP/1.1 200 OK"
2026-10-19 12:19:04,504 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 12:19:04,529 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Fconfig.json=&etag=%223992bf890728a92476c700e6e657fd696eb94160%22 "HTTP/1.1 200 OK"
2026-10-19 12:19:04,562 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 12:19:04,588 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/tokenizer_config.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2Ftokenizer_config.json=&etag=%2237fca74771bc76a8e01178ce3a6055a0995f8093%22 "HTTP/1.1 200 OK"
2026-10-19 12:19:04,623 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-10-19 12:19:04,663 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-10-19 12:19:04,746 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 12:19:04,767 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/BAAI/bge-small-en-v1.5/5c38ec7c405ec4b44b94cc5a9bb96e735b38267a/1_Pooling%2Fconfig.json?%2FBAAI%2Fbge-small-en-v1.5%2Fresolve%2Fmain%2F1_Pooling%2Fconfig.json=&etag=%221da070f0993788c8851a652170ff013aa54dd519%22 "HTTP/1.1 200 OK"
2026-10-19 12:19:04,800 | INFO | HTTP Request: HEAD https://huggingface.co/BAAI/bge-small-en-v1.5/resolve/main/2_Normalize/config.json "HTTP/1.1 404 Not Found"
2026-10-19 12:19:04,842 | INFO | HTTP Request: GET https://huggingface.co/api/models/BAAI/bge-small-en-v1.5 "HTTP/1.1 200 OK"
2026-10-19 12:19:05,788 | INFO | Loaded 1 prompt with these keys: ['query']

In [55]:
# config llm used to generate responses

from dotenv import load_dotenv
load_dotenv()  # load groq api key from .env file

Settings.llm = Groq(model="openai/gpt-oss-120b") # use openai/gpt-oss-120b model instead if hit rate limit, but could have lower answer quality

In [49]:
# set up chroma for vectore store and build index

chroma_client = chromadb.PersistentClient(path=str(processed_dir / "chroma_db"))
chroma_collection = chroma_client.get_or_create_collection(name="arxiv_papers")

vectore_store = ChromaVectorStore(chroma_collection=chroma_collection)
storage_context = StorageContext.from_defaults(vector_store=vectore_store)

index = VectorStoreIndex(nodes, storage_context=storage_context)

print("index built and persisted to", processed_dir / "chroma_db")

index built and persisted to /Users/anna/KPMG-1K-ai-research-intelligence-agent-for-business-insight-translation/data_processed/chroma_db

In [68]:
# hybrid retrieval: bm25 (keyword) + vector (semantic), fused via reciprocal rank fusion

bm25_retriever = BM25Retriever.from_defaults(nodes=nodes, similarity_top_k=30)
vector_retriever = index.as_retriever(similarity_top_k=30)

fusion_retriever = QueryFusionRetriever(
    [vector_retriever, bm25_retriever],
    similarity_top_k=30,
    num_queries=1,
    mode="reciprocal_rerank",
)

2026-10-19 13:51:36,536 | DEBUG | Building index from IDs objects

In [69]:
# build query engine (embed question, retrieve top similar chunks, feed them into llm, and generate response)

reranker = SentenceTransformerRerank(model="cross-encoder/ms-marco-MiniLM-L-6-v2", top_n=5) # build cross-encoder reranker
query_engine = index.as_query_engine(
    similarity_top_k=20,
    node_postprocessors=[reranker]
)

2026-10-19 14:02:08,428 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:08,463 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/modules.json "HTTP/1.1 404 Not Found"
2026-10-19 14:02:08,465 | INFO | No modules.json found for cross-encoder/ms-marco-MiniLM-L-6-v2, initializing a new CrossEncoder model.
2026-10-19 14:02:08,497 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L-6-v2 "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:08,535 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2 "HTTP/1.1 200 OK"
2026-10-19 14:02:08,571 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:08,605 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:08,629 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/cross-encoder/ms-marco-MiniLM-L6-v2/233902d25c440f23af6f7d6e94d2946bac0bee0a/config.json?%2Fcross-encoder%2Fms-marco-MiniLM-L6-v2%2Fresolve%2Fmain%2Fconfig.json=&etag=%2288bc4f74b33a2073abc9a66cb532b889448ac3ed%22 "HTTP/1.1 200 OK"
2026-10-19 14:02:08,669 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/main/adapter_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:08,702 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-10-19 14:02:08,736 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:08,771 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:08,876 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/cross-encoder/ms-marco-MiniLM-L6-v2/233902d25c440f23af6f7d6e94d2946bac0bee0a/config.json?%2Fcross-encoder%2Fms-marco-MiniLM-L6-v2%2Fresolve%2Fmain%2Fconfig.json=&etag=%2288bc4f74b33a2073abc9a66cb532b889448ac3ed%22 "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 105/105 [00:00<00:00, 9530.86it/s]
2026-10-19 14:02:08,962 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/main/processor_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:08,995 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/processor_config.json "HTTP/1.1 404 Not Found"
2026-10-19 14:02:09,033 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:09,066 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-10-19 14:02:09,109 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/main/video_preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:09,149 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/video_preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-10-19 14:02:09,188 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/main/preprocessor_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:09,222 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/preprocessor_config.json "HTTP/1.1 404 Not Found"
2026-10-19 14:02:09,257 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:09,290 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:09,400 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/cross-encoder/ms-marco-MiniLM-L6-v2/233902d25c440f23af6f7d6e94d2946bac0bee0a/tokenizer_config.json?%2Fcross-encoder%2Fms-marco-MiniLM-L6-v2%2Fresolve%2Fmain%2Ftokenizer_config.json=&etag=%22a2435fedfac32b9ad70f052d4f84007730cd3109%22 "HTTP/1.1 200 OK"
2026-10-19 14:02:09,439 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:09,483 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:09,507 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/cross-encoder/ms-marco-MiniLM-L6-v2/233902d25c440f23af6f7d6e94d2946bac0bee0a/config.json?%2Fcross-encoder%2Fms-marco-MiniLM-L6-v2%2Fresolve%2Fmain%2Fconfig.json=&etag=%2288bc4f74b33a2073abc9a66cb532b889448ac3ed%22 "HTTP/1.1 200 OK"
2026-10-19 14:02:09,544 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:09,576 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:09,600 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/cross-encoder/ms-marco-MiniLM-L6-v2/233902d25c440f23af6f7d6e94d2946bac0bee0a/config.json?%2Fcross-encoder%2Fms-marco-MiniLM-L6-v2%2Fresolve%2Fmain%2Fconfig.json=&etag=%2288bc4f74b33a2073abc9a66cb532b889448ac3ed%22 "HTTP/1.1 200 OK"
2026-10-19 14:02:09,635 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:09,667 | INFO | HTTP Request: HEAD https://huggingface.co/cross-encoder/ms-marco-MiniLM-L6-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:09,691 | INFO | HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/cross-encoder/ms-marco-MiniLM-L6-v2/233902d25c440f23af6f7d6e94d2946bac0bee0a/tokenizer_config.json?%2Fcross-encoder%2Fms-marco-MiniLM-L6-v2%2Fresolve%2Fmain%2Ftokenizer_config.json=&etag=%22a2435fedfac32b9ad70f052d4f84007730cd3109%22 "HTTP/1.1 200 OK"
2026-10-19 14:02:09,727 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L-6-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:09,761 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-10-19 14:02:09,799 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L-6-v2/tree/main?recursive=true&expand=false "HTTP/1.1 307 Temporary Redirect"
2026-10-19 14:02:09,834 | INFO | HTTP Request: GET https://huggingface.co/api/models/cross-encoder/ms-marco-MiniLM-L6-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"

In [70]:
# ask question (hardcoded for now)

response = query_engine.query("What are the most relevant recent research papers on reducing hallucinations in retrieval-augmented generation? Summarize the main approaches and identify where the evidence is strongest.")

print("RESPONSE:\n", response)

print("\nSOURCES:")
for node in response.source_nodes:
    meta = node.metadata
    print(f"- {meta['title']} (page {meta['page_number']}, score={node.score:.3f})")

Batches: 100%|██████████| 1/1 [00:00<00:00, 51.16it/s]
2026-10-19 14:02:17,867 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

RESPONSE:
 **Key recent papers that target hallucinations in retrieval‑augmented generation (RAG)**

| Year | Paper (first author) | Core idea for hallucination mitigation |
|------|----------------------|----------------------------------------|
| 2022 | Dai et al. – *Survey of Hallucination in Natural Language Generation* | Provides a taxonomy of hallucination types and reviews mitigation strategies, establishing a common vocabulary for later work. |
| 2024 | Yan et al. – *Corrective Retrieval‑Augmented Generation* | Introduces a corrective loop that first retrieves evidence, generates a draft, then checks the draft against the retrieved sources and revises any unsupported statements. |
| 2024 | Broszio et al. – *Self‑Reflective Chain‑of‑Thought (SRCoT): Retrieve‑Reflect‑Revise* | Proposes a closed‑loop “retrieve → reflect → revise” pipeline for edge‑deployed LLMs. The model explicitly reflects on the adequacy of its evidence before finalising the output. |
| 2025 | Edge et al. – *From Local to Global: A Graph RAG Approach to Query‑Focused Summarisation* | Uses a graph‑structured retrieval component that aggregates evidence across multiple hops, reducing reliance on a single noisy document and thereby lowering factual drift. |
| 2025 | Yazan et al. – *Improving RAG for Personalisation with Author Features and Contrastive Examples* | Augments the retriever with author‑level metadata and trains the generator with contrastive examples that penalise hallucinated statements. |
| 2025 | Kalra et al. – *HyPA‑RAG: A Hybrid Parameter Adaptive Retrieval‑Augmented Generation System for AI Legal and Policy* | Adapts retrieval and generation parameters dynamically based on domain‑specific confidence signals, aiming to keep legal‑policy outputs grounded in verified sources. |

### Summarised approaches

1. **Closed‑loop verification (Corrective RAG, SRCoT)**
   - **Mechanism:** After an initial generation, the system re‑queries the knowledge base (or re‑examines the retrieved passages) and automatically revises any segment that lacks support.
   - **Strength of evidence:** Both papers report quantitative reductions in hallucination rates on benchmark fact‑checking and summarisation datasets (e.g., a 30 % drop in unsupported claims for Corrective RAG; SRCoT shows consistent gains across edge‑LLM configurations). The experimental sections include ablation studies that isolate the revision step as the primary contributor.

2. **Graph‑based multi‑hop retrieval (Graph RAG)**
   - **Mechanism:** Constructs a knowledge graph from retrieved documents, allowing the generator to draw on a broader, interconnected evidence set rather than a single passage.
   - **Strength of evidence:** Empirical results on query‑focused summarisation tasks demonstrate higher factual precision (≈ 5‑point ROUGE‑L improvement) and fewer hallucinations compared with flat‑list retrieval baselines.

3. **Metadata‑enhanced retrieval & contrastive training (Personalisation RAG)**
   - **Mechanism:** Enriches the retriever with author or source features and trains the generator with contrastive loss that explicitly penalises outputs that diverge from the retrieved evidence.
   - **Strength of evidence:** The authors present controlled experiments where the contrastive model outperforms a standard RAG baseline on a personalised news‑generation benchmark, achieving a statistically significant reduction in factual errors.

4. **Dynamic parameter adaptation for high‑risk domains (HyPA‑RAG)**
   - **Mechanism:** Monitors domain‑specific confidence scores and adjusts retrieval depth and generation temperature on‑the‑fly, aiming to be more conservative when evidence is sparse.
   - **Strength of evidence:** Case studies in legal‑policy drafting show that the adaptive system produces fewer unsupported citations than a static‑parameter RAG system, though the evaluation is limited to a narrow set of legal prompts.

5. **Survey and taxonomy (Dai et al.)**
   - **Mechanism:** While not an algorithmic contribution, the survey consolidates definitions of hallucination types and benchmarks, providing the methodological foundation for the empirical work above.
   - **Strength of evidence:** The paper aggregates results from dozens of prior studies, highlighting which mitigation techniques have demonstrated reproducible gains across multiple tasks.

### Where the evidence is strongest

- **Closed‑loop correction** (Corrective RAG and SRCoT) offers the most robust empirical backing. Both papers include extensive benchmark testing, ablations, and cross‑model evaluations that directly measure hallucination frequency before and after the revision step.
- **Graph‑based retrieval** also shows solid quantitative improvements, though its evaluation is confined to a single summarisation task.
- **Contrastive training with metadata** provides promising results, but the evidence is currently limited to a specific personalization scenario.
- **Dynamic adaptation for legal/policy** presents compelling case‑study evidence but lacks broad‑scale benchmarking.

Overall, the most compelling and generalizable mitigation strategy emerging from recent work is the incorporation of an explicit verification or revision stage that re‑examines generated text against retrieved evidence before final output. This closed‑loop design consistently yields the largest measured drops in hallucination rates across diverse datasets and model sizes.

SOURCES:
- Characterising and Analysing Retrieval-Augmented Generation Techniques (page 16, score=1.053)
- Self-Reflective Chain-of-Thought (SRCoT): Evidence-Based Text Generation via a Closed-Loop Retrieve--Reflect--Revise Pipeline on Edge LLMs (page 2, score=0.332)
- Characterising and Analysing Retrieval-Augmented Generation Techniques (page 1, score=0.221)
- Loud and Clear: Making Visual Evidence Count in Multimodal Document RAG (page 11, score=-2.803)
- DialFork: Going Beyond Factuality to Evaluate Procedural Hallucination in Conversational Agents (page 10, score=-5.015)

# Part 4 - Baseline RAG Evaluation

In [26]:
# Part 4: Baseline RAG Evaluation

import chromadb
import pandas as pd

from llama_index.core import VectorStoreIndex, StorageContext
from llama_index.vector_stores.chroma import ChromaVectorStore

In [27]:
# Create benchmark questions

benchmark_questions = [
    {
        "id": "Q1",
        "question": "What problem does Pandora's AI Model Routing Box aim to solve?",
        "expected_arxiv_id": "2608.20316v1"
    },
    {
        "id": "Q2",
        "question": "How does Pandora's AI Model Routing Box improve the efficiency of AI model selection?",
        "expected_arxiv_id": "2608.20316v1"
    },
    {
        "id": "Q3",
        "question": "What is AI4AI-Bench designed to evaluate?",
        "expected_arxiv_id": "2608.20318v1"
    },
    {
        "id": "Q4",
        "question": "How does AI4AI-Bench assess the performance of LLM agents in algorithmic design?",
        "expected_arxiv_id": "2608.20318v1"
    },
    {
        "id": "Q5",
        "question": "What information is used to induce task models from computer-use traces?",
        "expected_arxiv_id": "2608.20319v1"
    },
    {
        "id": "Q6",
        "question": "What is the purpose of the agentic approach for active data collection and travel behaviour modelling?",
        "expected_arxiv_id": "2608.20320v1"
    },
    {
        "id": "Q7",
        "question": "What problem does grounded checklist-aligned reward learning address in patient-oriented medical research?",
        "expected_arxiv_id": "2608.20331v1"
    },
    {
        "id": "Q8",
        "question": "How is reward learning used to improve patient-oriented medical outcomes?",
        "expected_arxiv_id": "2608.20331v1"
    }
]

benchmark_df = pd.DataFrame(benchmark_questions)

benchmark_df

   id                                           question expected_arxiv_id
0  Q1  What problem does Pandora's AI Model Routing B...      2608.20316v1
1  Q2  How does Pandora's AI Model Routing Box improv...      2608.20316v1
2  Q3          What is AI4AI-Bench designed to evaluate?      2608.20318v1
3  Q4  How does AI4AI-Bench assess the performance of...      2608.20318v1
4  Q5  What information is used to induce task models...      2608.20319v1
5  Q6  What is the purpose of the agentic approach fo...      2608.20320v1
6  Q7  What problem does grounded checklist-aligned r...      2608.20331v1
7  Q8  How is reward learning used to improve patient...      2608.20331v1

In [28]:
# Create Chroma vector store

chroma_client = chromadb.PersistentClient(
    path=str(processed_dir / "chroma_db")
)

chroma_collection = chroma_client.get_or_create_collection(
    name="baseline_rag"
)

vector_store = ChromaVectorStore(
    chroma_collection=chroma_collection
)

storage_context = StorageContext.from_defaults(
    vector_store=vector_store
)

In [29]:
# Create the baseline vector index

index = VectorStoreIndex(
    nodes,
    storage_context=storage_context,
    show_progress=True
)

retriever = index.as_retriever(
    similarity_top_k=5
)

Generating embeddings: 100%|██████████| 300/300 [00:45<00:00,  6.63it/s]

In [30]:
# Test baseline retrieval

test_question = benchmark_questions[0]["question"]

results = retriever.retrieve(test_question)

for rank, result in enumerate(results, start=1):
    print(f"Rank {rank}")
    print(f"arXiv ID: {result.node.metadata.get('arxiv_id')}")
    print(f"Title: {result.node.metadata.get('title')}")
    print(f"Page: {result.node.metadata.get('page_number')}")
    print()

Rank 1
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 26

Rank 2
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 26

Rank 3
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 26

Rank 4
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 18

Rank 5
arXiv ID: 2608.20316v1
Title: Pandora's AI Model Routing Box: Efficient Allocation with Costly Value Estimation
Page: 18

In [31]:
# Evaluate baseline retrieval

retrieval_results = []

for item in benchmark_questions:

    results = retriever.retrieve(item["question"])

    retrieved_ids = [
        result.node.metadata.get("arxiv_id")
        for result in results
    ]

    expected_id = item["expected_arxiv_id"]

    retrieval_results.append({
        "id": item["id"],
        "question": item["question"],
        "expected_arxiv_id": expected_id,
        "retrieved_ids": retrieved_ids,
        "hit_at_1": expected_id in retrieved_ids[:1],
        "hit_at_3": expected_id in retrieved_ids[:3],
        "hit_at_5": expected_id in retrieved_ids[:5]
    })

evaluation_df = pd.DataFrame(retrieval_results)

evaluation_df

,id,question,expected_arxiv_id,retrieved_ids,hit_at_1,hit_at_3,hit_at_5
0,Q1,What problem does Pandora's AI Model Routing B...,2608.20316v1,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260...",True,True,True
1,Q2,How does Pandora's AI Model Routing Box improv...,2608.20316v1,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260...",True,True,True
2,Q3,What is AI4AI-Bench designed to evaluate?,2608.20318v1,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260...",True,True,True
3,Q4,How does AI4AI-Bench assess the performance of...,2608.20318v1,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260...",True,True,True
4,Q5,What information is used to induce task models...,2608.20319v1,"[2608.20319v1, 2608.20319v1, 2608.20319v1, 260...",True,True,True
5,Q6,What is the purpose of the agentic approach fo...,2608.20320v1,"[2608.20320v1, 2608.20320v1, 2608.20320v1, 260...",True,True,True
6,Q7,What problem does grounded checklist-aligned r...,2608.20331v1,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260...",True,True,True
7,Q8,How is reward learning used to improve patient...,2608.20331v1,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260...",True,True,True

In [32]:
# Calculate retrieval metrics

hit_at_1 = evaluation_df["hit_at_1"].mean()
hit_at_3 = evaluation_df["hit_at_3"].mean()
hit_at_5 = evaluation_df["hit_at_5"].mean()

print("Baseline Retrieval Performance")
print("-" * 40)
print(f"Hit@1: {hit_at_1:.2%}")
print(f"Hit@3: {hit_at_3:.2%}")
print(f"Hit@5: {hit_at_5:.2%}")

Baseline Retrieval Performance
----------------------------------------
Hit@1: 100.00%
Hit@3: 100.00%
Hit@5: 100.00%

In [33]:
# Save baseline retrieval results

evaluation_df.to_csv(
    processed_dir / "baseline_retrieval_evaluation.csv",
    index=False
)

Okay, so far 100% Hit for 1,3, and 5 indicates that it was able to retrieve a chunk from the expected paper. However, we do not know if the RAG system generates correct answers.

Will be using Groq generation and evalluate the answers below.

In [34]:
# Set up Groq

import os
from dotenv import load_dotenv

from llama_index.core import Settings
from llama_index.llms.groq import Groq

load_dotenv()

groq_api_key = os.getenv("GROQ_API_KEY")

llm = Groq(
    model="openai/gpt-oss-20b",
    api_key=groq_api_key
)

Settings.llm = llm

In [35]:
# Test Groq with one question

question = benchmark_questions[0]["question"]

results = retriever.retrieve(question)

context = "\n\n".join([
    f"""
Source:
Title: {result.node.metadata.get('title')}
arXiv ID: {result.node.metadata.get('arxiv_id')}
Page: {result.node.metadata.get('page_number')}

Text:
{result.node.text}
"""
    for result in results
])

prompt = f"""
You are a research intelligence assistant.

Answer the question using only the research context provided below.

Question:
{question}

Research context:
{context}

Instructions:
- Give a concise and factual answer.
- Do not use information outside the provided context.
- If the context does not contain enough information, say so.
- At the end of your answer, provide the source arXiv ID.
"""

response = llm.complete(prompt)

print(response.text)

2026-10-06 15:35:47,022 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

Pandora’s AI Model Routing Box is designed to address the problem of efficiently allocating AI models to incoming tasks while taking into account the cost of estimating each model’s value. It seeks to minimize regret and inspection cost by routing queries to the most appropriate model under a budget‑constrained value‑estimation setting.

Source: arXiv 2608.20316v1

In [36]:
# Generate a RAG answer

def generate_rag_answer(question):

    results = retriever.retrieve(question)

    context = "\n\n".join([
        f"""
Source:
Title: {result.node.metadata.get('title')}
arXiv ID: {result.node.metadata.get('arxiv_id')}
Page: {result.node.metadata.get('page_number')}

Text:
{result.node.text}
"""
        for result in results
    ])

    prompt = f"""
You are a research intelligence assistant.

Answer the question using only the research context provided below.

Question:
{question}

Research context:
{context}

Instructions:
- Give a concise and factual answer.
- Do not use information outside the provided context.
- If the context does not contain enough information, say so.
- At the end of your answer, provide the source arXiv ID.
"""

    response = llm.complete(prompt)

    return response.text, results

In [37]:
# Generate answers for all benchmark questions

rag_results = []

for item in benchmark_questions:

    answer, results = generate_rag_answer(
        item["question"]
    )

    retrieved_ids = [
        result.node.metadata.get("arxiv_id")
        for result in results
    ]

    rag_results.append({
        "id": item["id"],
        "question": item["question"],
        "expected_arxiv_id": item["expected_arxiv_id"],
        "answer": answer,
        "retrieved_ids": retrieved_ids
    })

rag_results_df = pd.DataFrame(rag_results)

rag_results_df

2026-10-06 15:35:48,711 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:35:50,150 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:35:50,305 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:35:50,308 | INFO | Retrying request to /chat/completions in 2.000000 seconds
2026-10-06 15:35:53,302 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:35:53,517 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:35:53,518 | INFO | Retrying request to /chat/completions in 17.000000 seconds
2026-10-06 15:36:11,728 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:36:13,087 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:13,089 | INFO | Retrying request to /chat/completions in 13.000000 seconds
2026-10-06 15:36:26,723 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:36:27,866 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:27,905 | INFO | Retrying request to /chat/completions in 9.000000 seconds
2026-10-06 15:36:37,366 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:37,377 | INFO | Retrying request to /chat/completions in 4.000000 seconds
2026-10-06 15:36:42,088 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:36:43,608 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:36:43,613 | INFO | Retrying request to /chat/completions in 28.000000 seconds
2026-10-06 15:37:11,919 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:37:11,925 | INFO | Retrying request to /chat/completions in 3.000000 seconds
2026-10-06 15:37:15,789 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2026-10-06 15:37:16,606 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 429 Too Many Requests"
2026-10-06 15:37:16,611 | INFO | Retrying request to /chat/completions in 25.000000 seconds
2026-10-06 15:37:42,769 | INFO | HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"

,id,question,expected_arxiv_id,answer,retrieved_ids
0,Q1,What problem does Pandora's AI Model Routing B...,2608.20316v1,Pandora’s AI Model Routing Box tackles the cha...,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260..."
1,Q2,How does Pandora's AI Model Routing Box improv...,2608.20316v1,Pandora’s AI Model Routing Box improves effici...,"[2608.20316v1, 2608.20316v1, 2608.20316v1, 260..."
2,Q3,What is AI4AI-Bench designed to evaluate?,2608.20318v1,AI4AI‑Bench is a benchmark that tests whether ...,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260..."
3,Q4,How does AI4AI-Bench assess the performance of...,2608.20318v1,AI4AI‑Bench evaluates an LLM agent by letting ...,"[2608.20318v1, 2608.20318v1, 2608.20318v1, 260..."
4,Q5,What information is used to induce task models...,2608.20319v1,Task models are induced from the low‑level eve...,"[2608.20319v1, 2608.20319v1, 2608.20319v1, 260..."
5,Q6,What is the purpose of the agentic approach fo...,2608.20320v1,The agentic approach is designed to unify the ...,"[2608.20320v1, 2608.20320v1, 2608.20320v1, 260..."
6,Q7,What problem does grounded checklist-aligned r...,2608.20331v1,Grounded checklist‑aligned reward learning (G‑...,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260..."
7,Q8,How is reward learning used to improve patient...,2608.20331v1,Reward learning in G‑CARL improves patient‑ori...,"[2608.20331v1, 2608.20331v1, 2608.20331v1, 260..."

In [38]:
# Review generated answers

for _, row in rag_results_df.iterrows():

    print(f"--- {row['id']} ---")
    print(f"Question: {row['question']}")
    print()
    print(f"Answer: {row['answer']}")
    print()
    print(f"Expected source: {row['expected_arxiv_id']}")
    print("-" * 60)

--- Q1 ---
Question: What problem does Pandora's AI Model Routing Box aim to solve?

Answer: Pandora’s AI Model Routing Box tackles the challenge of **efficiently allocating tasks to AI models when estimating each model’s value is expensive**—i.e., it seeks to optimize routing decisions while accounting for the cost of value estimation.

Source: arXiv 2608.20316v1

Expected source: 2608.20316v1
------------------------------------------------------------
--- Q2 ---
Question: How does Pandora's AI Model Routing Box improve the efficiency of AI model selection?

Answer: Pandora’s AI Model Routing Box improves efficiency by routing queries to the most valuable models using a cost‑aware value‑estimation framework.  The system employs value estimators (Section C.1) and carefully designed prompts (Section C.2) to predict each model’s expected benefit, allowing it to limit the number of inspections (see Supplemental Results D.1) and the monetary cost of value‑function evaluations (Supplemental Results D.3).  This targeted allocation reduces overall regret plus inspection cost, as shown in Table 4 on RAG routing, where the Box achieves the lowest combined metric among compared methods.

Source: arXiv 2608.20316v1.

Expected source: 2608.20316v1
------------------------------------------------------------
--- Q3 ---
Question: What is AI4AI-Bench designed to evaluate?

Answer: AI4AI‑Bench is a benchmark that tests whether a large‑language‑model agent can write code that improves the training algorithm of a repository’s own model.  The agent’s submission is evaluated by running the modified code under the same conditions as the original, and a fixed evaluator computes a metric (e.g., accuracy, solve‑rate, loss).  The benchmark measures whether the agent’s code yields a better metric than the baseline, thus assessing the agent’s ability to perform recursive self‑improvement in algorithm design.

Source: arXiv 2608.20318v1

Expected source: 2608.20318v1
------------------------------------------------------------
--- Q4 ---
Question: How does AI4AI-Bench assess the performance of LLM agents in algorithmic design?

Answer: AI4AI‑Bench evaluates an LLM agent by letting it modify the training algorithm of a frozen research repository and then measuring the quality of the resulting model with a **fixed, pre‑defined evaluator**.

1. **Baseline** – The original repository’s code is run once to produce a baseline model \(C\).
2. **Agent submission** – The agent’s code produces a modified training algorithm \(C'\).
3. **Evaluation** – Both \(C\) and \(C'\) are trained under identical conditions (same hardware, budget, and evaluator).
4. **Metric** – A fixed evaluator \(m\) computes a scalar score \(s(C)=m(a(C))\) and \(s(C')=m(a(C'))\).
5. **Improvement test** – The submission is considered better if
   \[
   s(C') > s(C) \quad \text{for upward‑directed metrics (↑)} \quad\text{or}\quad
   s(C') < s(C) \quad \text{for downward‑directed metrics (↓)} .
   \]
6. **Dense scoring** – Rather than a binary win/lose, the benchmark reports the actual metric value, providing a dense score that reflects the magnitude of improvement.

Thus, AI4AI‑Bench assesses performance by comparing the evaluator‑derived metric of the agent‑generated model to that of the baseline, using a dense, direction‑aware score.

**Source:** arXiv:2608.20318v1.

Expected source: 2608.20318v1
------------------------------------------------------------
--- Q5 ---
Question: What information is used to induce task models from computer-use traces?

Answer: Task models are induced from the low‑level events that are passively recorded during computer use: screenshots of the screen and the corresponding mouse or keyboard actions.

Source: arXiv 2608.20319v1

Expected source: 2608.20319v1
------------------------------------------------------------
--- Q6 ---
Question: What is the purpose of the agentic approach for active data collection and travel behaviour modelling?

Answer: The agentic approach is designed to unify the traditionally separate stages of travel‑behavior research into a single, transparent, and modular workflow. By linking a conversational data‑collection agent, a structured data‑processing agent, and a behavioral‑prediction agent, it enables an AI‑assisted survey to capture context‑dependent travel behavior and to feed that data directly into predictive models (e.g., LLMs, DCMs, ML benchmarks). The goal is to streamline the process from survey administration to behavioral prediction while allowing systematic evaluation of how different information types and AI configurations affect mode‑choice accuracy.

Source: arXiv 2608.20320v1

Expected source: 2608.20320v1
------------------------------------------------------------
--- Q7 ---
Question: What problem does grounded checklist-aligned reward learning address in patient-oriented medical research?

Answer: Grounded checklist‑aligned reward learning (G‑CARL) tackles the problem of producing **clinically accurate, evidence‑grounded interpretations of medical reports that also respect patient‑specific context and clinical checklists**. In patient‑oriented medical research, existing methods (e.g., simple fine‑tuning or “LLM‑as‑a‑Judge”) often misdiagnose abnormalities, ignore relevant patient history, or fail to answer the user’s primary question. G‑CARL aligns the model’s outputs with a checklist of clinical criteria and evidence‑based rewards, thereby improving diagnostic accuracy, contextual integration, and recommendation quality.

**Source:** arXiv:2608.20331v1

Expected source: 2608.20331v1
------------------------------------------------------------
--- Q8 ---
Question: How is reward learning used to improve patient-oriented medical outcomes?

Answer: Reward learning in G‑CARL improves patient‑oriented medical outcomes by providing fine‑grained, evidence‑grounded supervision for language models that interpret medical reports. The framework decomposes rewards into two types:

1. **Retrieval‑grounded claim reward** – each atomic medical claim in a generated response is verified against the uploaded report and a multi‑source medical datastore. This gives localized feedback on factual accuracy and discourages unsupported elaboration, ensuring that the information patients receive is verifiable and clinically reliable.

2. **Checklist‑guided reward** – for context‑dependent goals such as demand satisfaction and expression quality, G‑CARL generates instance‑specific weighted checklists (refined by clinicians). The reward emphasizes the checklist items most relevant to the current report and user question, providing transparent supervision that the response addresses the patient’s concerns appropriately.

By aligning rewards with verifiability and patient‑specific needs, G‑CARL consistently outperforms supervised and other reinforcement‑learning baselines, with gains confirmed by clinician preference and user comprehension studies. This leads to more accurate, relevant, and patient‑friendly medical interpretations, thereby improving patient‑oriented outcomes.

**Source:** arXiv ID 2608.20331v1.

Expected source: 2608.20331v1
------------------------------------------------------------

In [40]:
# Create answer evaluation table

answer_evaluation_df = rag_results_df[
    [
        "id",
        "question",
        "answer",
        "expected_arxiv_id"
    ]
].copy()

# Manual evaluation
# 0 = poor, 1 = partial, 2 = strong

answer_evaluation_df["answer_relevance"] = [
    2,  # Q1
    2,  # Q2
    2,  # Q3
    2,  # Q4
    2,  # Q5
    2,  # Q6
    2,  # Q7
    2   # Q8
]

answer_evaluation_df["faithfulness"] = [
    2,  # Q1
    2,  # Q2
    2,  # Q3
    2,  # Q4
    2,  # Q5
    2,  # Q6
    2,  # Q7
    2   # Q8
]

answer_evaluation_df["citation_accuracy"] = [
    2,  # Q1
    2,  # Q2
    2,  # Q3
    2,  # Q4
    2,  # Q5
    2,  # Q6
    2,  # Q7
    2   # Q8
]

answer_evaluation_df

,id,question,answer,expected_arxiv_id,answer_relevance,faithfulness,citation_accuracy
0,Q1,What problem does Pandora's AI Model Routing B...,Pandora’s AI Model Routing Box tackles the cha...,2608.20316v1,2,2,2
1,Q2,How does Pandora's AI Model Routing Box improv...,Pandora’s AI Model Routing Box improves effici...,2608.20316v1,2,2,2
2,Q3,What is AI4AI-Bench designed to evaluate?,AI4AI‑Bench is a benchmark that tests whether ...,2608.20318v1,2,2,2
3,Q4,How does AI4AI-Bench assess the performance of...,AI4AI‑Bench evaluates an LLM agent by letting ...,2608.20318v1,2,2,2
4,Q5,What information is used to induce task models...,Task models are induced from the low‑level eve...,2608.20319v1,2,2,2
5,Q6,What is the purpose of the agentic approach fo...,The agentic approach is designed to unify the ...,2608.20320v1,2,2,2
6,Q7,What problem does grounded checklist-aligned r...,Grounded checklist‑aligned reward learning (G‑...,2608.20331v1,2,2,2
7,Q8,How is reward learning used to improve patient...,Reward learning in G‑CARL improves patient‑ori...,2608.20331v1,2,2,2

In [41]:
# Calculate generation metrics

answer_relevance = (
    answer_evaluation_df["answer_relevance"].mean() / 2
)

faithfulness = (
    answer_evaluation_df["faithfulness"].mean() / 2
)

citation_accuracy = (
    answer_evaluation_df["citation_accuracy"].mean() / 2
)

print("Baseline RAG Generation Performance")
print("-" * 40)
print(f"Answer Relevance: {answer_relevance:.2%}")
print(f"Faithfulness: {faithfulness:.2%}")
print(f"Citation Accuracy: {citation_accuracy:.2%}")

Baseline RAG Generation Performance
----------------------------------------
Answer Relevance: 100.00%
Faithfulness: 100.00%
Citation Accuracy: 100.00%

In [42]:
# Final baseline RAG results

final_results = pd.DataFrame({
    "Metric": [
        "Hit@1",
        "Hit@3",
        "Hit@5",
        "Answer Relevance",
        "Faithfulness",
        "Citation Accuracy"
    ],
    "Score": [
        hit_at_1,
        hit_at_3,
        hit_at_5,
        answer_relevance,
        faithfulness,
        citation_accuracy
    ]
})

final_results["Score"] = final_results["Score"].map(
    lambda x: f"{x:.2%}"
)

final_results

              Metric    Score
0              Hit@1  100.00%
1              Hit@3  100.00%
2              Hit@5  100.00%
3   Answer Relevance  100.00%
4       Faithfulness  100.00%
5  Citation Accuracy  100.00%

In [43]:
# Save generated RAG answers

rag_results_df.to_csv(
    processed_dir / "baseline_rag_answers.csv",
    index=False
)

print("Saved: baseline_rag_answers.csv")

Saved: baseline_rag_answers.csv

In [44]:
# Save manual answer evaluation

answer_evaluation_df.to_csv(
    processed_dir / "baseline_answer_evaluation.csv",
    index=False
)

print("Saved: baseline_answer_evaluation.csv")

Saved: baseline_answer_evaluation.csv

In [45]:
# Save final baseline RAG results

final_results.to_csv(
    processed_dir / "baseline_rag_results.csv",
    index=False
)

print("Saved: baseline_rag_results.csv")

Saved: baseline_rag_results.csv

## Baseline RAG Evaluation Summary

The baseline RAG pipeline was evaluated using an eight-question benchmark covering the five research papers in the dataset. Retrieval performance was measured using Hit@1, Hit@3, and Hit@5, while generated responses were manually evaluated for answer relevance, faithfulness to the retrieved context, and citation accuracy.

The baseline achieved 100% Hit@1, Hit@3, and Hit@5 on the benchmark. The generated responses also achieved 100% on answer relevance, faithfulness, and citation accuracy based on the manual evaluation.

These results indicate that the baseline pipeline successfully retrieved the expected source paper and generated relevant, context-supported answers for the benchmark questions. However, the benchmark contains only eight questions, so these results should be interpreted as baseline performance on the current evaluation set rather than evidence of general RAG performance.

## Evaluation Methodology

### Retrieval Evaluation

Retrieval performance was evaluated using three metrics:

- **Hit@1:** whether the expected source paper was ranked first.
- **Hit@3:** whether the expected source paper appeared within the top three retrieved results.
- **Hit@5:** whether the expected source paper appeared within the top five retrieved results.

### Generation Evaluation

Generated answers were manually evaluated using a 0–2 scale:

- **Answer Relevance:** whether the response directly answers the benchmark question.
- **Faithfulness:** whether the response is supported by the retrieved research context.
- **Citation Accuracy:** whether the cited arXiv source corresponds to the expected source paper.

A score of 2 represents a strong result, 1 represents a partial result, and 0 represents an incorrect or unsupported result.